### ISSUE TITLE
Enabling Voice Only+Minimal+Hide Channels=Trouble

### ISSUE THREAD

**Issue by g33z3r-hd** [Jiiks/BetterDiscordApp#100]
When enabling these 3 options together, there is no way to access the settings menu again to undo this change and, as such, I can find no way to actually use Discord with Better Discord installed.

**Comment by Jiiks** [comment]
There's a small R button in the servers list that restores channels.

**Comment by omegajesus** [comment]
Is there a way to re-hide the channels after clicking that R without going back into the settings every time?
