### ISSUE TITLE
0.2.5 Windows Installer fails to install the plugin (no errors)

### ISSUE THREAD

**Issue by DinckelMan** [Jiiks/BetterDiscordApp#106]
The title says it all. Tried closing discord and installing later, or restarting the app with the checkmark, same result.

Any ideas what's up?

**Comment by DoNotSpamPls** [comment]
We can't help you with so little information.
What's wrong? Can you provide us with some screenshots? What plugin are you installing? etc.
Edit the post with some more info and we will try to help you
