### ISSUE TITLE
0.2.5 Windows- Javascript error on launching Discord

### ISSUE THREAD

**Issue by JJostar** [Jiiks/BetterDiscordApp#108]
![ss 2015-12-23 at 02 26 30](https://cloud.githubusercontent.com/assets/16389893/11982461/b0efdcf2-a981-11e5-9f21-29dd1b8417b9.png)
Also, it gets stuck here:
![ss 2015-12-23 at 02 31 17](https://cloud.githubusercontent.com/assets/16389893/11982476/e6cdda4a-a981-11e5-92e5-41be8c1142b9.png)
There is no BetterDiscord option in User Settings. The only emotes that show up are TKBreezy sub emotes, no other twitch emotes (even from the other channel I'm subbed to) work, nor do any default twitch/FFZ/BTTV emotes.
![ss 2015-12-23 at 02 57 32](https://cloud.githubusercontent.com/assets/16389893/11982980/3efb172e-a986-11e5-97b6-378e1815f98c.jpg)

**Comment by JJostar** [comment]
It works now. I didn't even do anything.¯\_(ツ)_/¯

**Comment by velkovjr** [comment]
I get the same problem, but it doesn't fix itself.
Please help

**Comment by Jiiks** [comment]
There's something wrong with your emotedata. Delete the cached files @ %appdata%\BetterDiscord and restart.

**Comment by DoNotSpamPls** [comment]
Did it, didn't help
Please help

**Comment by DoNotSpamPls** [comment]
*Fix added to the FAQ in the wiki*
#Close
