### ISSUE TITLE
0.2.5 Windows Installer fails to install

### ISSUE THREAD

**Issue by Sunriz3D** [Jiiks/BetterDiscordApp#109]
http://i.imgur.com/3N8XLKt.png

**Comment by Bluscream** [comment]
![s](https://i.imgur.com/3N8XLKt.png)

**Comment by Jiiks** [comment]
Make sure you're not accessing that folder with anything and run as admin.

**Comment by Sunriz3D** [comment]
I tried to run as admin, not accessing the folder too ( I have nothing to do in it, so not gonna open it ^^', even editing files I don't have the skills !  )

Tried to disable my antivirus ( Eset Smart Security ) not working too.

**Comment by Jiiks** [comment]
You could try the node installer package

**Comment by Sunriz3D** [comment]
Is it up to date ? its version 0.2.3 and the win installer is 0.2.5
