### ISSUE TITLE
[Suggestion] Favorite emotes organization

### ISSUE THREAD

**Issue by jacobmix** [Jiiks/BetterDiscordApp#111]
Being able to organize your favorite'd emotes would be a great feature.
"Drag and Drop" Would be preferred. Just drag, and drop them to change their order.

**Comment by Jiiks** [comment]
Added to todo list

**Comment by jacobmix** [comment]
Do you actually have a public todo list? Or do you just have a private/mental one?

**Comment by Jiiks** [comment]
Private and it's still there :P 
Although it keeps getting pushed down by more important ones.
