### ISSUE TITLE
Add search for message

### ISSUE THREAD

**Issue by Streusel** [Jiiks/BetterDiscordApp#113]
This is pretty straight forward, in a website you hit cmd+f, ctrl+f and search, in some irc clients you can do it, in discord you can't. Got pinged and you were away only to have to scroll back up to where you got pinged? Use the search and type in @streusel in my case for instance to scroll to the position on the page where it was posted.

**Comment by Jiiks** [comment]
Because Discord only displays x amount of messages, this is really not possible at the moment.
It would require a method that takes control of your client, scrolls up waiting for Discord to load more messages and searches those.
