### ISSUE TITLE
Not working on Chrome?

### ISSUE THREAD

**Issue by CodyMKW** [Jiiks/BetterDiscordApp#140]
I installed BetterDiscord on Chrome from the site but when I go to Discord I don't see any settings for BetterDiscord at all

**Comment by pohky** [comment]
If the emotes are showing then it works, the browser versions only support showing emotes for now (no settings or anything else).

**Comment by CodyMKW** [comment]
Oh ok the emotes do work I didn't know settings didn't work yet for browser version
