### ISSUE TITLE
Public Servers list broken?

### ISSUE THREAD

**Issue by Kaeloron** [Jiiks/BetterDiscordApp#141]
Hi guys,

noticed this morning after restarting discord that the public servers list does not show any servers anymore? There is just a placeholder without invite code/name etc. left over in the list. 

On the same topic: does BD have an update functionality for itself, or do you have to redownload the client always fresh from GitHub to get the newest version?

Best regards,
Kaeloron

**Comment by pohky** [comment]
It was indeed broken. Fixed.
