### ISSUE TITLE
Cannot load twitch sub emotes

### ISSUE THREAD

**Issue by Candunc** [Jiiks/BetterDiscordApp#15]
Using v0.1.5 beta, on OS X.

When loading the Twitch Subscriber Emotedata, I get the following error:

```
*A JavaScript error occurred in the main process*

Uncaught exception:
Error: ENOENT: no such file or directory, open '../BetterDiscordData/emotes_twitch_sub.json' at Error (native)
```

I am unable to test on Windows at the moment, so I am unsure if this is OS specific due to the implementation of BetterDiscord. 

![err](https://cloud.githubusercontent.com/assets/549161/10770447/ff9ce898-7cb0-11e5-8c68-478b4cfdd8e3.png)

**Comment by Jiiks** [comment]
This is due to emotedata being cached locally and the path doesn't exists on mac. 
It should still load the emotes just not cache them.

https://github.com/Jiiks/BetterDiscordApp/blob/master/lib/BetterDiscord.js '_dataPath' should be made os-specific.

**Comment by Candunc** [comment]
Ok, I can do that later tonight!
