### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by SirDoctors** [Jiiks/BetterDiscordApp#153]

**Comment by Jiiks** [comment]
Maybe once there's a official linux app, closing for now.

**Comment by TheDoctorsLife** [comment]
There's an offical linux app now, so will we be seeing better discord available for the Linux builds?

**Comment by Jiiks** [comment]
No eta but yes.

**Comment by sarnex** [comment]
My PR, based on Francesco149's original,  is working and is not platform specific anymore.

**Comment by Serkan-devel** [comment]
Discord canary on Linux is very usable already. +1 for Linux support

**Comment by TheDoctorsLife** [comment]
@Jiiks @sarnex's PR is at the latest version of discord and is working pretty well, any chance you could take a look and see if it's all cool to get this issue resolved?
