### ISSUE TITLE
After getting PTB to work with BDA the CustomCSS is broken

### ISSUE THREAD

**Issue by AraHaan** [Jiiks/BetterDiscordApp#169]
So lets just say you have a Custom CSS in Discord Canary and/or Discord and you get PTB working.
All of your CSS work would become just these 2 chars in that box.
``ée``.
@Jiiks pl0x fix this.

**Comment by Jiiks** [comment]
atob issue with empty data https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/atob
