### ISSUE TITLE
JavaScript Error (PC)

### ISSUE THREAD

**Issue by DenialPanda** [Jiiks/BetterDiscordApp#179]
I looked on the FAQ and tried step 1. That did not work.
Step 2 is a dead link, so it did not help either.

I am not sure what to do as the error pops up everytime. The bar at the bottom right also gets stuck.

Pictures: 
https://gyazo.com/19b5f51a6e8be68a9d51911a206d9c07
https://gyazo.com/6fbb5ae7e29840adbeb2851416de11b2

**Comment by AetherXCloud** [comment]
I am also having this issue if anyone has a solution please advise

**Comment by demodude4u** [comment]
I'm not sure when it'll be fixed, but there is a temporary workaround to replace the erronous BetterDiscord.js file with this one [https://raw.githubusercontent.com/Jiiks/BetterDiscordApp/master/lib/BetterDiscordT.js](https://raw.githubusercontent.com/Jiiks/BetterDiscordApp/master/lib/BetterDiscordT.js)

Then kill discord and restart it.

**Comment by Pand3m0nia** [comment]
Hi there,

By following the FAQ and by replacing the.js file I eventually got BetterDiscord to work. The problem I have now is that only the emote FeelsBadMan works, and none of the others. Also, under the "Global" tab only "emote" appears with a broken image file.

Any advice?

**Comment by djdairy** [comment]
I have also followed the FAQ and got Better Discord working again with only the FeelsBadMan emote. Until someone comes up with a fix I supposed we can all take solace in the fact that the emote most relevant to the situation is the only emote which survived.

FeelsBadMan

**Comment by gmt2001** [comment]
I figured it out. BetterDiscord is using http (not https) to get the Twitch emote data from twitchemotes.com, however, twitchemotes.com just blocked non-https connections to this data. The patch to fix everything is to start with a fresh copy of https://raw.githubusercontent.com/Jiiks/BetterDiscordApp/master/lib/BetterDiscord.js and then make the following change

Find line 352, replace with
`            'domain': 'twitchemotes.com',`

Find line 353, replace with
`            'url': '/api_cache/v2/global.json',`

Find line 360, replace with
`            'https': true,`

Find line 367, replace with
`            'domain': 'twitchemotes.com',`

Find line 368, replace with
`            'url': '/api_cache/v2/subscriber.json',`

Find line 375, replace with
`            'https': true,`

**Comment by gmt2001** [comment]
Pull request created with patch #180

**Comment by djdairy** [comment]
Thanks gmt2001! Kreygasm NOW Kreygasm WE Kreygasm MEME Kreygasm

**Comment by cosmicsalad** [comment]
https://github.com/Jiiks/BetterDiscordApp/blob/master/lib/BetterDiscordT.js already does this btw

**Comment by eeyou** [comment]
Interesting is that both gmt2001 and demodude4u fixes seem not always to work.
I had the same issue, tried demodude4u fix at work and it helped, but when I tried both gmt2001 and demodude4u fixed, I didn't work for me. Error is gone, but all I can see is Feels<...>Man emotes.
Any ideas?

**Comment by gmt2001** [comment]
That file makes it pull from a manually updated file in this repo. My fix pulls from the live list on twitchemotes.com which is constantly updated

**Comment by Jiiks** [comment]
Fixed in 0.2.6
