### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by Coachinator** [Jiiks/BetterDiscordApp#18]
http://prntscr.com/8w6aei

After installing discord, the node, and answering yes to the question in the cmd, that's what came up after re-opening discord.

**Comment by Jiiks** [comment]
Looks like i forgot to edit the Utils.js in the release.
It's fixed now so either download the installer again or replace the Utils.js file with the one here: https://github.com/Jiiks/BetterDiscordApp/blob/master/lib/Utils.js
