### ISSUE TITLE
[Question] Custom CSS, calling local files

### ISSUE THREAD

**Issue by TheLastMelody** [Jiiks/BetterDiscordApp#185]
How do I call local files in a custom made css?
url ("file:///Users/username/Desktop/background.png") is not working. Not sure what that means.

**Comment by T3charmy** [comment]
What OS are you using? Windows? if so, you might need to do

url ("file://C:/Users/username/Desktop/background.png")

**Comment by TheLastMelody** [comment]
That doesn't work either, nor does file:///~Users/username/Desktop/background.png or file://

**Comment by AraHaan** [comment]
Well for Starters. 1 Do not load local images. 2 Upload them to some server like puu.sh r something.
@TheLastMelody

**Comment by TheLastMelody** [comment]
@AraHaan Yeah, that's what I'm doing. It's just a pain to have to upload pictures just because I want to change background. I know I'm not the only one with this issue. But, meh, if that's how it is I'll just have to live with it.
Just a simple question thou, why doesn't it work?

**Comment by AraHaan** [comment]
Idek

**Comment by iVEnoVaLue** [comment]
I made a plugin for it, because only base64 and https data is allowed.

**Comment by TheLastMelody** [comment]
What plugin is it?

**Comment by iVEnoVaLue** [comment]
https://github.com/iVEnoVaLue/BetterPlugins/tree/master/plugins
It's a little bit tricky to use, cause i rely on betterdiscord (this could easily be implemented in BD btw) 
The plugin seeks for links starting with local:// reads image's contents and translates it into base64, then replaces the link with base64 data. You have to have in %appdata%/BetterDiscord/ a folder 'images' (it gets created after the plugin runs once)

**Comment by TheLastMelody** [comment]
Damn, it was the whole moving images thing I really wanted to avoid, but oh well. Thanks pal ^_^
I too rely on BD nowadays.

**Comment by iVEnoVaLue** [comment]
You specify local://imagename.ext, it points directly to that folder

**Comment by TheLastMelody** [comment]
I don't follow. If I use local://imagename.ext will it look in the images folder, or the root folder?

**Comment by iVEnoVaLue** [comment]
In the images folder. 
local://   ->   %appdata%/BetterDiscord/images

**Comment by TheLastMelody** [comment]
That was what I was asking. But thanks pal. How do I close this?

**Comment by TheLastMelody** [comment]
Nevermind, found the button. *derpface*
