### ISSUE TITLE
Can't upload files, theme and plugin list broken

### ISSUE THREAD

**Issue by MashaScream** [Jiiks/BetterDiscordApp#186]
When I try to upload files they don't unless I use the Chrome page.

The plugin and theme lists are broken, nothing shows up but idk if that's intended.

BetterDiscord v0.2.6, 64bit Windows 10. Tried running it in compatibility mode for Win7 + admin, didn't work.

**Comment by EhsanKia** [comment]
Do you have any themes/plugins installed?

Try removing all of them and see if it works properly.
