### ISSUE TITLE
How To Manually Install BD On Mac?

### ISSUE THREAD

**Issue by Outsanity** [Jiiks/BetterDiscordApp#187]
I did it the first time by pure dumb luck but what are the steps to manually drag and drop folders/files?

**Comment by jzanutto** [comment]
You need an app folder in /Applications/Discord.app/Contents/Resources/ which you can get by using the asar node module to extract the app.asar folder (the index.js file in the root BD directory). If you have an app directory you should simply be able to drag and drop the BetterDiscord folder into the /Applications/Discord.app/Contents/Resources/app/node_modules/ folder and restart Discord. Discord should pick up the node extension when it starts.

This is what I did.

**Comment by Jiiks** [comment]
Installer should work fine again https://github.com/Jiiks/BetterDiscordApp/pull/189
https://github.com/Jiiks/BetterDiscordApp/releases/tag/v0.2.6OSX
