### ISSUE TITLE
Edited message will cause emotes to disappear

### ISSUE THREAD

**Issue by zSoulweaver** [Jiiks/BetterDiscordApp#19]
Noticed this one for awhile, just decided to report it now, but when you edit a message the emote returns back to a text form, I'm not sure if it does that for others, but I'd assume it does.

Also, loving the new update, cheers!

**Comment by Jiiks** [comment]
This is a known bug, I just haven't had the time to fix it but will make it a priority.

**Comment by Jiiks** [comment]
This has been fixed in the latest version.
