### ISSUE TITLE
Emote API/implementing custom emotes

### ISSUE THREAD

**Issue by Lombra** [Jiiks/BetterDiscordApp#197]
Hello,
Is there any emote API to tap into? Otherwise, how would I go about adding my own emotes? Let's say I have a page returning a JSON object with `'emote': 'path'` mappings. Any place I can check for a simple implementation?

**Comment by Candunc** [comment]
You'd have better luck looking at [FrankerFaceZ](http://www.frankerfacez.com/) or [BTTV](https://nightdev.com/betterttv/) and uploading a custom emote there, I'm afraid there isn't a specific emote API in BetterDiscord, nor do I know how to make a custom plugin with that support.

**Comment by pohky** [comment]
There is no such thing right now and it's also not planned to add support for anything else than [FrankerFaceZ](http://www.frankerfacez.com/), [BTTV](https://nightdev.com/betterttv/) and [Twitch](http://www.twitch.tv/).
