### ISSUE TITLE
Add a way to filter emotes

### ISSUE THREAD

**Issue by Candunc** [Jiiks/BetterDiscordApp#20]
I know this is on your todo list, however it is somewhat annoying that twitch has allowed words like 'Hey' to correspond to emotes. For example, in the subscriber.json there is the following entry:
```
"ilastpack":{
"title":"Ilastpack",
"link":"http:\/\/twitch.tv\/ilastpack",
"desc":null,"id":"ilastpack",
"badge":"\/\/static-cdn.jtvnw.net\/jtv_user_pictures\/subscriber-star.png",
"set":1339,
"emotes":[{"code":"Hey","image_id":5038}]}
```
Which brings up this emote ![](http://static-cdn.jtvnw.net/emoticons/v1/5038/\/1.0)

Thanks for all your hard-work Jiiks, BetterDiscord is absolutely fantastic.

**Comment by Jiiks** [comment]
I completely forgot those existed(I had them removed on my own lists).
Added a check to ignore any words below 4 characters.

Thanks :)
