### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by JohnChorley1** [Jiiks/BetterDiscordApp#219]
I try and open install.sh in a terminal and it gives me an error saying it can't find the module index.js. Is there any fix for this?

**Comment by mkody** [comment]
What version of OS X are you using? Can you share your Node.JS version? (Run `node --version` in a terminal.)

**Comment by Zyst** [comment]
I also have an issue where the `install.sh` file is running but not actually installing as of Discord Version 1.0.0 (0.0.236)

`node --version` output is `v5.8.0`

Running the `install.sh` after `killall Discord` leads to the following output:

```
zyst@BLACKORDER:~/Downloads/BD0.2.61OSX$ sudo sh install.sh
Password:
BetterDiscord Simple Installer v0.3 for Discord 0.0.284 by Jiiks.
If Discord has updated then download the latest installer.
The following directories will be deleted if they exists: discorpath/app, discordpath/node_modules/BetterDiscord, is this ok? Y/NY
Looking for discord resources at: /Applications/Discord.app/Contents/Resources
Discord resources found at: /Applications/Discord.app/Contents/Resources
Looking for app folder
Deleting /Applications/Discord.app/Contents/Resources/app folder.
Deleted /Applications/Discord.app/Contents/Resources/app folder.
Deleting /Applications/Discord.app/Contents/Resources/node_modules/BetterDiscord folder.
Deleted /Applications/Discord.app/Contents/Resources/node_modules/BetterDiscord folder.
Looking for app archive
App archive found at: /Applications/Discord.app/Contents/Resources/app.asar
Extracting app archive
Copying BetterDiscord
Extracted to: /Applications/Discord.app/Contents/Resources/app
Injecting index.js
Injected index.js
Deleting old cache files
Looks like we're done here
```

But the application will not actually have the new "Better Discord" option:

![Non available](https://cloud.githubusercontent.com/assets/3832380/14064083/fdb595ee-f3b0-11e5-8fef-f1fdc6b00ce4.png)

**Comment by mkody** [comment]
Huh, oh. I just lost BetterDiscord on my machine by trying again the install.sh, I now have the same results as @Zyst. But this should go on an another issue.

**Comment by Zyst** [comment]
I went down the list of installers all the way to 2.5, none of them worked.

2.5 does have a popup that mentions there's a new version available, but the settings menu and the like don't exist.

**Comment by Jiiks** [comment]
Does 0.2.7 fix this? https://github.com/Jiiks/BetterDiscordApp/releases/tag/v0.2.7

**Comment by mkody** [comment]
@Jiiks I can confirm it works for me now!
Maybe wait for @Zyst to confirm too. :)

**Comment by Jiiks** [comment]
Going to close since this is getting old. If you still have issues then open a new issue.
