### ISSUE TITLE
Enabling "Voice Mode" bug

### ISSUE THREAD

**Issue by RedSnt** [Jiiks/BetterDiscordApp#22]
Enabling "Voice Mode" in v0.1.5 beta breaks discord. Not sure I've tested all possible scenarios but when enabling BTTV and FFZ emote support, quick emote menu and public servers this definitely breaks discord as soon as you enable Voice Mode.  
I'm thinking it might be related to the quick emote menu, but not sure.

**Comment by Jiiks** [comment]
Seems to only happen when using the direct messages tab.

**Comment by Jiiks** [comment]
This has been temporarily fixed with a timeout(voice mode resets every time you switch channels).
