### ISSUE TITLE
BetterDiscord does not work with latest version of Discord

### ISSUE THREAD

**Issue by Candunc** [Jiiks/BetterDiscordApp#23]
I really don't want to type this out, but here is the error message:

![err](https://cloud.githubusercontent.com/assets/549161/10865951/a0be4a26-7fe2-11e5-9394-09d75c482dca.png)

Operating System is OS X, not entirely sure what version of Discord this is.

**Comment by Jiiks** [comment]
Was there an update for OSX?

**Comment by Candunc** [comment]
Apparently so, must have come out this morning; I had no issues last night.

**Comment by Jiiks** [comment]
Just tested it on a vm and yeah installer needs separate values for osx.
Try replacing your installer index with the latest one:
https://github.com/Jiiks/BetterDiscordApp/blob/master/NodeInstaller/index.js
and rerun installer.

**Comment by Candunc** [comment]
Yup, that does work! Might need to look for a way to do it automatically, so it doesn't have to be updated every single version?

**Comment by Jiiks** [comment]
Yep making it automated would be the best, I just haven't gotten around to doing it.

**Comment by Jiiks** [comment]
Yes at the moment you'll have to download the latest version when there's a major update.

As for the download, looks like the upload failed but it's up now :+1:

**Comment by ROBOTYMOUS** [comment]
if i download betterdiscord+ i only get Custom Game v1.0 and Guilds Scrollbar v1.0﻿ ...
