### ISSUE TITLE
Old emotes

### ISSUE THREAD

**Issue by Confuseh** [Jiiks/BetterDiscordApp#235]
Meanwhile when new emotes are being delivered quite often, old ones that are already removed in BTTV/FFZ are not removed in BD.

**Comment by EhsanKia** [comment]
The problem is that it's not easy to detect those. The database has 20k emotes, and short of checking all 20k emotes every week, there's now way to cleaning deleted emotes.

**Comment by Confuseh** [comment]
I agree, I'll probably have my own check and create pull request deleting old emotes.

**Comment by EhsanKia** [comment]
Can you pass the ideas here first? I maintain the BTTV database, but I try to be gentle on their servers. I do have connections with NightDev though and might be able to get a database out of them.

**Comment by Confuseh** [comment]
Well my idea was bulk-requesting BTTV, but that'd probably be hurtful, kinda don't want to do that.
