### ISSUE TITLE
Quick Emote menu not showing up

### ISSUE THREAD

**Issue by TormDeltest** [Jiiks/BetterDiscordApp#238]
Hi, I recently installed BetterDiscord and Im having an issue with button to open Quick Emote Menu keeps missing. It showed once but after I rebooted PC that night it dissapiered for good. And yes I do have it enabled in settings. Similar problem do have few of my guild mates who are using Discord aswell and recently installed BetterDiscord.

**Comment by Jiiks** [comment]
Is it working now?

**Comment by Bro0da** [comment]
i have the same problem ...quick emote menu is enabled but there is no button .

**Comment by razerocksxd** [comment]
I, too, am having this issue. Have been for about a week now. I've tried updating, downgrading, reinstalling, deleting local files, and even CSS. Nothing seems to solve the issue. I can't seem to find it in the inspect element (ctrl+shft+i)  thing either. Any help would be appreciated.

**Comment by TormDeltest** [comment]
Sometimes the menu is still not showing up (usually when I start discord). But since then I learned that if I swap between servers in discord the menu shows up. So at least I know how to always make it show up but it would be superior if menu was visible straight away :)
