### ISSUE TITLE
Minimal Mode screws up picture aspect ratio

### ISSUE THREAD

**Issue by avail** [Jiiks/BetterDiscordApp#239]
Without:

![Without BetterDiscord](https://a.catgirlsare.sexy/hvshce.png)

With:
![With BetterDiscord](https://a.catgirlsare.sexy/ccfqds.png)

**Comment by Jiiks** [comment]
Minimal mode has a fixed size, will fix soon :tm:

**Comment by Jiiks** [comment]
Fixed in 1.59
