### ISSUE TITLE
parseEmoteData null error

### ISSUE THREAD

**Issue by Mkalo** [Jiiks/BetterDiscordApp#242]
For some reason I was getting this error and a some others because emoteData was null:
http://i.imgur.com/2K5RYxq.png

I managed to fix it placing some ifs: http://pastebin.com/7CGh8QRv

I do not know what caused it tho. For now it seems to be working.

**Comment by Jiiks** [comment]
Should be fixed in https://github.com/Jiiks/BetterDiscordApp/releases/tag/v0.2.7
