### ISSUE TITLE
Better Discord Functions Not Appearing

### ISSUE THREAD

**Issue by Lufufuu** [Jiiks/BetterDiscordApp#251]
None of the functions are appearing, and the emotes don't appear either. When going through the auto installer, it said there was no errors.

**Comment by AraHaan** [comment]
maybe corrupt emote data.I am in process of making a Vanilla Discord PTB that has the normal files + modified app.asar files with BetterDiscord Embedded in it. Downside is that when PTB updates dont update unless I tell you too or Vanilla PTB RIP.

**Comment by shtrih** [comment]
In my case BD is loading, plugins are loading but BD settings tab don't appear.

**Comment by iVEnoVaLue** [comment]
ctrl+shift+i on windows to check for errors

On Mac OSX won't work if you're using the top menu for accessing preferences. Only the button from the application (the browser interface) triggers the display of BetterDiscord menu. Also you can use ctrl+opt +i for chromium console

**Comment by shtrih** [comment]
After `Ctrl+R` I saw `BD what's new 1.59` dialog and settings tab works now.

**Comment by Jiiks** [comment]
Sometimes it fails to load for one reason or another and there's no feedback for it. Will be made more stable when I have time.
