### ISSUE TITLE
Emotes not displaying correctly.

### ISSUE THREAD

**Issue by mrpcguy** [Jiiks/BetterDiscordApp#252]
When I type in an emote, it gets changed to a random different one. No matter what emote I put, it gets changed. The emote I actually put isn't getting displayed at all.
It was working fine yesterday, but today it suddenly isn't working.
This is an issue for me since I use emotes a lot in the discord servers I'm in, and I can't use the ones I want to.

**Comment by AtefBN** [comment]
Yeah i've been meaning to open an issue myself. The emotes are completely random now.

**Comment by mrpcguy** [comment]
Apparently it's an april fools thing. You just have to put `{april2nd}` in your custom CSS.

I guess I can close this issue then.
