### ISSUE TITLE
Emotes: Frustrating issues (certain emotes are too general with their names)

### ISSUE THREAD

**Issue by Wwlink55** [Jiiks/BetterDiscordApp#259]
While not breaking, I'm having a frustrating issue with the Emotes included with BetterDiscord.

Some of the emotes are very general with their name, and just by typing them, you will automatically use them (and you can't disable specific emotes, since the only option is to opt out of many of these emotes is to disable emotes entirely). The one that bothers me the most is Noire.

I'm on a Gamindustri/Neptunia server....and it grinds my gears to have EVER mention of Noire be turned into the emote.  Could we have a way to disable certain emotes, or have emotes require an additional input, such as a semicolon or something?

**Comment by Jiiks** [comment]
Submit a pull request of common words to the blacklist here: https://github.com/Jiiks/BetterDiscordApp/blob/master/data/emotefilter.json
