### ISSUE TITLE
More emotes replacing common words

### ISSUE THREAD

**Issue by Phoenix100k** [Jiiks/BetterDiscordApp#26]
I've discovered "snap" displays a camera emoji. There are a few others I can't think of right now, but it may warrant going through the list and removing other common word replacements. I've noticed they're not Twitch emotes, so they may be from the other packs (BTTV, Franker, etc.)

**Comment by Candunc** [comment]
Nope, again I'd blame it on twitch for allowing common words to use emotes. This time it is someone that goes by fwiz.

```
"fwiz": {
  "title": "Fwiz",
  "link": "http://twitch.tv/fwiz",
  "desc": null,
  "id": "fwiz",
  "badge": "//static-cdn.jtvnw.net/jtv_user_pictures/subscriber-star.png",
  "set": 170,
  "emotes": [
    {
      "code": "FwizzyKid",
      "image_id": 1419
    },
    {
      "code": "PLAYS",
      "image_id": 4568
    },
    {
      "code": "KAPPA",
      "image_id": 4569
    },
    {
      "code": "SLEEPY",
      "image_id": 4570
    },
    {
      "code": "RAGE",
      "image_id": 4571
    },
    {
      "code": "CHYABOI",
      "image_id": 4572
    },
    {
      "code": "FAIL",
      "image_id": 4573
    },
    {
      "code": "snap",
      "image_id": 9182
    }
  ]
},
```

**Comment by Jiiks** [comment]
Yeah they are old partners whose emotes were never removed from the database.

New emote blacklist is now loaded from: https://github.com/Jiiks/BetterDiscordApp/blob/master/emotefilter.json

Just edit that and submit a pull request if you find any bad emotes :+1:

**Comment by Candunc** [comment]
Ok, cool. Thanks Jiiks!
