### ISSUE TITLE
[PTB] Clicking on channels opens in browser

### ISSUE THREAD

**Issue by Miwrzezl** [Jiiks/BetterDiscordApp#275]
When going into a server and clicking on a channel, there's a 90% chance that it'll open in the browser and the client

**Comment by Jiiks** [comment]
Unable to reproduce

**Comment by AraHaan** [comment]
I get this issue too.

**Comment by Jeanolos** [comment]
Your ALT key is stuck. This only happens, when holding down the ALT key

**Comment by Rekkisomo** [comment]
@Jeanolos lolno
