### ISSUE TITLE
When using settings shortcut (cmd+,), BD's settings tab doesn't show.

### ISSUE THREAD

**Issue by jariz** [Jiiks/BetterDiscordApp#276]
If you manually click the gear icon, BD's settings will show, however, when you use the settings shortcut - which is cmd+, on mac - the option isn't available, very much confusing me at first.

**Comment by Jiiks** [comment]
Will investigate

**Comment by iVEnoVaLue** [comment]
I can confirm it doesn't work, and i couldn't make a plugin to work properly for it. It's an event unwatchable like sending an IPC command to show the menu.

**Comment by Jiiks** [comment]
Was fixed in 1.71
