### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Sunriz3D** [Jiiks/BetterDiscordApp#28]
Hello, BetterDiscord was doing fine before the last update. Now it doesn't even show. I tried to reinstall Discord + BetterDiscord not working, tried the last index.js, same.

The installation of BetterDiscord is fine everything is ok, no errors.
But in Discord its like i have not BetterDiscord.

Thanks !

ps : i don't know if there is a log that i can give you

**Comment by Jiiks** [comment]
Unable to reproduce. 
Try running discord from console: cmd /K  "%localappdata%\Discord\app-0.0.280\Discord.exe"
and see if it loads at all.

**Comment by Sunriz3D** [comment]
Not launching with the command.

![discord](https://cloud.githubusercontent.com/assets/1722587/10869739/7559f07a-80b8-11e5-98a3-43d58852cad7.png)

**Comment by Sunriz3D** [comment]
Not launching with the command.

![discord](https://cloud.githubusercontent.com/assets/1722587/10869747/a58d24f6-80b8-11e5-916f-9fa7dd9a7ec7.png)

**Comment by Jiiks** [comment]
Try manually deleting the app folder from %localappdata%\Discord\app-0.0.280\resources
and BetterDiscord folder from %localappdata%\Discord\app-0.0.280\resources\node_modules
and run the latest installer again.

**Comment by Sunriz3D** [comment]
Seems to be working :)

Thanks !

**Comment by Jiiks** [comment]
Awesome :)
