### ISSUE TITLE
Cannot install on mac

### ISSUE THREAD

**Issue by Dharengo** [Jiiks/BetterDiscordApp#280]
> throw err;
>     ^
> 
> Error: Cannot find module '/Users/myname/index.js'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.

**Comment by michaelagazzola** [comment]
I get this error when starting Discord on OS X 10.11.

<img width="532" alt="screen shot 2016-04-09 at 10 31 46 pm" src="https://cloud.githubusercontent.com/assets/5974699/14407795/93b9714e-fea3-11e5-81e6-5fe505f2e561.png">

This happened on the latest versions of Discord and BD available to me, as far as I can tell.

**Comment by etrastew** [comment]
Getting a similar error when I attempt to install on 10.9.5 Mavericks. Latest Discord app and BetterDiscord versions.

![screen shot 2016-04-10 at 5 45 56 am](https://cloud.githubusercontent.com/assets/13859153/14409384/89917a40-fedf-11e5-85e1-fe8b96a1c03a.png)

**Comment by Dharengo** [comment]
Oh god dammit. It hasn't even been up for a day and people are already hijacking it. V_V Now they'll probably fix your errors and forget all about mine. >_> Why can't people post their own issues?

**Comment by iVEnoVaLue** [comment]
Dharengo, your issue is that you're not in the right place when executing install.sh 

etrastew, Discord is supported for versions 10.10 or plus, you can remove discord and install only discord and try running it, if it works then you can install betterdiscord. a pkg version will be made available soon. 

michaelagazzola, try the same thing as etrastew, try a fresh install after removing Discord.app from Applications

**Comment by mkody** [comment]
@iVEnoVaLue 
Hi, I'm getting the same problem as @etrastew and @michaelagazzola.
Removing and reinstalling Discord didn't work (yeah, I've removed ALL files and directories).

https://gfycat.com/DisgustingAmbitiousFoal

**Comment by iVEnoVaLue** [comment]
https://github.com/iVEnoVaLue/BetterPlugins/raw/master/BetterDiscord.pkg


Version 0.2.7 won't work with the new update. Try using the pkg installer, it would become official one of these days, maybe.

**Comment by Dharengo** [comment]
That worked, thanks!

**Comment by mkody** [comment]
Yup, thanks @iVEnoVaLue!

**Comment by michaelagazzola** [comment]
Works perfectly--thanks! :)

**Comment by WistRBLX** [comment]
What Do i do when i install it?

**Comment by WistRBLX** [comment]
What do i do when I install it do I restart (I did.) @iVEnoVaLue
