### ISSUE TITLE
Installed it via terminal, can't run discord. [OSX]

### ISSUE THREAD

**Issue by JohnChorley1** [Jiiks/BetterDiscordApp#281]
I installed Better Discord again and now I keep getting the following error when I try and run discord.
![screen shot 2016-04-11 at 09 21 37](https://cloud.githubusercontent.com/assets/16917454/14420950/cec2c230-ffc6-11e5-8a02-6d6ba7854161.png)

Anyway to fix?

**Comment by iVEnoVaLue** [comment]
https://github.com/iVEnoVaLue/BetterPlugins/raw/master/BetterDiscord.pkg
