### ISSUE TITLE
A JavaScript error occurred in the main process [Solved]

### ISSUE THREAD

**Issue by Novabella** [Jiiks/BetterDiscordApp#283]
![image](https://cloud.githubusercontent.com/assets/17990493/14547308/1750ed6e-0261-11e6-964c-9dd4eb179abf.png)

I've looked for explanations, but no one has talked about this exact error yet. I've reinstalled both discord, and better discord, and it's definitely caused by better discord.

**Comment by iVEnoVaLue** [comment]
in your themes / plugins you have a folder

**Comment by Novabella** [comment]
Where can I find that folder?

**Comment by iVEnoVaLue** [comment]
%appdata%/BetterDiscord 
Inside there are 2 folders, plugins and themes. Either of them has to contain  folders

**Comment by Novabella** [comment]
Thanks! All better.
