### ISSUE TITLE
An emote modifier to make emote bigger

### ISSUE THREAD

**Issue by marco213** [Jiiks/BetterDiscordApp#284]
By modifying the appdata's emote_bttv.json, I was able to use other scale of certain emotes by changing the 1x to 2x, and it looks great. But my Json file get replace on every restart and I was wondering if this could be a feature. It does not seems to break anything, plus it looks cool

http://i.imgur.com/cSPsTnZ.png

**Comment by Jiiks** [comment]
I thought about this and decided not to since not every emote has a bigger version and some that do have terrible quality.
Not to mention the possible abuse(not like the current modifiers aren't abused enough)
