### ISSUE TITLE
Provide support for meta information in CSS comment

### ISSUE THREAD

**Issue by waut3r** [Jiiks/BetterDiscordApp#289]
Hello,

I use SASS for writing CSS, and I have found that there is no way to output meta information that will be output in the compiled file. For instance:

```
// compileExpanded: ../themes/$1.css
//META{"name":"waut3rs_theme","description":"Something that matches the general feel of Windows 10 with tweaks here and there.","author":"waut3r","version":"1.0" }*//

* {
    background:#FF0;
}
```

In this example, the META information will disappear, as it will be interpreted as a SASS comment. The output looks like this:

```
* {
  background: #FF0;
}
```

My proposition is to provide support for CSS comments. The input would ideally look like:
`/*! META{"name":"waut3rs_theme","description":"Something that matches the general feel of Windows 10 with tweaks here and there.","author":"waut3r","version":"1.0" } */`

The output (what would be seen by BDA) would look like:
`/* META{"name":"waut3rs_theme","description":"Something that matches the general feel of Windows 10 with tweaks here and there.","author":"waut3r","version":"1.0" } */`

**Comment by Jiiks** [comment]
Will look into it. 

What are you using to compile sass? With grunt you could use: [grunt-file-append](https://www.npmjs.com/package/grunt-file-append)

and something like:

```
file_append: {
    default_options: {
        files: [{
            prepend: '//META{"name":"waut3rs_theme","description":"Something that matches the general feel of Windows 10 with tweaks here and there.","author":"waut3r","version":"1.0" }*//'
            input: 'pathtocss',
            output: 'pathtocss'
        }]
    }
}
```

**Comment by waut3r** [comment]
I was using Sass-autocompile for Atom. Doing a quick search, there seems to be grunt extensions which may prove to be useful. In the mean time I've just been theming with pure CSS.
