### ISSUE TITLE
Better Discord failing to start Win10

### ISSUE THREAD

**Issue by sng428** [Jiiks/BetterDiscordApp#29]
Getting this error on startup on Windows 10
![error_biblethump](https://cloud.githubusercontent.com/assets/15619381/10895014/a96e11da-8166-11e5-970a-8a84cf8b6e27.png)
Unsure as to what is the cause.

**Comment by Candunc** [comment]
Discord seems to have 'unofficial' updates that accidentally break things like BetterDiscord. Although BetterDiscord does _start_, it seems to hang on loading twitch emotes.

**Comment by Jiiks** [comment]
Looks like it failed to load some resource.
Try deleting the following folders and run the latest installer again.

%localappdata%\Discord\app-0.0.280\resources\app
%localappdata%\Discord\app-0.0.280\resources\node_modules\BetterDiscord
%localappdata%\Discord\BetterDiscordData

**Comment by sng428** [comment]
Resolved! Thanks for the help!
