### ISSUE TITLE
Cannot read property 'LatestVersion' of null

### ISSUE THREAD

**Issue by Zegura** [Jiiks/BetterDiscordApp#293]
![image](https://cloud.githubusercontent.com/assets/6127568/14942021/ebe1a808-0ff3-11e6-978a-b05cea765d6f.png)

Getting this attempting to install BetterDiscord with fresh Discord install.

**Comment by Jiiks** [comment]
Has this been fixed with 0.2.8?

**Comment by Zegura** [comment]
Sorry for the (very) delayed response. 

Yep! Seems to be working fine with 0.2.8.
