### ISSUE TITLE
[suggestion] Support for Android

### ISSUE THREAD

**Issue by whamer100** [Jiiks/BetterDiscordApp#294]
I've been a user of BetterDiscord for a very long time, and I wanna see support for Android (At least to the point of Twitch emotes

-whamer100

**Comment by Jeanolos** [comment]
Frankly, that's not really possible. It would require either rebuilding the whole Discord app or using Xposed. For both, the knowledge of either Java or C# and Android itself is required.

Additional to that, the users that want it would have to install the Xposed Framework on their phones.

So, no. There won't be Android support anytime soon

**Comment by Schwertspize** [comment]
Frankly Its not even as easy as what you said. I looked into the app code some time ago to do some custom styling myself and I failed to overwrite a single color. Apart from that, I would consider myself as knowledge of Java and Android. 

Besides, no C# in android apps.

**Comment by p8tgames** [comment]
Well, now we have tools like apktool and magisk. If com.discord isn't proguarded I'll take a look at my possibilities.

**Comment by PurpleCoffee** [comment]
p8tgames betterdiscord would be really cool for android.

**Comment by Lillievela** [comment]
Any Update on this p8tgames?

**Comment by xslendix** [comment]
Imma try make this a reality 2morrow

**Comment by IpProxyNeon** [comment]
Any breakthroughs?

**Comment by Lost0Neko** [comment]
Anything?👀

**Comment by p8tgames** [comment]
Hello!
Sadly no. I did take multiple looks at the discord app and found ways to
enable some hidden gems before, but I’m not very experienced with smali and
other required stuff.

Lost0Neko <notifications@github.com> schrieb am Sa. 30. Mai 2020 um 20:58:

**Comment by xslendix** [comment]
Ok, I found a way to do this but will take lots of time and only themes will be able to be implemented. You decompile the app with apktool, look for stuff in the xml that you can replace and make a xposed module.

**Comment by p8tgames** [comment]
you might as well make a substratum theme then

**Comment by kalebplayz125** [comment]
Its 2020 anything?

**Comment by Milionerzy11** [comment]
> Bluecord

Thx

**Comment by qCokiEq** [comment]
I wanna see where this goes now

**Comment by andreyr1** [comment]
> Bluecord

https://www.virustotal.com/gui/file/b136e544c1a8b9ee0e9699332c536a432a80c5c437598b1d2d478df58757b12b/detection
