### ISSUE TITLE
Too many emotes overwriting real words

### ISSUE THREAD

**Issue by Gyan1010** [Jiiks/BetterDiscordApp#295]
I'm not a big emote user but I thought most programs have it set so that emoticons need a to be surrounded by colons to be replaced. However, with better discord it seems anything someone might be normally saying like "double" or "may1" gets replaced by the emote. Can you please fix this to require proper syntax for the emotes.

**Comment by SilvieSkydancer** [comment]
If this does get fixed, can you leave its current setting as an option? Me and my friends find this hilarious and it's a staple in our chat.

**Comment by Jiiks** [comment]
If you find emotes that use common words you can submit a pull request to the blacklist located here: https://github.com/Jiiks/BetterDiscordApp/blob/master/data/emotefilter.json
