### ISSUE TITLE
Themes and Plugins no longer shown after recent update

### ISSUE THREAD

**Issue by Noroxuz** [Jiiks/BetterDiscordApp#299]
The recent update of Discord PTB broke BetterDiscord aka. I had to reinstall it manually. Afterwards the plugins and themes, which still are in the corresponding folder are no longer accessible within the Better Discord menu. Its as if nothing is in those folders at all. 

Is this a bug?

**Comment by pohky** [comment]
in the latest BD version themes and plugins have to be names "something.theme.css" or "something.plugin.js" (where .css and .js are the file extension like .txt for textfiles or .jpg for images, not a part of the name)

**Comment by Noroxuz** [comment]
Thanks that solved the issue :+1:
