### ISSUE TITLE
Can't use same emote twice in the same message

### ISSUE THREAD

**Issue by zSoulweaver** [Jiiks/BetterDiscordApp#3]
So, my friend just figured out that you can't use the same emote twice in the same message, instead what you'll see is (Actual Emote)>Kappa. But you can still use a different emote in the same message, but again you can't use it twice.

Please fix this one, I doubt it's a big issue, hopefully is a easy fix?

**Comment by Jiiks** [comment]
I've issued a temporary fix for this. Simply restarting discord will work.
