### ISSUE TITLE
Installer gives an error upon trying to kill Discord

### ISSUE THREAD

**Issue by Terravin** [Jiiks/BetterDiscordApp#300]
I've been trying to install Better Discord for almost an hour now, and it keeps giving me the same error no matter what I try to do.

As for what the error includes, here's a link to a pastebin:
http://pastebin.com/sKhEnzWi

Any help would be greatly appreciated.

**Comment by Jiiks** [comment]
Try running as admin or kill ALL Discord processes yourself before running the installer.
