### ISSUE TITLE
The "LUL" bttv emote isn't working

### ISSUE THREAD

**Issue by Ciys** [Jiiks/BetterDiscordApp#301]
All the bttv emotes are working but not that one.
https://cdn.betterttv.net/emote/567b00c61ddbe1786688a633/1x

**Comment by iVEnoVaLue** [comment]
LUUL

**Comment by mtcjayne** [comment]
Use "LUUL" instead. Since... for whatever reason... @ghost decided to be as unhelpful as possible while being helpful.
