### ISSUE TITLE
Option "Show Emotes" sounds confusing, maybe change it to "Show Twitch Emotes" or similar

### ISSUE THREAD

**Issue by notnsane** [Jiiks/BetterDiscordApp#303]
I left it enabled for months because I thought it disabled _all_ Emotes, including Unicode/Basic Discord Emotes.

This is confusing enough for users that have no idea of Twitch, that just want a theme change and that's it - remember, not every Discord user is a hardcore gamer.

Screenshot attached (sorry for the extra data, it's just to show where it is, which should be obvious)

![screenshot 2016-05-09 04 30 39](https://cloud.githubusercontent.com/assets/7162375/15106299/d550acf0-159e-11e6-8a19-6520f236c47b.png)

**Comment by Jiiks** [comment]
This was changed in 1.71 :+1:
