### ISSUE TITLE
OS X: App refuses to launch with BetterDiscord

### ISSUE THREAD

**Issue by LoosGuccreen** [Jiiks/BetterDiscordApp#304]
I get a javascript error, see atached file

Version used 0.2.7

~~How can I uninstall the thing on OS X ?~~ OK i reinstalled the app and it removed the broken BetterDiscord

![capture d ecran 2016-05-09 a 12 11 41](https://cloud.githubusercontent.com/assets/6335020/15110114/5ee94f54-15df-11e6-9c54-2e5eb693225c.png)

**Comment by Bluffkin** [comment]
Did this get fixed for Discord Version 1.0.0 (0.0.239) ?

**Comment by LoosGuccreen** [comment]
Just tried with Discord 1.0.0 (0.0.239), still have the problem.
It worked fine on the previous version.

**Comment by iVEnoVaLue** [comment]
https://github.com/iVEnoVaLue/BetterPlugins/raw/master/app/OSX/Installer/BetterDiscord.pkg
Base script version 2.7 (compatible with 2.8)
This week i have a few days free and i might get to rewrite the base script

**Comment by LoosGuccreen** [comment]
The .pkg did work
