### ISSUE TITLE
Certain BTTV emote not working?

### ISSUE THREAD

**Issue by Swagtato** [Jiiks/BetterDiscordApp#305]
All of the twitch emotes, twitch sub emotes, BTTV emotes and FrankerFaceZ work, but with one exception. The "LUL" emote just doesn't seem to work for me or any of my friends. It is one of my most used emotes in the actual twitch chat and it's quite a shame that I'm unable to use it on Discord.

**Comment by iVEnoVaLue** [comment]
LUUL

**Comment by Swagtato** [comment]
I see, that does indeed work. I couldn't find anything on that topic through Google, so I just assumed nobody had noticed. Which is very unlikely when you think about it, considering how popular the emote is. I guess it's different because three letters is too short? Just my guess, not like I know anything about it.

**Comment by iVEnoVaLue** [comment]
Emotes names are 4 letters or more.

**Comment by mtcjayne** [comment]
See #232 for the actual solution instead of the "WONTFIX"
