### ISSUE TITLE
Error while loading with BetterDiscord

### ISSUE THREAD

**Issue by Matthaz** [Jiiks/BetterDiscordApp#308]
Hello.
For a while I had been using BetterDiscord with absolutely no problems, but a couple of weeks ago I started getting this error message when launching the program.
![discordptb_2016-05-14_08-03-37](https://cloud.githubusercontent.com/assets/19353791/15263175/de9330a2-19aa-11e6-8201-84c1f8a81f90.png)
It comes up 3 times and I have to click ok each time to actually use discord. This is really annoying me as I really liked the features BetterDiscord has, So any help would be massively appreciated!

Thanks
-Matt

**Comment by iVEnoVaLue** [comment]
Download again and use the last version of the installer

**Comment by Matthaz** [comment]
I have, I've completely reinstalled everything multiple times, no change.

**Comment by iVEnoVaLue** [comment]
when did you download that version ?

**Comment by Matthaz** [comment]
not long ago, I basically try every update to see if anything has changed

**Comment by Matthaz** [comment]
Ok I just reinstalled again, instead of that i'm now getting 
![discordptb_2016-05-14_08-17-41](https://cloud.githubusercontent.com/assets/19353791/15263328/6e931676-19ac-11e6-91a4-3bc1ea2605a7.png)

**Comment by iVEnoVaLue** [comment]
You tried too many times to access https://raw.githubusercontent.com. Also that was the first error. You can restart about 30 times / h discord
