### ISSUE TITLE
Better Discord has an error and cannot install

### ISSUE THREAD

**Issue by GameMC711** [Jiiks/BetterDiscordApp#309]
The installer says I am missing app.asar file?
---------------------------
Killing Discord
Deleting old cached files
Deleting temp path
Downloading Resource: BetterDiscord.zip
Extracting BetterDiscord
Extracting app.asar
Error: app.asar file couldn't be found in 'resources' folder. Installation cannot Continue.
Finished installing BetterDiscord with 1 errors
----------------------------------
I tried to reinstall Discord, did not do anything

**Comment by iVEnoVaLue** [comment]
make sure you select app-0.0.290

**Comment by GameMC711** [comment]
I selected the correct folder, still nothing

**Comment by iVEnoVaLue** [comment]
Do you really have discord installed ? i mean that error can be thrown only if %localappdata%/Discord/app-0.0.290/resources doesn't contain a file named app.asar
The same  goes for PTB / Canary

**Comment by GameMC711** [comment]
Ah, thank you for bringing this up. Looks like when I uninstalled it via "uninstall a program" it did not delete the files in %appdata% so I removed them manually. It works now. Thanks!
