### ISSUE TITLE
24 hour timestamps not working

### ISSUE THREAD

**Issue by GoaLitiuM** [Jiiks/BetterDiscordApp#315]
Enabling this option does not change message timestamps at all, I still keep seeing timestamps in 12h format. This option has never worked for me since it was introduced.

OS: Windows 10 64-bit
System locale and display language: English US
Region: Finland

**Comment by Jiiks** [comment]
Is this fixed?

**Comment by GoaLitiuM** [comment]
I just noticed this option does work but only if the message display mode is set to Cozy. In Compact mode, timestamps are still displayed in 12h format.

**Comment by dafzor** [comment]
Confirming the bug report, timestamps only change in Cozy, not Compact.

**Comment by S-ed** [comment]
Also timestamps showing 12h in popup notifications
![screenshot 1474209673](https://cloud.githubusercontent.com/assets/3008353/18616588/2c572f34-7dc7-11e6-8ca1-acf145c7171e.png)

p.s.: not sure if it helps, but when You switching Locale to some other language, like Russian or German, Discord also switching timestamps to 24h.

**Comment by S-ed** [comment]
```js
                if (settingsCookie["bda-gs-6"]) {
                    $(".timestamp").not("[data-24]").each(function() {
                        var t = $(this);
                        t.attr("data-24", true);
                        var text = t.html();
                        var matches = /(.*?)(\d{1,2}):(\d{2})\s(AM|PM|am|pm)(.*)/.exec(text);
                        if (matches == null )
                            return true;
                        if (matches.length < 5)
                            return true;
                        var h = parseInt(matches[2]);
                        if (matches[4].toUpperCase() == "PM"){
                            h += 12;
                        }else if (h == 12)
                            h = 0;                            
                        matches[2] = ('0' + h).slice(-2);
                        t.html(matches[1] + matches[2] + ":" + matches[3] + matches[5]);
                    });
                }
```
I've replaced text() to html(). Since it dropped lot of formatting.
