### ISSUE TITLE
minimalistic look

### ISSUE THREAD

**Issue by zordy1337** [Jiiks/BetterDiscordApp#316]
so i was trying it out and now i cant remove it, the settings button has dissapeared, how do i find the settings? i tried to install discord again and then install the better discord app but it just loads it just like it was before, no buttons and stuff

https://gyazo.com/3b9e26f9910309799b53e46a97fc8f6c this is how it looks

**Comment by Jiiks** [comment]
There's a small "R" button for restorting the normal mode. Alternatively press ctrl+, or cmd+, to open settings.
