### ISSUE TITLE
Auto-Scroll to Bottom on Channel Change

### ISSUE THREAD

**Issue by smashedr** [Jiiks/BetterDiscordApp#317]
Every time i switch between text channels/servers the text does not auto-scroll all the way to the bottom, it seems to be scrolled up just a little (maybe 1-2 lines). Even if I scroll to the bottom change channels, and come back, it has me scrolled up again. This seems to only happen in text channels with Twitch emotes.

Is this a known bug and is there a fix in place? This makes using multiple channels very very annoying.

**Comment by smashedr** [comment]
Please note, this only affects "Compact" not "Cozy".

**Comment by OfotViking** [comment]
It's because the addon-emotes is 32px high and higher than the line height.
Workaround: add something like this to your custom css:

```
.message-group.compact .emotewrapper img {
    max-height: 16px !important;
    margin: -5px 0.1em !important;
}
```

https://github.com/Jiiks/BetterDiscordApp/blob/master/js/main.js#L730

**Comment by dekaod** [comment]
@OfotViking Even when using that in the custom css, there's still around 5 lines of messages not shown every time. Wanted to bring this back up because it's been a while now and compact is unusable.
