### ISSUE TITLE
Emotes not displayed if separated by whitespace other than the space character

### ISSUE THREAD

**Issue by Klazen108** [Jiiks/BetterDiscordApp#32]
This is most obvious with newlines, but will theoretically happen with tabs or non-ascii space characters. Splitting on a regex `/\s+/g` instead of just " " should resolve the issue.

**Comment by Jiiks** [comment]
True, fixed. Cheers :+1:

**Comment by Klazen108** [comment]
Just tested, works great! Thanks for the quick turnaround
