### ISSUE TITLE
Plugin stopped working / Firefox Version 46.0.1

### ISSUE THREAD

**Issue by freak7500** [Jiiks/BetterDiscordApp#320]
Hey, 

The BetterDiscord Plugin doesn't work anymore on Firefox  46.0.1 for me, any solutions?

**Comment by freak7500** [comment]
fix it BabyRage

**Comment by DaFri-Nochiterov** [comment]
Don't use Web version

**Comment by Jiiks** [comment]
Browser plugins are currently out of date. Will be fixed eventually.
