### ISSUE TITLE
BetterDiscord Option Not Showing

### ISSUE THREAD

**Issue by MKiper** [Jiiks/BetterDiscordApp#322]
Hey!

I installed everything, and when i go to User Settings, the Better Discord Option is not showing.

Any ideas?

http://i.imgur.com/sqjxBSn.png

**Comment by Wolf68k** [comment]
Did you update Discord but not BetterDiscord?

**Comment by mkody** [comment]
Just updated Discord today on my OS X machine and reinstalled BD too ([with this fix](https://github.com/Jiiks/BetterDiscordApp/issues/325#issuecomment-224263719)) and I don't get the option in the settings too.
