### ISSUE TITLE
Mac OSX Installer Broken

### ISSUE THREAD

**Issue by Mirageofmage** [Jiiks/BetterDiscordApp#323]
Running the BetterDiscord Installer leaves me with this error on initialization.

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/Username/index.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Moving the index.js to the indicated location gives me this error.

```
/Users/Username/index.js:115
 fs.exists(process.env.HOME + _prefsPath + emotes_twitch_global, (exists) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Is there currently a workaround or a patched installer that can be used?

My setup is as follows:

MacBook Pro 2012 Non-Retina
El Capitan 10.11.5 (SIP Disabled)
node.js v6.2.0
BD v0.2.8

```
npm version
{ npm: '3.8.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.47',
  zlib: '1.2.8' }
```

Please don't mark this as a duplicate as the other "Doesn't work on mac" posts don't address the actual issue.

**Comment by SouthApple** [comment]
Similar Error for me, but I figured out how to get it "installed". Moving EVERYTHING except the install.sh file to the location it looks for it in (/Users/(username)) and then running the install.sh yields this from Terminal: 

> BetterDiscord Simple Installer v0.3 for Discord 0.0.284 by Jiiks.
If Discord has updated then download the latest installer.
The following directories will be deleted if they exists: discorpath/app, discordpath/node_modules/BetterDiscord, is this ok? Y/Ny
Looking for discord resources at: /Applications/Discord.app/Contents/Resources
Discord resources found at: /Applications/Discord.app/Contents/Resources
Looking for app folder
Looking for app archive
App archive found at: /Applications/Discord.app/Contents/Resources/app.asar
Extracting app archive
Copying BetterDiscord
Extracted to: /Applications/Discord.app/Contents/Resources/app
Injecting index.js
Injected index.js
Deleting old cache files
Looks like we're done here

However, the Application never closes like it does for Windows. Closing the program fully and reopening it with BetterDiscord added yields this:

![image](https://cloud.githubusercontent.com/assets/11883419/15958855/8dba6d9e-2ebd-11e6-99e0-5872bef51aff.png)

Pressing OK closes the window and leaves the launcher in an infinite loop of Checking for Updates.

Setup Details:

MacBook Pro (Retina, 15", Mid 2014)
El Capitan v10.11.5
Node.js 4.4.5
BD 0.2.8
