### ISSUE TITLE
webContents is null after Discord Update (3rd June)

### ISSUE THREAD

**Issue by kurisubrooks** [Jiiks/BetterDiscordApp#325]
![image](https://cloud.githubusercontent.com/assets/6291467/15797450/22689904-2a5c-11e6-879b-d40765beff02.png)

**Comment by adongy** [comment]
The injector is broken, use the one that is used for linux and it should work well.

**Comment by vkopanja** [comment]
I have the same issue (OS X as well). I have no idea how to change the injector or which one is used for linux.

Can you provide any more info?

**Comment by ifonefox** [comment]
I am also having this problem. 
@adongy The betterdiscord website says nothing about linux, the github has no releases for linux, and I can't find anything in the index.js that talks about linux.

**Comment by adongy** [comment]
Hmm sorry seems like i was talking about a fork

In the index.js of the installer,

replace
```
data.splice(_importSplice, 0, 'var _betterDiscord = require(\'betterdiscord\');\n');
data.splice(_functionCallSplice, 0, splice);
```

with

```
data = data.join("\n");
data = data.replace('var _ModuleUpdater2 = _interopRequireDefault(_ModuleUpdater);\n','var _ModuleUpdater2 = _interopRequireDefault(_ModuleUpdater);\n\nvar _betterDiscord = require(\'BetterDiscord\');\n');
data = data.replace('mainWindow.setMenuBarVisibility(false);','mainWindow.setMenuBarVisibility(false);\n' + splice + '\n');
data = data.split("\n");
```

rerun the installer and it should work.

**Comment by zyxep** [comment]
@adongy 
It require a _betterDiscord2 variable.
I used your code and added the var _betterDiscord2 to it and ti worked.

```
data = data.join("\n");
data = data.replace('var _ModuleUpdater2 = _interopRequireDefault(_ModuleUpdater);\n','var _ModuleUpdater2 = _interopRequireDefault(_ModuleUpdater);\n\nvar _betterDiscord = require(\'BetterDiscord\');\n var _betterDiscord2;');
data = data.replace('mainWindow.setMenuBarVisibility(false);','mainWindow.setMenuBarVisibility(false);\n' + splice + '\n');
data = data.split("\n");
```

Line 102 & 103 in index.js of the 0.2.8 OS X installer.

**Comment by kurisubrooks** [comment]
Proposed a Pull Request (#336)
