### ISSUE TITLE
Problems with installation guide

### ISSUE THREAD

**Issue by DragonQuiz** [Jiiks/BetterDiscordApp#33]
Found this by a server admin on discord and when I was looking at the Auto Installation guide I was confused on how this gets onto discord. If the owner or someone who had installed it can simplify the installation guide that would be better take, thanks.

**Comment by Jiiks** [comment]
Download the latest release zip: https://github.com/Jiiks/BetterDiscordApp/releases
Download the latest node binaries: https://nodejs.org/en/download/

Extract the release, place node.exe in the extracted folder:

![image](http://puu.sh/lkdkE.png)

and run the install.bat

**Comment by DragonQuiz** [comment]
thanks but it doesn't work whenever I try it the console goes away and when I try it in admin mode it just goes to the node site and redownloads a new one

**Comment by Jiiks** [comment]
Try opening command line in the folder and type "node.exe injdex.js"

**Comment by DragonQuiz** [comment]
yeah after a few tries this came up https://gyazo.com/a3b69094e550b9a1466b81b10276ede0

**Comment by Jiiks** [comment]
Well you need to navigate to the same folder where the index.js is.

**Comment by DragonQuiz** [comment]
It's in the exact same folder, nothing was moved at all I even deleted the
old and did a fresh one still happens

**Comment by Jiiks** [comment]
No, you're running cmd in system32. Did you download it to system32?

**Comment by DragonQuiz** [comment]
downloaded it to the default location (downloads folder)
is the location important to a successful install?

**Comment by Jiiks** [comment]
Running cmd in the same folder is unless you use absolute paths.
"path to node.exe" "path to index.js"

**Comment by DragonQuiz** [comment]
Looks like there's a problem if you do a space when you press yes, but if you don't do a space it works 
![image](https://cloud.githubusercontent.com/assets/8675162/11315523/3af0920a-8fc1-11e5-88e0-1b8caed8cd69.png)

**Comment by Jiiks** [comment]
Yeah it only accepts Y/N Yes/No good to see you got it working ^^
