### ISSUE TITLE
dblClickEdit.plugin.js not working anymore

### ISSUE THREAD

**Issue by SilBoydens** [Jiiks/BetterDiscordApp#331]
i loved how i could just dubbelclick on something to edit it, but that is not working anymore.
is it just for me or do others have this problem to?

**Comment by redmaw** [comment]
Still working for me.

**Comment by SilBoydens** [comment]
in the last couple days i tryed it on fresh installed discord(with betterdiscord and that enabled of cours), on canary and on PTB
none work for me, what could be the problem?
