### ISSUE TITLE
BetterDiscord ruins Discord?

### ISSUE THREAD

**Issue by master98ofu** [Jiiks/BetterDiscordApp#333]
Yeah, I was talking as usual using betterdiscord then my power went out. It was a breaker switch. I decided to restart my computer, and when Discord decided to pop up, this is what happened upon startup: 
![image](https://cloud.githubusercontent.com/assets/19939865/16062548/661d0522-3259-11e6-9ff3-9348386c95de.png)
Why?

**Comment by NotSoSuper** [comment]
you ruin github

**Comment by master98ofu** [comment]
Real helpful.

**Comment by kurisubrooks** [comment]
Unfortunately the error is too small to read. 
To me it looks like the binary file was corrupt. Please uninstall Discord, then reinstall it, then reinstall BetterDiscord to fix.
