### ISSUE TITLE
No emotes options? :)

### ISSUE THREAD

**Issue by eyalsk** [Jiiks/BetterDiscordApp#34]
Is there a way to disable emotes completely and show plain text instead?

Thanks for this *extension*. :)

**Comment by Jiiks** [comment]
Not at the moment but if you really want to then you can modify the cached files in %localappdata%\Discord\BetterDiscordData.

Replace the contents of emotes_twitch_global.json with:
{"emotes": {}}

and the contents of emotes_twitch_sub.json with:
{}

I'll add an option to disable them in the next version.

**Comment by Jiiks** [comment]
This has now been added :)

**Comment by eyalsk** [comment]
Nice! thanks. :)
