### ISSUE TITLE
No background for themes [MAC OSX]

### ISSUE THREAD

**Issue by Nosejob** [Jiiks/BetterDiscordApp#340]
Hi,
When I turn on a theme, I get the new design on my discord app, but the background image doesn't show (it stays on dark mode).

**Comment by WiggigyCookies** [comment]
Hey how did you get BetterDiscord on your mac. If you can reply then that will be awesome. :)

**Comment by Nosejob** [comment]
I got it with the 2.7 BetterDiscord package. Here's the link: https://github.com/iVEnoVaLue/BetterPlugins/raw/master/app/OSX/Installer/BetterDiscord.pkg
I couldn't install it with the "official" zip.
