### ISSUE TITLE
[OS X] Installer doesn't work

### ISSUE THREAD

**Issue by mkody** [Jiiks/BetterDiscordApp#341]
Since last update, running the installer from latest release, the HEAD or using #336 <sup>(Fix OS X Installer, Fix Typo)</sup> doesn't work.

```
❯ ./install.sh
(node:3249) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
BetterDiscord Simple Installer v0.3 for Discord 0.0.284 by Jiiks.
If Discord has updated then download the latest installer.
The following directories will be deleted if they exists: discorpath/app, discordpath/node_modules/BetterDiscord, is this ok? Y/NY
Looking for discord resources at: /Applications/Discord.app/Contents/Resources
Discord resources found at: /Applications/Discord.app/Contents/Resources
Looking for app folder
Deleting /Applications/Discord.app/Contents/Resources/app folder.
Deleted /Applications/Discord.app/Contents/Resources/app folder.
Looking for app archive
App archive found at: /Applications/Discord.app/Contents/Resources/app.asar
Extracting app archive
Copying BetterDiscord
fs.js:916
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/Applications/Discord.app/Contents/Resources/node_modules/BetterDiscord'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:916:18)
    at /Users/kody/Desktop/BD0.2.8OSX/index.js:84:16
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)
```

There's no `node_modules` folder inside `Contents/Resources/`.
![anq0x](https://cloud.githubusercontent.com/assets/843787/16635882/8f554088-43cc-11e6-91af-a251eedd5535.png)

**Comment by KGan** [comment]
This was over a month and a half ago, but for anyone who is still getting this you can checkout #369 . You'll need to move/copy around some files locally for the scripts to run like the release.

My node was so old that I had to update it to support es6 arrow functions. If you get `unrecognize token ... ` around something that reads like `(exists) => {` then that's you. I did it this way https://davidwalsh.name/upgrade-nodejs

full instructs from scratch. Start wherever you need, or just copy paste the whole thing...
```
git clone https://github.com/Jiiks/BetterDiscordApp
cd BetterDiscordApp
echo "installer needs these"
npm install asar wrench
echo "Get muh fork"
git remote add kgan https://github.com/KGan/BetterDiscordApp
git fetch --all
git checkout kgan/fix-installer-mkdir
echo "Most likely you'll start here"
cd Installers/Node
cp ../../splice .
mkdir BetterDiscord
cp -r ../../{betterdiscord.js,lib,package.json} BetterDiscord/
sh install.sh
```

**Comment by mkody** [comment]
@KGan: I'd suggest doing `git pull khan fix-installer-mkdir` instead of doing a checkout there, to merge with the current master. Also, this needs a fix with the `_index` variable, like I said in #369.
