### ISSUE TITLE
After clean setup, Discord with BetterDiscord doesn't work

### ISSUE THREAD

**Issue by Boardchip** [Jiiks/BetterDiscordApp#345]
Using the newest versions of both Discord and BetterDiscord, this error occurs.
http://puu.sh/pYxpD/e05666ee1e.png
Does anybody have a fix?

**Comment by shinji257** [comment]
Do this.

1) Install Discord
2) Launch standard Discord to verify it works and to allow Discord to get post-release updates and required modules.
3) Install BetterDiscord.

I found if you skip Step 2 then Discord fails to work properly if at all.
