### ISSUE TITLE
New update is causing Better Discord to not reinstall

### ISSUE THREAD

**Issue by NinjaKiero** [Jiiks/BetterDiscordApp#348]
So after every Discord update Better Discord uninstalls and you have to reinstall it. But with the 0.0.292 update (the most recent one) Better Discord won't reinstall, instead it gives me this message. Can someone please help? 
![better discord](https://cloud.githubusercontent.com/assets/20424691/16777041/f16aaa78-485f-11e6-8533-0b02c8e50e59.PNG)

**Comment by PavloBilyak** [comment]
@NinjaKiero 
Download new version of installer(2.81). It was fixed.

**Comment by NinjaKiero** [comment]
Wow, I didn't even realise that. Thanks dude!

**Comment by eightshimada** [comment]
Hey, is the issue only fixed for the window installer? I'm on Mac and it seems to not be fixing my issue when reinstall. So i'm not sure if there's an updated file for me to download or not

**Comment by PavloBilyak** [comment]
It probably fixed in 2.81... You need to wait when developers of BetterDiscord release updated installer for Mac.

**Comment by appleseedexm** [comment]
We need to rewrite the installation script for both systems so that the code injection into Discord is not done on old init scripts. Currently as soon as the index.js of Discord changes, the injected BD load script might not work at all. I'll see if I can find the time to rewrite it someday.
