### ISSUE TITLE
Minimal mode cuts off server member list

### ISSUE THREAD

**Issue by Juicysteak117** [Jiiks/BetterDiscordApp#354]
When using minimal mode the bottom 4 offline people(out of 17 total on this server)get cut off despite enough space.  In the image attached, on the left side is what I see with minimal mode on, at the default size of discord. On the right side is when I attempt to scroll down on this list(the scroll bar hardly moves), to where it flashes the correct number of users for a split second where I was lucky enough to get the screenshot. The blacked at names are what is there normally, the red names are the ones that briefly show. The blue at the bottom is the window on below Discord, notice the vast extra space. If I maximize Discord, the issue is solved. This is on Windows 8.1 with the July 11th Discord update, and BetterDiscord version 0.2.8.

![image](https://cloud.githubusercontent.com/assets/20595808/17054847/39122fbc-4fbe-11e6-8920-c7a7076083a7.png)

EDIT: I just realized that I think I know why this is. Whenever you aren't scrolled down on a list, it cuts off the bottom portion of the list and leaves dead space there. I don't know if this is a BD feature or vanilla, but I think it should be removed in minimal mode since minimal mode is supposed to remove dead space, not add more.

**Comment by TheOfficialJosh** [comment]
Can confirm, It only shows the players you can see in normal mode, then adds dead space to the rest.
