### ISSUE TITLE
Unstall?

### ISSUE THREAD

**Issue by Anvh87** [Jiiks/BetterDiscordApp#36]
Hello,
I installed this application to see what it adds and how it worked but for me personally there is little value added.
Is there a way to remove it since I didn't see any instructions for that?

**Comment by Jiiks** [comment]
Delete these folders:
%localappdata%\Discord\app-0.0.280\app
%localappdata%\Discord\app-0.0.280\node_modules\BetterDiscord
%localappdata%\Discord\BetterDiscordData

**Comment by Anvh87** [comment]
Thank you for the quick reply

**Comment by ehsaan555** [comment]
UPDATE: it's not %localappdata%\Discord\app-0.0.280\Resources\node_modules

**Comment by azsry** [comment]
@ehsaan555 It's currently
 %localappdata%\Discord\app-0.0.298\resources\app
%localappdata%\Discord\app-0.0.298\resources\node_modules\BetterDiscord

**Comment by bouwmeneer** [comment]
i have a problem with betterdiscord and i saw this post but it isnt for mac.
i removed al the files from discord and betterdiscord and it keeps coming back how do i remove it?

**Comment by LondynTowers** [comment]
So I figured this out quite quickly actually. 
You first need to go to Finder and go to "Go" Press Alt/Option and a new category will come up; Library. Click that. the go-to Application Support and find the BetterDiscord folder. Get rid of that. Restart Discord. That should work. Hope that helps!

**Comment by Sexy-Mercy** [comment]
***Hi how i  remove it As some of these files dont exist?***

**Comment by Sexy-Mercy** [comment]
https://i.imgur.com/CYNrTUf.png

**Comment by Sexy-Mercy** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

**Comment by Lightning486** [comment]
I followed the steps of how to uninstall betterdicord for mac as mentioned above from @LondynTowers. I found the folder and deleted everything. Afterwards, I reintalled discord. It appears betterdiscord is still in effect though. How do I fix this?
