### ISSUE TITLE
Emotes resize on hover

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Jiiks/BetterDiscordApp#360]
When you hover custom emote in emoji picker, it resizes emote (makes it bigger)

![image](https://cloud.githubusercontent.com/assets/10401817/17450211/3d3210a4-5b89-11e6-8514-56f004069b01.png)

I figured out, that problem is here:

``` diff
.bda-dark .emoji-picker .scroller .emoji-item.selected {
-    background: rgba(123,123,123,.37);
+    background-color: rgba(123,123,123,.37);
}
```

**Comment by HanFox** [comment]
@Jiiks this is still an issue.
