### ISSUE TITLE
Reload Shortcut

### ISSUE THREAD

**Issue by Ryulise** [Jiiks/BetterDiscordApp#367]
Discord has to be reloaded for BetterDiscord to reload, and you need that for things like themes and plugins to load if new additions are made. Is there a possible way to make a keyboard shortcut, or put a reload button in the settings menu?

**Comment by noodlebox** [comment]
Discord already has a shortcut, try Ctrl+R.

**Comment by Ryulise** [comment]
I know Discord does, but sometimes you don't want to have to restart it completely.
