### ISSUE TITLE
After the latest Discord update, unable to install BetterDiscord

### ISSUE THREAD

**Issue by Candy-Sama** [Jiiks/BetterDiscordApp#373]
After the latest discord update(as of this time, 8.24.2016) betterDiscord is unable to install due to this error: 
![image](https://cloud.githubusercontent.com/assets/21232117/17954233/10a41b9a-6aac-11e6-8191-d5e20028f612.png)

Yes, I have tried running it with admin privileges. 

This was the update version before I pressed install.
![image](https://cloud.githubusercontent.com/assets/21232117/17954220/f8e2a8f0-6aab-11e6-858b-113af2c2f4cd.png)

**Comment by Candy-Sama** [comment]
Some Additional info:
Yes, I've reinstalled Discord itself to see if it's anything on Discord's side, still the same error. Tho, looking at the error message, I don't think it's got to do with Discord itself, right?

**Comment by FNCxPro** [comment]
The trace looks like it is failing on killing Discord, so open the task tray, and exit Discord yourself and try installing. Also that appears like the supposed to be backslashes, are Yen symbols. IDK if that works... Yeah, try my solution, thanks.
Also: backslashes are: ```\```

**Comment by Candy-Sama** [comment]
Hm... Doesn't seem to work. I'm going to try to do a full restart since I kind of didn't restart after the uninstall of betterdiscord.

Regarding the backslashes, that's just something from the Japanese App Locale

**Comment by Candy-Sama** [comment]
Just an update, a complete fresh restart works
