### ISSUE TITLE
missing very popular BetterTTV emote

### ISSUE THREAD

**Issue by menzac** [Jiiks/BetterDiscordApp#376]
Hello, I am using Better Discord with my friends for a long time, but we are missing emote **LUL**. I was waiting for it every update and it never came, so I write this. This emote is really popular and I would like to see it in this awesome plugin.

**Comment by noodlebox** [comment]
See #301 #305 or #232

**Comment by menzac** [comment]
thanks

**Comment by mtcjayne** [comment]
I'm a bit confused here. Why is this emote ineligible for inclusion exactly?

Too much added resource usage to parse 3 letter words just for the sake of one emote? If so, it'd be better to outright state that than to just ignore the requests.
