### ISSUE TITLE
[Linux] BetterDiscord start issue

### ISSUE THREAD

**Issue by cidlover** [Jiiks/BetterDiscordApp#378]
Upon starting Discord from any means on my Antergos install, a dialog comes up with this error:
`Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at load (/home/kyle/BetterDiscord/BetterDiscordApp-stable16/lib/BetterDiscord.js:364:15)
    at Timeout.waitForDom (/home/kyle/BetterDiscord/BetterDiscordApp-stable16/lib/BetterDiscord.js:342:5)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)` 

Terminal output:
DiscordCanary 0.0.8
11: [+] Entered: WorkerThreadMain
13: [+] Entered: Initialize
14: [-] Exited: Initialize
Fetching https://discordapp.com/api/modules/linux/canary/versions.json
[BetterDiscord INF] Hooking dom-ready
[BetterDiscord INF] Checking data/cache
[BetterDiscord INF] Using repository: Jiiks and branch: master
[BetterDiscord INF] Getting latest hash
[BetterDiscord INF] Downloading Resource: api.github.com/repos/Jiiks/BetterDiscordApp/commits/master
[BetterDiscord INF] Hash: 48d4a58102dcdbc1ce888b322df2f7aa834eb695
[BetterDiscord INF] Getting updater
[BetterDiscord INF] Downloading Resource: raw.githubusercontent.com/Jiiks/BetterDiscordApp/48d4a58102dcdbc1ce888b322df2f7aa834eb695/data/updater.json
[BetterDiscord INF] Latest Version: 0.2.7
[BetterDiscord INF] Using CDN: cdn.rawgit.com
[BetterDiscord INF] Updating ext data
[BetterDiscord INF] Hooked dom-ready
[BetterDiscord INF] Loading
[BetterDiscord INF] Hooking ipc async

**Comment by sicr0** [comment]
how you solved the issue?
