### ISSUE TITLE
Cant see the settings button

### ISSUE THREAD

**Issue by OrangeRaptor** [Jiiks/BetterDiscordApp#380]
I turned on minimal mode and no voice/text channel mode,
![screenshot_6](https://cloud.githubusercontent.com/assets/21991092/18233902/bb3e615a-72a9-11e6-9e2c-58bd686a9bfe.png)
 and now i cant undo it. Plz Help

**Comment by LateNight123** [comment]
ctrl + ,

**Comment by cvaughn55** [comment]
Do you mean ctrl and the =/+ sign cause that dont work for me.

**Comment by martacbrr** [comment]
Having the same issue. Is there even a way to "uncheck" this option on the BD files?

**Comment by Smir** [comment]
its CTRL + , ( , and < ) key

**Comment by DiglidiDudeNG** [comment]
Same issue here. Wish I knew about the `ctrl + ,` shortcut beforehand, I had to search how to open the chromium dev tools to find the settings button within the DOM.

**Comment by FlutterNom** [comment]
The hotkey command for Settings is 

`Ctrl + ,`
In context it is
**Control** and **Comma**
