### ISSUE TITLE
Cant get BD on my Mac.

### ISSUE THREAD

**Issue by WiggigyCookies** [Jiiks/BetterDiscordApp#382]
Help me I cant get BD on my Mac. My mac is El Capitan 10.11.6 and my node version is v4.5.0

**Comment by draxes** [comment]
Yes, please help, it does not work, and install.sh is broken and doesn't work. Haven't heard any feedback from the devs other than a closed issue that is still an issue on the matter.

**Comment by kurisubrooks** [comment]
macOS is no longer supported. The build for macOS is grayed out.

**Comment by sn0w** [comment]
Seriously?
But why?
