### ISSUE TITLE
Hide Public Server List..

### ISSUE THREAD

**Issue by Smir** [Jiiks/BetterDiscordApp#383]
Is it possible to hide the public server list icon??

http://puu.sh/r3tWu/500847b359.png

**Comment by DaFri-Nochiterov** [comment]
![image](https://cloud.githubusercontent.com/assets/10401817/18418143/3f456cd4-786b-11e6-82ff-7e769616c77f.png)

**Comment by Smir** [comment]
erm I turned oon minimal mode and get rid of channels.. now I've lost the
options? :( and unsure how to change channels? >.<

**Comment by Smir** [comment]
thank you, must of overlooked it >.<
