### ISSUE TITLE
Moving Discord out of %LocalAppdata% will cause failure on "moving BetterDiscord to node_modules" when installing

### ISSUE THREAD

**Issue by DarkVamprism** [Jiiks/BetterDiscordApp#387]
I have installed Discord and then made it portable, now running on a USB but trying to install BetterDiscord causes the setup to stop responding during the "moving BetterDiscord to node_modules" part of the installation, if a custom path is able to be put into the installation I would think that would be the path used to transfer BetterDiscord to

**Comment by Luke-Antra** [comment]
Had the same problem here. It causes a unhandled System.IO.IOException in mscorlib.dll when trying to move the BetterDiscord Folder from the temporary download Directory to the target directory using Directory.Move as moving things across volumes is apparently not possible this way.

My best guess for a fix would be to use a method of moving that supports moving files accross volumes.
