### ISSUE TITLE
Changing font size from option panel (suggestion)

### ISSUE THREAD

**Issue by pascalbrax** [Jiiks/BetterDiscordApp#39]
Discord is terrible to use on a 4K or UHD resolution monitor (Windows), unless there's a way to increase the font size of the channels, nicknames and messages.

**Comment by Jiiks** [comment]
Will definitely add font settings when I have time to continue development :)
Can't give you any eta but hopefully not too long.

**Comment by Jiiks** [comment]
You can now use the custom css to change any font size :+1:
