### ISSUE TITLE
Can't find the settings cog while in minimal mode!

### ISSUE THREAD

**Issue by Ba1aclava** [Jiiks/BetterDiscordApp#394]
I turned the minimal mode on + some other minimal mode and now I can't find the settings button to turn the minimal mode off!
I'm not sure if it is a combination of both the minimal modes that was an issue, or if one of them is acting up.
[Here's a picture of the Discord window](http://i.imgur.com/Ja88FBD.png). I might be just blind not seeing the settings button?

**Comment by kingbuffalowing** [comment]
Do CTRL + , (CTRL plus the comma key) to get to settings. that way you can fix the minimal mode thing. :D

**Comment by Ba1aclava** [comment]
Haha thanks man! Didn't realise there was a short cut to get to the
settings  but that makes sense haha
