### ISSUE TITLE
[Request] Add option to display bigger emotes

### ISSUE THREAD

**Issue by Eruyome** [Jiiks/BetterDiscordApp#396]
Especially with server custom emotes it would be nice to be able to change their display size. Since they are very small you're very limited in your emote choice when adding some to your server.

**Comment by Hatbuster** [comment]
That's already a thing.
Use this in the custom css section.


.emoji {
    height: 32px!important;
    width: 32px!important;
    vertical-align: top;
}


adjust for different sizes

**Comment by Eruyome** [comment]
Thx, but that's not what I was looking for. This changes the default emojis size, what I want is changing the size of the custom server emotes. And it doesn't seem to work on those. If I could get the developer mode working I may be able to find the right css-class myself, but somehow it's not working for me.
