### ISSUE TITLE
Better Discord for Mac

### ISSUE THREAD

**Issue by EphemeralHope** [Jiiks/BetterDiscordApp#399]
The betterdiscord site has the MAC download grayed out. I just want an answer, yes or no, whether it works for OSX or not. If so, could I get some help? Thanks in advance!

**Comment by Outsanity** [comment]
@EphemeralHope He was supposed to be working on a Mac version installer last I remembered.

**Comment by EphemeralHope** [comment]
@Outsanity Thanks! Looking through the other posts about OSX, people are just giving too many answers I dunno which one is true. :)
