### ISSUE TITLE
2x Kill/3x Kill emotes

### ISSUE THREAD

**Issue by Phoenix100k** [Jiiks/BetterDiscordApp#4]
Hey, just a quality of life request. "double" and "triple" are pretty common words, but with BetterDiscord they are replaced by 2x Kill and 3x Kill emotes. Any way to just get rid of these ones and any other ones that would replace common text? I really enjoy the Twitch emotes otherwise.

**Comment by Jiiks** [comment]
I'll remove them tonight.

**Comment by Jiiks** [comment]
Removed from the list, simply restarting discrod will fetch the new list.
