### ISSUE TITLE
Options menu missing

### ISSUE THREAD

**Issue by SamG97** [Jiiks/BetterDiscordApp#40]
I have had Better Discord installed for a while and it's been working fine. Today, I noticed that the options 'cog' symbol on the left of the client was missing for me. I thought that Better Discord wasn't working but Twitch and BTTV emotes are still displaying properly so as far as I can see, the missing options menu is the only problem. I am currently running v0.1.5beta with the v0.0.283 index.js file on Windows 10.

**Comment by Jiiks** [comment]
Options were moved to the Discord settings modal

![ss](https://camo.githubusercontent.com/9ba965b1fb7db8afaf75c8323a53ced7a243c0d9/687474703a2f2f692e696d6775722e636f6d2f696573703955592e706e67)
