### ISSUE TITLE
Uninstall Issue

### ISSUE THREAD

**Issue by WolfGFX** [Jiiks/BetterDiscordApp#402]
Whenever i do %localappdata%\Discord\app-x.x.xxxx\app  <<< This thingy
I have no idea what those "X's" Mean. Ive deleted the Better discord file, but not these 2 things.

**Comment by Scotsguy** [comment]
It means that the version number can vary and instead of changing each update it's a placeholder.

**Comment by WolfGFX** [comment]
So then... Whats the version now?
