### ISSUE TITLE
[Suggestion] Option to automatically disconnect you from voice channel when closing the program

### ISSUE THREAD

**Issue by Riboe** [Jiiks/BetterDiscordApp#41]
Is it possible for you to add such functionality? Everyone I know hates having to disconnect manually before closing their PCs, since none of us wants to connect to a voice channel right when our PCs start up.

**Comment by Jiiks** [comment]
I will look into this

**Comment by Jiiks** [comment]
4½ months later this has been implemented :P https://github.com/Jiiks/BetterDiscordApp/commit/a478c362fa47e66cd34418a65edc5d780c8c18e6 Thanks to @pohky
