### ISSUE TITLE
Corsair VOID Wireless problem

### ISSUE THREAD

**Issue by BahamutxD** [Jiiks/BetterDiscordApp#42]
So this headset (http://www.corsair.com/en-us/void-wireless-dolby-7-1-gaming-headset) have problems with the desktop app (Windows) since version 1.11.85 from Corsair Utility Engine.

If the software Corsair Utility Engine (CUE) is installed, it will make the headset not work with Discord. Web Discord works fine thought.

The only work arounds found so far is to either uninstall CUE or trick windows to disable sound enhancement but this is no easy since it's not showing by default and you have to reinstall the headset drivers to make it show everytime.

There is an ongoing discussion at Corsair forums about the issue aswell.
http://forum.corsair.com/forums/showthread.php?t=149830

**Comment by Candunc** [comment]
I'm not sure if this is the relevant place to submit an issue, this is for BetterDiscord, a modification for Discord that allows things like Twitch emotes to be displayed inline. [Here is Discord's official support page](https://support.discordapp.com/hc/en-us), you may want to post your issue there.

**Comment by Jiiks** [comment]
Yeah there's really nothing I can do since I don't own that headset or any other headset that uses that software.

According to that thread it looks like Corsair is looking into it.
