### ISSUE TITLE
Unable to install BetterDiscord

### ISSUE THREAD

**Issue by Songodin** [Jiiks/BetterDiscordApp#47]
Windows 7, unable to install. 
Better Discord Install folder
![image](https://cloud.githubusercontent.com/assets/16124189/11543034/0ecb290e-9900-11e5-97bf-b0c578a2f0a4.png)

Error Received

![image](https://cloud.githubusercontent.com/assets/16124189/11543042/1b9d513e-9900-11e5-9a2f-c9f02a4480ba.png)

Please advise and assist.
~Songodin

**Comment by Jiiks** [comment]
Have you installed Discord to some other folder/do you somehow have an older version or newer version?

**Comment by Songodin** [comment]
My discord is 0.283, attempted a fresh install of the program. My discord is located at C:\Users\USERNAME\AppData\Local\Discord
Is this the wrong location for the program?

**Comment by Jiiks** [comment]
Check manually that the resources folder exist.
C:\Users\USERNAME\AppData\Local\Discord\app-0.0.283\resources

**Comment by Songodin** [comment]
It does indeed.
![image](https://cloud.githubusercontent.com/assets/16124189/11570840/f99ea492-99be-11e5-8576-b2244ce0001e.png)

**Comment by Jiiks** [comment]
Join the support channel @ https://discord.gg/0Tmfo5ZbOR9AK6ym so I can help your better ;)

**Comment by Songodin** [comment]
Will you still be available around 1030 pm central time? If not I will join tomorrow afternoon for assistance. Thank you.

**Comment by Songodin** [comment]
Thank you for all of the help. Turns out my PC just hates java... or any easy install for anything. I appreciate the hard work put in by Jiiks. Recommended for all future TS and Repair!
