### ISSUE TITLE
24 hour timestamps not working in Compact mode

### ISSUE THREAD

**Issue by GoaLitiuM** [Jiiks/BetterDiscordApp#471]
(original issue #315 )

This option seems to only work in Cozy message display mode, enabling it for Compact mode does not change any timestamps to 24h format.

**Comment by GoaLitiuM** [comment]
Update: I personally don't need any need for this option anymore since Discord now allows you to change the UI language which will affect how the timestamps are displayed. Changing the language to English UK will enable 24h format while keeping everything in English.

**Comment by FichteFoll** [comment]
I don't think English UK has been there a while ago when I last checked for it, but I suppose sinceit's there now I don't need it anymore either.
