### ISSUE TITLE
Settings Menu Breaks Sorta

### ISSUE THREAD

**Issue by DuIslingr** [Jiiks/BetterDiscordApp#474]
After loading up BetterDiscord DP2 the settings menu seems to break. When i select any submenus other than betterdiscords submenus they wont change to display the settings for them. If i select BetterDiscord submenus it works fine.

**Comment by Jiiks** [comment]
Unable to reproduce. Is there any errors in console?

**Comment by DuIslingr** [comment]
Well after updating issue no longer occurs. Weird. Oh well. Closed

**Comment by DuIslingr** [comment]
Reopening this because I have managed to keep reproducing the issue. Basically I open settings and keep changing the settings page other than to betterdiscord menus which still function. Eventually it freezes at one and wont change unless I close settings and reopen it. It still eventually occurs though.

**Comment by Inve1951** [comment]
is this still happening? possibly related to some plugin
