### ISSUE TITLE
can't find bdstorage.json after restart. [Linux]

### ISSUE THREAD

**Issue by shadow-absorber** [Jiiks/BetterDiscordApp#478]
if you restart discord without clearing the /var/local/BetterDiscord folder you get an error saying it can't find the file /bdstorage.json pastebin of log: [https://pastebin.com/qbRPtJjt](url)

seems it can be fixed by modefying the BetterDiscord.js and removing the slash before bdstorage.json in all instances. maybe add a check for linux and make sure to not add an extra slash there.

**Comment by Aetheryx** [comment]
You can also fix this by doing `ln -s bdstorage.json bdStorage.json`. At least, that's what did it for me.
