### ISSUE TITLE
Backgrounds No Longer Load

### ISSUE THREAD

**Issue by PaleaPablo** [Jiiks/BetterDiscordApp#480]
After a recent discord update, background images no longer load and I cant seem to locate the correct code required to make the background image appear once more.

The line of outdated code I am currently using is
.app, 
.callout-backdrop { 
    background-image: url();
    background-size: cover !important; 
    background-position: center; 

Can someone tell me how to update this? or supply an updated version?

**Comment by tehbasshunter** [comment]
Depending on the theme you're using the theme might've updated and require a new download if it doesn't autoupdate.  
  
If you're using Nova, Space Nova, or the Overwatch themes you can get those from my theme-fixes repo as they're not being updated by the author or they've been neglected.  
  
You might be missing the .layers/.layer line that should look like this:
`.layers, .layer { background: transparent!important;
}`

**Comment by PaleaPablo** [comment]
It was a custom theme I made for my discord server (mainly for me and my mates) and I rarely update it :/. However, your solution worked perfectly and fixed both of the issues I was encountering! Thankyou heaps, have a good one
