### ISSUE TITLE
BD just "disappearing"

### ISSUE THREAD

**Issue by ArrynIto** [Jiiks/BetterDiscordApp#481]
Betterdiscord just "stopped" working from one day to another. Worked just fine yesterday. Anyways tried uninstalling it & adding it up again. Didn't help. Tried installing a clean Discord again and then adding BD. Still nothing. The loading indicator on the bottom doesn't even show up and log files arent even created. 
It's not getting blocked by any Antivirus/Firewall 'nor Windows itself. 
Tried seeking help in the BD Server but it looks like they have no clue 🤷‍

**Comment by ZdrytchX** [comment]
BD doesn't work for me. Installation has 0 errors, but discord just looks plain vanilla for me.
