### ISSUE TITLE
Cannot open theme, plugins folder on Linux

### ISSUE THREAD

**Issue by RTK99** [Jiiks/BetterDiscordApp#489]
Just recently installed BetterDiscord on Arch Linux. But when I go to open the theme folder, nothing happens. I'm not sure what's causing the issue. Reinstalled BD, reinstalled Discord too. Same also happens for the plugins folder.

**Comment by tehbasshunter** [comment]
Did you install using a package from the AUR?  
  
Of the 2 that are on there at least one of them comes with some plugins that are outdated and unsupported.  
  
While this is made with Ubuntu users in mind you can still follow the instructions for arch. Just make sure you have git and npm installed https://www.youtube.com/watch?v=h1R2NTX-6C8

**Comment by tehbasshunter** [comment]
Are you trying to open the folder from the BD settings or through your file manager?  If through the settings it is only possible on Mac and Windows I believe.

**Comment by RTK99** [comment]
W as trying to open through BD settings
