### ISSUE TITLE
Recent Discord UI update messed up CSS for BD settings

### ISSUE THREAD

**Issue by Orrielel** [Jiiks/BetterDiscordApp#491]
![picture](https://puu.sh/wevqu/a1dd343a1b.png)

**Comment by Puv1s** [comment]
For any questions -> https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by Puv1s** [comment]
(my bad, meant to respond to other issue)

**Comment by Lhorzz** [comment]
I've also got this problem. The UI seems to get fixed (most of it) when you turn off the second option for Minimal Mode. Now the community discord isn't connecting anymore.

**Comment by bb010g** [comment]
https://github.com/mrmaple240/betterdiscord-mini-themes/blob/master/TempBDSettingsPublicServersFix.theme.css works as a temporary fix.

**Comment by Orrielel** [comment]
Fixed in 4fc5abe, so closing.
