### ISSUE TITLE
BD Theme/Server Tab not Syncing?

### ISSUE THREAD

**Issue by Kokurou** [Jiiks/BetterDiscordApp#493]
![screenshot 881](https://user-images.githubusercontent.com/29297963/26961586-e1c703e8-4cad-11e7-832d-478fbd7f86bf.png)

This happened after today's Windows 10 update, Discord looked perfect with every theme I have installed, until the latest Windows 10 update that I had no control on whether to install or not. Automatic updates don't give me the choice to make them optional.

**Comment by Puv1s** [comment]
Please stop opening issues about themes and plugins here, it's not what this is for. For theme and plugin problems contact their author or ask in BD support server channels. Thanks

**Comment by Kokurou** [comment]
I'm new to this, I don't know how to work this site yet. Just registered today actually to ask about how to fix this.

**Comment by Puv1s** [comment]
For any questions -> https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by Kokurou** [comment]
That one doesn't work. I've tried joining that one in the past and it's always had the ! icon and saying "1 server is temporarily unavailable due to an outage"

**Comment by Orrielel** [comment]
Not related to your OS, but an updated within Discord. They changed the classNames for the channels when they updated the UI 3 days ago. [[Reddit Thread](https://www.reddit.com/r/discordapp/comments/6fydsd/megathread_discord_text_channel_change_ui_feedback/)]
Basically means every theme has to be updated.
