### ISSUE TITLE
BetterDiscord Settings no longer appear (DiscordCanary)

### ISSUE THREAD

**Issue by slashiee** [Jiiks/BetterDiscordApp#496]
For some reason, I can no longer access the BetterDiscord settings. I know it's running because my themes and plugins loaded.
![image](https://user-images.githubusercontent.com/15317421/27008009-45a483b8-4e1b-11e7-8410-1feeca39e788.png)
And I did check, it's not a theme or plugin issue.
![image](https://user-images.githubusercontent.com/15317421/27008015-6b0dcc4a-4e1b-11e7-878a-6b97fb781e0e.png)

**Comment by SamTheGr8est** [comment]
Join the support Discord, you'll get mor ehelp there: https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by slashiee** [comment]
Is this the Discord server that's down like 99% of the time?

**Comment by SamTheGr8est** [comment]
Yep, they have a backup just for support: https://discord.gg/2HScm8j
