### ISSUE TITLE
Minimal mode breaking layout

### ISSUE THREAD

**Issue by Lopyan** [Jiiks/BetterDiscordApp#497]
After turning on Minimal Mode, it is impossible to click on the settings button.

**Comment by Garry050** [comment]
me too. How to disable Minimal Mode without settings tab?

BD server still down :(

**Comment by Lopyan** [comment]
Someone in the BD server told me to use `CTRL + ,`
It opens the setttings menu.

**Comment by eiglow** [comment]
i ended up uninstalling BetterDiscord because i didn't know about the `CTRL + ,` thing and i needed to change my settings, rip

but surely this is a pretty basic thing, just change the widths of 1 or 2 things, to, you know, not cover up integral parts of the UI
