### ISSUE TITLE
Meta should not end with "*//"

### ISSUE THREAD

**Issue by katabame** [Jiiks/BetterDiscordApp#498]
### This is little same of #289 

Hello, I'm newbie of make theme with BetterDiscord.
While writing theme using Stylus, I had a problem.

Currently, the meta line ending with `*//`
like this: 
```css
//META{"name":"exampleTheme","description":"this is example","author":"unknown","version":"1.0"}*//
```

But this formatting is not following CSS rule.
Why not
like this
```css
/*META{"name":"exampleTheme","description":"this is example","author":"unknown","version":"1.0"}*/
```
or like this?
```css
//META{"name":"exampleTheme","description":"this is example","author":"unknown","version":"1.0"}//
```

1st one (`/*META ~~*/`) is completely following CSS rule. I would recommend this. (Also, Javascript can output this as comment too.)
2nd one (`//META ~~//`) is not following CSS rule, but some alt CSS can output this.
example:
```stylus
/*
//META{"name":"exampleTheme","description":"this is example","author":"unknown","version":"1.0"}//
*/
```

### TL;DL
* Meta should not end with "*//"
* I would recommend `/*META ~~*/` format. (It's completely following CSS and JavaScript Rule!)

**Comment by Zerthox** [comment]
That's why usually the meta line ends with `}*//{}` and not just `}*//`

**Comment by katabamia** [comment]
ah, I just tried ends with `}*//{}` now, it complied to `}*//` seems great.

but I'm still can't understand why using format that not following CSS/JS comment rule.
Is there any reason of using `//META ~~ *//` ?

**Comment by Orrielel** [comment]
Probably how the meta data is parsed and fed into the UI
