### ISSUE TITLE
Custom Role Colours not working

### ISSUE THREAD

**Issue by OrangutanGaming** [Jiiks/BetterDiscordApp#499]
With [customRoleColour](https://github.com/Jiiks/BetterDiscordApp/blob/master/Plugins/customRoleColour.plugin.js), the select colour section doesn't appear for me anymore.

![image](https://user-images.githubusercontent.com/18350092/27049255-a21f871e-4fa6-11e7-94dc-aa5601d917bd.png)
(Same for tags)

**Comment by Zerthox** [comment]
Look when the plugin was last updated. It's outdated.

**Comment by tehbasshunter** [comment]
It's actually updated. Redownload it.

**Comment by OrangutanGaming** [comment]
I have the latest version from March 11th, 2016. It used to work, but the colour picker has stopped showing recently.

**Comment by OrangutanGaming** [comment]
Has been fixed
