### ISSUE TITLE
Cannot Install Better Discord

### ISSUE THREAD

**Issue by Yoshi1203** [Jiiks/BetterDiscordApp#500]
Doesn't matter how I install it, I cannot update to Better Discord whatsoever; It always crashes during set-up. However, I could easily install it to my laptop. Common fixes?

**Comment by tehbasshunter** [comment]
You grab the zip, extract all the files and run the installer as admin?

**Comment by MrTaco256** [comment]
I'm having the same issue, as soon as it starts to extract BetterDiscord in the setup BetterDiscordWI will stop working

**Comment by Romanthefrog10** [comment]
same =/
