### ISSUE TITLE
Linux does not find any themes

### ISSUE THREAD

**Issue by OfficialBAMM** [Jiiks/BetterDiscordApp#501]
Hey there,

I've been using the default version of discord for linux with BetterDiscord (latest version) and the themes does not show. I've placed the themes in: "/usr/lib/betterdiscord/Themes" 

I have the following themes in the folder:
Compozy_SwanSong_v1-31.theme.css
Beard's-Material-theme-for-Discord.theme.css

Both with read and write permissions.

Specs:
ArchLinux kernel 4.11
WM: i3

**Comment by tehbasshunter** [comment]
Try 
```
/.config/betterdiscord/themes/
```

**Comment by OfficialBAMM** [comment]
Should have looked better. Thank you.
