### ISSUE TITLE
Certain newer emotes not working in BetterDiscord.

### ISSUE THREAD

**Issue by jp1995** [Jiiks/BetterDiscordApp#502]
I guess it's because you haven't updated / synced your emote list with bttv for a while. Can I ask if and when you plan on doing that? I'd love to spam KrappaPls, but every day I am faced with the harsh, cold reality of not being able to. Please help.

**Comment by Yentis** [comment]
I'd like to know as well, it's been over 2 months since the last update to betterttv while frankerfacez is getting updated every few days.
