### ISSUE TITLE
BetterDiscord 0.2.82 fails to install

### ISSUE THREAD

**Issue by amitbeck** [Jiiks/BetterDiscordApp#508]
I get the following error:

> Error: Unable to find a valid app

This happens after extracting app.asar, with the error message of the installer being:

> Error: app.asar file couldn't be found in 'resources' folder. Installation cannot Continue.

[Problem](http://i.imgur.com/R2PK4hQ.png)

How do I fix this? I can't launch Discord now, probably until I reinstall it and delete %localappdata% files manually.

**Comment by amitbeck** [comment]
Never mind, I now realized after reinstalling Discord and **successfully** installing BetterDiscord, that the problem was caused by applying [this fix](https://www.reddit.com/r/discordapp/comments/4zvag6/we_added_right_to_left_support_to_discord/) to Discord.
Sadly enough, this fix and BetterDiscord cannot be applied at the same time on Discord client.

**Comment by DuIslingr** [comment]
A plugin could be made for betterdiscord to accomplish the same thing I think.

**Comment by amitbeck** [comment]
@DuIslingr If that's possible, that would be great.

**Comment by Inve1951** [comment]
no longer an issue and this would also resolve itself by reinstalling discord
