### ISSUE TITLE
Better Discord is stuck in a loading loop

### ISSUE THREAD

**Issue by Gabrion** [Jiiks/BetterDiscordApp#512]
Hello, i have recently been having a problem with better discord being stuck in a loading loop. I have tried Reinstalling Betterdiscord and discord itself but the problem it still there :/

http://imgur.com/a/WAnE6 

Help would be Appreciated

**Comment by Inve1951** [comment]
this can be caused by either a bad connection (up to 20mins is _normal_) or a plugin throwing during startup
hit ctrl+shift+i to bring up the console which should have additional error information
