### ISSUE TITLE
Better Discord changelog in the background?

### ISSUE THREAD

**Issue by ZenHeadshot** [Jiiks/BetterDiscordApp#514]
![screenshot_12](https://user-images.githubusercontent.com/29655642/27478794-2b8590a8-57df-11e7-98dc-8bc5e77ce774.png)

I'm not sure how to describe this issue besides showing this screenshot. using the latest version of Discord and Better Discord. I cannot select the text behind the text channels nor can i select/click on the text channel where the changelog seems to be, and if i go into settings it seems to disappear until i change the theme at which point it is always there even in the settings.

**Comment by laxplayerj93** [comment]
I've had the same issue just starting today.

**Comment by ZenHeadshot** [comment]
Issue was resolved by restarting my PC

**Comment by ente3000** [comment]
You don't have to restart your PC, just close Discord (completely). Right-click on the tray icon and select "Quit Discord" or kill `discord.exe`.
