### ISSUE TITLE
Chat doesn't scroll down properly

### ISSUE THREAD

**Issue by SfSuicune** [Jiiks/BetterDiscordApp#515]
Whenever I click into a channel chat, the scrollbar isn't scrolled down properly, so the last 1-3 messages aren't visible. That's really annoying.
Edirt: Saw that it is caused by the FFZ/TWITCH/BTTV emotes

**Comment by Jfamig** [comment]
Yep. after hours of debugging I finally figured out it was this plugin. It doesn't even work anymore. 

Having this exact problem, uninstalling this useless plugin now.

Please fix
