### ISSUE TITLE
Emote modifiers not working?

### ISSUE THREAD

**Issue by v16s** [Jiiks/BetterDiscordApp#516]
In the past 1 week all the emote modifiers like :spin and :pulse just stopped working and giving the vanilla emotes. Also the discord server seems to be down?

**Comment by tehbasshunter** [comment]
The emote modifiers broke with the last BD update.  
  
The server isn't down but unavailable when it hits the usercap. Unfortunately that's become a little longer than usual do to more and more people joining.  
  
And no discord won't raise the cap.

**Comment by v16s** [comment]
oh. i guess ill just be closing this issue then. Hopefully you guys can get it fixed with the next update. Keep up the good work!
