### ISSUE TITLE
Tick boxes

### ISSUE THREAD

**Issue by OrangutanGaming** [Jiiks/BetterDiscordApp#517]
The tick boxes seem to have changed since the last BetterDiscord update, which also changes the offsets causing themes to not work. 
![image](https://user-images.githubusercontent.com/18350092/27519350-8e9aa55a-59e9-11e7-9320-294377a70ba5.png)

![image](https://user-images.githubusercontent.com/18350092/27519352-acaf7fa2-59e9-11e7-8b9d-c213e692068e.png)
(Worked fine before update, CV 5.2.4 used in image)

I believe this was caused from BetterDiscord changing how the tick boxes were working, however, I wouldn't be surprised if that's completely wrong and it's Discord, but these tick boxes aren't in standard Discord.

**Comment by Inve1951** [comment]
discord changed the css class names and BD/ClearVision didn't follow up yet
here's a temporary fix <https://github.com/rauenzi/BetterDiscordAddons/tree/master/Themes/SwitchFix>
