### ISSUE TITLE
24 hour timestamps don't work for join messages

### ISSUE THREAD

**Issue by Lazersmoke** [Jiiks/BetterDiscordApp#519]
The 24 hour timestamp option doesn't apply to "X has joined the server" messages

![betterdiscordbug](https://user-images.githubusercontent.com/2996388/27621233-04c86986-5b95-11e7-999d-5227db295b26.PNG)

The normal messages are shown with the proper 24 hour timestamp, but the "Zach just joined. Everyone, look busy!" message shows up as "Today at 11:29 PM", which is not 24 hour time.

Version is: v0.2.81:1.792byJiiks

**Comment by dinosw** [comment]
I still see all chat messages in 12h am/pm mode.
And I have enabled the 24h option :)

**Comment by Daniihh** [comment]
This bug also goes for "somebody started a call" messages.

![24](https://user-images.githubusercontent.com/39541871/41207191-4855950a-6cdf-11e8-80f1-50015890031d.PNG)
