### ISSUE TITLE
No themes work for my better discord

### ISSUE THREAD

**Issue by callmetroller** [Jiiks/BetterDiscordApp#523]
ive tried everything, and the themes just dont work, the fonts and everything change but when i got the settings its a moshup of the theme and normal discord or just normal discord settings, the background image does not load whatsoever...
Nova theme:
![image](https://user-images.githubusercontent.com/29825496/27766034-96929314-5e88-11e7-8f4c-088cf4c6e6e0.png)
![image](https://user-images.githubusercontent.com/29825496/27766037-b2206dea-5e88-11e7-8b41-a0cadcb70928.png)
Battlefield 3 theme:
![image](https://user-images.githubusercontent.com/29825496/27766039-be6f1380-5e88-11e7-83b4-ac4eea085a94.png)
![image](https://user-images.githubusercontent.com/29825496/27766042-cd0efce8-5e88-11e7-85cc-4bd864899b39.png)

**Comment by tehbasshunter** [comment]
1. The dev of Nova hasn't been keeping up with the changes so I was kind enough to try too maintain it. You want [__THIS COPY__ ](https://github.com/tehbasshunter/theme-fixes/blob/master/Nova.theme.css).  
  
The other one you'll have to bug the creator to update since it's not one or ours.

**Comment by JMIAY** [comment]
thats not only u its also me https://gyazo.com/69146146d722e972363194c9a7751924

**Comment by TacticalGiraffe** [comment]
@tehbasshunter That copy works for me but the Member list on the right side seems to be broken (stays black instead of being transparent) would you mind updating it? I can understand if it is too much of a hassle. 
Thankyou!


![image](https://user-images.githubusercontent.com/38790983/39371035-7c8c6338-4a0e-11e8-9c2a-982d3c51d64a.png)

**Comment by tehbasshunter** [comment]
@TacticalGiraffe Already updated it as of almost a week ago. Redownload.
