### ISSUE TITLE
Don`t show in settings tab

### ISSUE THREAD

**Issue by TheMaxFlame** [Jiiks/BetterDiscordApp#524]
10 minutes ago worked fine now is not working in console i have no errors but I have this 2 warrings :http://prntscr.com/fr555s

**Comment by Coachqandtybo2** [comment]
Yeah, I'm having the same problem, except mine say: 
Failed to parse SourceMap: https://discordapp.com/channels/codemirror.min.js.map
Failed to parse SourceMap: https://discordapp.com/channels/css.min.js.map
Failed to parse SourceMap: https://discordapp.com/channels/simplescrollbars.min.js.map

**Comment by L3thal1ty** [comment]
I also am having an issue with it not showing up anymore. I had it installed, but had what I believe to be an issue with the theme I had chosen, but didn't know it at the time. I uninstalled discord and removed the better discord folders, and reinstalled, and now I can't get anything to show up in settings anymore.

**Comment by froggz19** [comment]
same problem here, on both versions, 0.0.297 and canary 0.0.161

**Comment by Labreezy** [comment]
Also showing up on my end, 0.0.297.  Same errors as @Coachqandtybo2 and everything.
