### ISSUE TITLE
BD still downloads emotes, even though they're disabled in settings

### ISSUE THREAD

**Issue by VianTORISU** [Jiiks/BetterDiscordApp#541]
I mainly use BD for custom CSS and plugins, and should I notice that some plugin causes BD to glitch, I have to CTRL+R to... wait 4-5 minutes for emotes to be downloaded.

Already tried "Read-only" attribute for emotes_*.json files @ `X:\Users\%Username%\AppData\Roaming\BetterDiscord` - nope.

P.S. https://github.com/Jiiks/BetterDiscordApp/issues/395

**Comment by Inve1951** [comment]
this _feature_ is planned for BD2
note that once the emote cache was written BD won't redownload it unless there was an update to it

**Comment by VianTORISU** [comment]
Then how often do these emotes update?
I think that BD couldn't check if there's an update or not, so it redownloads the same version of these emotes.

**Comment by Inve1951** [comment]
it uses the github api to only compare a checksum in order to determine whether it has to redownload
