### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by Inve1951** [Jiiks/BetterDiscordApp#542]
there should be some sort of roadmap towards BDv2.
i suggest adding a github project page displaying what's completed and what has yet to be written.

i'd surely contribute but without knowing what needs to be done that's not so easy.

**Comment by Lombra** [comment]
What state is v2 in roughly? Barely usable? Mostly working? Many features missing? Any point in starting developing plugins for it?

**Comment by ibrokemypie** [comment]
is it dead?

**Comment by Inve1951** [comment]
yes and no
BDv2 is undergoing a rewrite in typescript, however @Jiiks is more than less missing in action and the new files weren't published yet
