### ISSUE TITLE
In User Modal, Clicking "+" to add New Role closes entire modal

### ISSUE THREAD

**Issue by alexdiliberto** [Jiiks/BetterDiscordApp#545]
This only seems to happen when I select a user from the left pane (EX: User "JonSnow" is inside a Voice Channel A, and I click "JonSnow" avatar, then click "+". The entire modal closes)

**Comment by Inve1951** [comment]
can reproduse
like OP said only from voice channel

**Comment by alexdiliberto** [comment]
Thanks for the quick follow up @Inve1951 

But hmmm, I can't reproduce when i remove BD. I'll close this issue for now
