### ISSUE TITLE
My Mac won't let me install BetterDiscord

### ISSUE THREAD

**Issue by Herofied1180** [Jiiks/BetterDiscordApp#546]
Whenever I try to install it, BetterDiscord says everything is fine, but my mac says it has been tampered with or damaged and is recommended to be deleted. Please someone tell me what is going on.

**Comment by Herofied1180** [comment]
This is what it looks like 
<img width="421" alt="screen shot 2017-08-06 at 1 42 46 pm" src="https://user-images.githubusercontent.com/18603248/29005640-6bbace18-7aad-11e7-886b-04d9721745b0.png">

**Comment by Inve1951** [comment]
already been to BD2#support
tehbasshunter, me and co didn't find a solution

**Comment by nathanprocks** [comment]
Either
`xattr -rc /Applications/Discord.app`
or
`spctl --add --label "Discord" /Applications/Discord.app`
got it working for me. I don't remember which.
