### ISSUE TITLE
addition: URL Expander Plugin

### ISSUE THREAD

**Issue by g33kidd** [Jiiks/BetterDiscordApp#552]
There's been an issue with links such as `https://goo.gl/Q6YrOi` (Erlang The Movie 2) being sent around on discord. The people who have clicked on the link get software installed and gives hackers remote access to their computer.

Sure, discord has a thing to say "Spoopy link", but I don't think that's enough. It would be beneficial to the entirety of the discord community to have something the reverses the URL Shortener and shows the user the exact URL and maybe add a place we can check for blacklist URLs.

Me and a friend are ready to fork and add this functionality, thoughts?

**Comment by JohnDoesCodes** [comment]
mhmm
