### ISSUE TITLE
bd linux ubuntu 17.04

### ISSUE THREAD

**Issue by Tslimshady99** [Jiiks/BetterDiscordApp#553]
Cant get bd to working after following guilde on discord server 2 or the wiki guilde

**Comment by Inve1951** [comment]
this worked for most users so far: <https://www.youtube.com/watch?v=h1R2NTX-6C8>

**Comment by Tslimshady99** [comment]
it still isnt working

**Comment by Tslimshady99** [comment]
I was able to install but now its talking for ever to download emotes
`[BetterDiscord INF] Downloading Resource: cdn.rawgit.com/Jiiks/BetterDiscordApp/1d074365695cae0024cc94e6db9000dffddce51b/data/emotedata_ffz.json
` been on this for more then tem minutes

**Comment by Tslimshady99** [comment]
it works now
