### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by mendel3** [Jiiks/BetterDiscordApp#558]
When I try to install discord on my school computer, I get an error:

(node:33743) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
BetterDiscord Simple Installer v0.3 for Discord 0.0.284 by Jiiks.
If Discord has updated then download the latest installer.
The following directories will be deleted if they exists: discorpath/app, discordpath/node_modules/BetterDiscord, is this ok? Y/Ny
Looking for discord resources at: /Users/MYNAME/Desktop/Stuff/Discord.app/Contents/Resources
Discord resources found at: /Users/MYNAME/Desktop/Stuff/Discord.app/Contents/Resources
Looking for app folder
Deleting /Users/MYNAME/Desktop/Stuff/Discord.app/Contents/Resources/app folder.
Deleted /Users/MYNAME/Desktop/Stuff/Discord.app/Contents/Resources/app folder.
Looking for app archive
App archive found at: /Users/MYNAME/Desktop/Stuff/Discord.app/Contents/Resources/app.asar
Extracting app archive
Copying BetterDiscord
fs.js:924
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/Users/MYNAME/Desktop/Stuff/Discord.app/Contents/Resources/node_modules/BetterDiscord'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at /Users/MYNAME/Downloads/BD0.2.8OSX/index.js:84:16
    at FSReqWrap.cb [as oncomplete] (fs.js:259:19)

Is it because I don't have admin access, or I changed the application path in index.js?

I am on a MacBook Air (11-inch, Early 2015) on MacOS Sierra version 10.12.6

**Comment by DevilsLynAvenged** [comment]
Probably that or my other thing I was going to say was did you make sure you have the Discord Application at all or did you make sure that it's in the Application Folder?

**Comment by mendel3** [comment]
I have Discord, but in a folder on my desktop because I can't access or change the Applications folder.

**Comment by DevilsLynAvenged** [comment]
then yeah it's probably the Admin rules

**Comment by mendel3** [comment]
would it work if I asked my administrator to run it using sudo? like sudo ./install.sh

**Comment by DevilsLynAvenged** [comment]
I mean if that's the case yes
