### ISSUE TITLE
BetterDiscord website issue with download buttons

### ISSUE THREAD

**Issue by IvanDelsinne** [Jiiks/BetterDiscordApp#559]
I tried downloading the BetterDiscord tool for OSX but when I came on the website,
I could only access the Windows download, OSX and others were being blocked, like forbidden.

Is that an actual feature to only allow download for a given system (probably matched against the User-Agent) ? Or is that a bug ? Because that complexifies the download workflow and makes the tool less accessible.

See screenshot of the download options below:

![Screenshot](https://pix.watch/GiBNM4/o53hQx.png)

**Comment by Inve1951** [comment]
the official installer is outdated, use den's version: https://github.com/denBot/BetterDiscordOSXInstaller

**Comment by IvanDelsinne** [comment]
Thanks for the informations, maybe it should be announced or at least displayed on the website.

**Comment by Inve1951** [comment]
it's announced on both BD (support) servers
