### ISSUE TITLE
JavaScript error occurred in the main process with bdcustomcss

### ISSUE THREAD

**Issue by honeywave** [Jiiks/BetterDiscordApp#561]
![image](https://user-images.githubusercontent.com/1066456/30530468-f3466e5e-9c14-11e7-818a-2eb5fc83f98e.png)

I get this error when I just installed BetterDiscord. It causes me to be unable to interact with Discord in anyway, however, the BD logo at the bottom right is flashing. Is there a way to fix this? I have pastebin'd my terminal output here: https://pastebin.com/K292v25R

I don't know if it is of any importance, but I run Linux Mint 18.2 sonya on the x86_64 Linux 4.8.0-53-generic kernel.

**Comment by theGhoodedgamer** [comment]
I had the same problem. I had to set discord so it doesn't automatically run on startup. Create a folder on the desktop with only a space as the name, and move it to '/var/local/BetterDiscord/' Then go find this '/var/local/BetterDiscord/bdStorage.json' and move it in the folder you just moved. You have to do this every time you want to run discord after closing it.

**Comment by honeywave** [comment]
Do you know if there will be a fix to this? It seems awfully tedious to do this every single time.

**Comment by theGhoodedgamer** [comment]
I have no idea, but for all I know this is how it'll be until they further development in Linux versions. Btw, does it work now?

**Comment by honeywave** [comment]
Yeah, it works now. Thanks for the help!

**Comment by Inve1951** [comment]
just delete bdstorage.json or change it to look like this:
```json
{
    "defaults": {
        "data": {}
    },
    "data": {},
    "bdcustomcss": ""
}
```

if this doesn't fix it create a symlink to the file with the name all lowercase

**Comment by honeywave** [comment]
This also works for me too. I also just made a really short script that I run on startup, literally one line.
`#!/bin/bash
rm /var/local/BetterDiscord/bdstorage.json`

**Comment by DUSKvsDAWN** [comment]
removing the bdstorage file does not work for me. I'm running out of ideas here.
