### ISSUE TITLE
Plugin enchancing the overlay window

### ISSUE THREAD

**Issue by vvv444** [Jiiks/BetterDiscordApp#562]
I would like to develop an addon to alter some functionality of the overlay window. Any idea where should I start? How can I access its elements? The DOM inspector only works for the main window.

**Comment by lavendertheghost** [comment]
Would also like to know.

**Comment by Inve1951** [comment]
it's rumoured to be impossible
apparently the overlay got it's own executable
haven't used it so i can't tell you many details

i'd approach it like this:
- find the overlay process
- capture all IO requests it makes and see if it accesses any files usefull to you (e.g. css/js/json)
- check the imports/exports with dumpbin.exe (comes with VS)
- hook it up to a debugger
- do some reclass(64) magic (get the tool from unknowncheats website)

this might come in handy: <https://docs.microsoft.com/en-us/sysinternals/downloads/procmon>
