### ISSUE TITLE
Error: A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by jujulion** [Jiiks/BetterDiscordApp#565]
(Error Image) https://imgur.com/4O6xcZT.png
(Installation Image) https://imgur.com/c1UDaK1.png
-------------------------------------------------------------
Happened upon installation of "BetterDiscord" and afterwards, Discord is rendered useless, and the cursor is changed to a select cursor, but it doesn't do anything. The program does not respond, but doesn't show the error that the program is unresponsive. Immediately happens when discord is opened.

**Comment by tehbasshunter** [comment]
The first issue is because your custom CSS is corrupt.  
  
Delete bdstorage.json in `%appdata%/betterdiscord/` and restart discord.

**Comment by DUSKvsDAWN** [comment]
@tehbasshunter tried it, didn't fix it. it did fix it previously but not for this particular one, it seems.
