### ISSUE TITLE
Error: Theme only showing up during transitions.

### ISSUE THREAD

**Issue by SupaSped** [Jiiks/BetterDiscordApp#566]
I am using the theme Nova with the Discord PTB, and the theme only appears during transitions (e.g. going into menu, leaving menu). It disappears straight after.

**Comment by xNightWulf** [comment]
Hello,

Add this theme too, it will fix it.
https://github.com/GimoTheBeast/Discord-Theme-Fixes

**Comment by SupaSped** [comment]
Hello,
Thanks for you solution! It helped a lot!
:D

**Comment by Inve1951** [comment]
the listed nova is outdated
you want this file: <https://github.com/tehbasshunter/theme-fixes/blob/master/Nova.theme.css>

**Comment by SupaSped** [comment]
Thanks for the help, but it's already fixed with NightWulf's link. I don't mind having an extra file in the folder :P
Thanks again

**Comment by Inve1951** [comment]
gimo's theme fixer takes care of elements added to discord in updates
e.g. makes newer layers on top of the background transparent
however it can't know the intended behavior of a theme

for example the autocompletion menu which was there and themed before
all theme fixer can do about it is give it a non default discord look (make it blackish) when the theme would give it a background image instead

it's ment as a means to prevent discord from looking completely off until the patched theme version is out

**Comment by SupaSped** [comment]
Ok, I guess I'll use the updated one!
Thanks for the help!
