### ISSUE TITLE
BetterDiscord not installing?

### ISSUE THREAD

**Issue by Rinwada** [Jiiks/BetterDiscordApp#572]
When I try to install BetterDiscord, the installer boots up and starts installing, but when it gets to "Extracting BetterDiscord" it freezes and it displays "BetterDiscord has stopped working" and I have to close it.
![betterdiscordbroken](https://user-images.githubusercontent.com/32498836/31150415-7864ee00-a861-11e7-80ef-b75cef13dbdf.png)

**Comment by Inve1951** [comment]
join us on the BD support server and i'm sure we'll find a solution for you
<https://discord.gg/2HScm8j>
