### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by koradei** [Jiiks/BetterDiscordApp#573]
# [First Error Message](https://cdn.discordapp.com/attachments/330686478646509568/365163700371587073/unknown.png)
# [Second Error Message](https://prnt.sc/gt8l27)

I tried installing Better Discord for the first time on my PC and this happened. I don't know what the cause is and the solutions I've seen so far on here don't work since I don't have the folders that are said by the people.

**Comment by Inve1951** [comment]
join us on the BD support server and i'm sure we'll find a solution for you
<https://discord.gg/2HScm8j>
