### ISSUE TITLE
Lib Internals error

### ISSUE THREAD

**Issue by kyleharrison19354** [Jiiks/BetterDiscordApp#574]
OK, so I have the lib internals file in the proper folder, I have reinstalled BetterDiscord in administrator mode, cleared out the files and downloaded the latest versions of the plugns, but I am getting this error message. It only started popping up today: 

![untitled](https://user-images.githubusercontent.com/32531799/31209097-c2989922-a956-11e7-8fc4-bbf478f0a5c8.png)

**Comment by rauenzi** [comment]
This is an issue with Samogot's library—not BetterDiscord itself. You will have to wait for him to update the library for a fix. The reason it broke is that discord restructured some of their internal data and the library is unable to hook onto it.
