### ISSUE TITLE
Themes and Functions not working

### ISSUE THREAD

**Issue by SmartStreams** [Jiiks/BetterDiscordApp#576]
Today I've been having some issues regarding using the BetterDiscord functions and themes on Mac, I've been trying to enable functions for a while by using Ctrl+R and nothing has been working, and themes are simply not working, since the only thing I can see is:

<img width="1406" alt="screen shot 2017-10-05 at 18 14 00" src="https://user-images.githubusercontent.com/30561707/31255043-fd00213c-a9f8-11e7-9d95-6a3d6d57ce5f.png">

**ewwww default Discordddd**  (Don't mind the links smh)

<img width="26" alt="screen shot 2017-10-05 at 18 11 11" src="https://user-images.githubusercontent.com/30561707/31254917-96039eb4-a9f8-11e7-96c8-1e8ec342b78d.png">

Yet the BetterDiscord Icon is still here, so I don't know what the issue is

**Comment by rauenzi** [comment]
You have a broken plugin, there was an update that broke many plugins and when plugins break it can prevent BD from loading. Remove all your plugins and try it.

**Comment by CreatorKami** [comment]
I have the same issue, and removing the plugins didn't help

**Comment by SmartStreams** [comment]
Well, it was fixed after I deleted some of my plugins. Thank you.
