### ISSUE TITLE
turned on compact mode now i cant access user settings

### ISSUE THREAD

**Issue by Sw00b** [Jiiks/BetterDiscordApp#578]
they disappeared. help please.

**Comment by LillieSatou** [comment]
ctrl + , in discord client to get to settings.

**Comment by forry** [comment]
Have the same problem. When you reduce the width of the whole window, the widget with the settings button shrinks and the button is clipped out so only the mute and deaffen buttons are visible/clikable.
![capture](https://user-images.githubusercontent.com/1142973/31539103-de92093a-b007-11e7-818a-a1a4e5da216f.PNG)
