### ISSUE TITLE
Error javascript

### ISSUE THREAD

**Issue by Owned67** [Jiiks/BetterDiscordApp#580]
Hello,

no modify, just reboot my computer and i get this error.

uninstalled and removed discord & betterdiscord, clean install but error persist...
http://zupimages.net/up/17/41/txd7.jpg

Install betterdiscord latest version 2.82 return no error

thanks for a fix

**Comment by Owned67** [comment]
3 reinstall for fix... Solved

**Comment by lolxgaming** [comment]
Ok!
