### ISSUE TITLE
Cant Install Better Discord - Its crashing while install

### ISSUE THREAD

**Issue by IceModz** [Jiiks/BetterDiscordApp#583]
Hi,
I have a problem: I cant install Better Discord. When I try to install it crashes after a few seconds.
Screenshot: http://prntscr.com/gz13og
-IceModz

**Comment by Inve1951** [comment]
try with ticking the first box in the installer
here's the second BD server, guessing first one is down for you <https://discord.gg/2HScm8j>

**Comment by IceModz** [comment]
I ticked the first box!

**Comment by IceModz** [comment]
Still doesnt work :/

**Comment by Naranzhia** [comment]
I suffer the same thing too :((

**Comment by Inve1951** [comment]
use this installer with the fork option enabled <https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>
