### ISSUE TITLE
Crashes When Screensharing Windows 10

### ISSUE THREAD

**Issue by TheVinAnator** [Jiiks/BetterDiscordApp#584]
Latest Windows 10 version, 64 bit, latest BetterDiscord. As soon as I enter a call with screenshare I get the crash. Although as long as I'm not in the DM page it won't crash, it's just when I go into the DM page.

**Comment by Inve1951** [comment]
try without BD, bet it crashes just as bad

**Comment by TheVinAnator** [comment]
Weird uninstalling and reinstalling discord fixed it. (also reinstalling BD)
