### ISSUE TITLE
Better discord is broken on linux

### ISSUE THREAD

**Issue by samogot** [Jiiks/BetterDiscordApp#585]
commit 9ab77a8217ef2d3ef648f4cef9f9eeaa9c571a86 have introduced a regression on case-sensitive file systems. It completely breaks linux support and should break some mac configurations
There are two things that should be reverted or fixed another way:
1. case sensitive require of `Utils.js`.
https://github.com/Jiiks/BetterDiscordApp/commit/9ab77a8217ef2d3ef648f4cef9f9eeaa9c571a86#diff-fbf97e21c94e1d2527a8e75c23381cc1R13
https://github.com/Jiiks/BetterDiscordApp/commit/9ab77a8217ef2d3ef648f4cef9f9eeaa9c571a86#diff-fbf97e21c94e1d2527a8e75c23381cc1L82
It would be better to just rename this file or rename it usage to match the case. 

2. Config directory in root-owned folder
https://github.com/Jiiks/BetterDiscordApp/commit/9ab77a8217ef2d3ef648f4cef9f9eeaa9c571a86#diff-fbf97e21c94e1d2527a8e75c23381cc1R90
This should be just reverted

**Comment by Xaekai** [comment]
Was this ever fixed or even acknowledged?

**Comment by FichteFoll** [comment]
I considered building against an older version of BD or even reverting this commit on build, but never got around to it.
After about two months I just stopped caring and removed BD from my system. I highly doubt this has been fixed since.
