### ISSUE TITLE
Emote text disappears from text box

### ISSUE THREAD

**Issue by SnoutBaron** [Jiiks/BetterDiscordApp#587]
Using BD with the discord windows app.

When selecting a BD emote from the emote window, the text is added to the text box as it should. However when clicking on the text box to continue writing, any of the emote text that was added by BD from the emote window will then disappear.

Note, it does not clear the whole text box but only BD emote text that was recently added by the emote window.

**Comment by egold555** [comment]
I can conclude that happens on v0.2.82:1.792
