### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Rubyjunk** [Jiiks/BetterDiscordApp#591]
https://i.imgur.com/WWnbZx3.png

This error can be resolved by removing the entirety of "case 1:" of "switch(extData.specialparser)" in %localappdata%\Discord\app-0.0.298\resources\node_modules\BetterDiscord\lib\BetterDiscord.js

**Comment by danail23** [comment]
Omg ty so much.... you dont even know how much time i was searching for a fix. I even tried replacing the emotes and everything! Dude i love you!
