### ISSUE TITLE
Building/Compiling the app on Windows

### ISSUE THREAD

**Issue by Maradar** [Jiiks/BetterDiscordApp#592]
Hello all,

Is here somebody who can provide a step-by-step guide (for rookies like me) how to compile the app on Windows 10.

I am asking because the official release is 450 commits behind master and that is just too much.

Thanks

**Comment by wolfbeast** [comment]
Having a document outlining how to step-by-step build the application on Windows would be great!
e.g. a step saying "run `npm install` to pull in dependencies" assumes people have a CLI environment that's all set up already.

Please include:
1. Build prerequisites (and how to get the environment set up)
2. Getting the source
3. Configuring
4. Building (to create a binary executable/complete app)

**Comment by wolfbeast** [comment]
I don't see how adding a "consider this" document addresses this issue. It certainly doesn't provide anything asked for.
