### ISSUE TITLE
[dp3] minor inconveniences

### ISSUE THREAD

**Issue by Confuseh** [Jiiks/BetterDiscordApp#593]
**This issue is only related to the dp3 branch**
- Closing settings on any of the BD tabs and re-opening settings results with split between settings and BD tab that active last before closing [Not sure whether its an actual bug since it is actually quite useful for quick-reloading plugins] [visual](https://cdn.discordapp.com/attachments/119918741516451840/366896066072674314/unknown.png)
- BD settings also appear in server settings [visual](https://cdn.discordapp.com/attachments/119918741516451840/368418579667877889/unknown.png)
- Clicking appearance crashes Discord [error](https://puu.sh/y5XAf/54ff92a0bd.png) - ~~I guess rewritten path doesn't account for the relative paths.~~ its a strange behavior that I'm trying to track without success
- Styles in CSS Editor don't persist after discord reloads
- Plugins have to be switched on each time after discord reloads
- Events class' `.on` function `set`s event into the map, rather than creating an array where multiple callbacks could be added, similar situation with `.off` where it just removes whatever entry there is from the Map
_Personally, I'd prefer to do `const { Events } = window` rather than having to define my own mutation observer and then proxy that to the EventEmitter for my purposes_
- This middleware approach is great to make BD work between updates, but if update is significant enough to move folders [e.g. from `app-0.0.166` to `app-0.0.167`], then BD doesn't move over, although this is an inconvenience since all it takes is to copy-paste a folder, it'd be nice if updates like that would be considered aswell
- Although Plugin configs' author field accepts array, it only shows first item

Oh, and I should mention that this is all happening on Canary, not sure about other releases, but I could check it on PTB and Stable, if needed. Other than that, I've been trying to write emote plugin based on the existing BD plugin and using ES6 classes seems pretty neat.

_please excuse any grammatical or spelling errors i did not have enough rest lately i will be happy to elaborate on anything that i didnt explain properly or was confusing to understand_

**Comment by pendo324** [comment]
All bugs do occur in Stable and probably occur in PTB (not going to test it myself). As for the Events class, its probably working as intended, we'll have to ask Jiinks (I've been out of the loop for _literally_ years).

I'm planning on taking a look at why the active BetterDiscord settings panel opens to the side when you close and reopen settings.

On Mac, the CSS editor just stays [like this](https://user-images.githubusercontent.com/424987/32012098-d393a3fa-b984-11e7-8989-5b10d861ab62.png) until I kill the Discord process. I haven't investigated this yet.

I think it just doesn't sync plugin state to disk at the moment (or at least I haven't found it). Probably still needs to be added. I might take a stab at it after looking into the way the current version does it.

**Comment by Confuseh** [comment]
What I meant by Events class part, that the things aren't reusable.
For example: if I add callback x to the `mutation.childList`, it will put it into the Map and adds listener to the `EventEmitter`, then if I add callback y to the `mutation.childList`, it will basically rewrite entry in the Map, rather than adding it into an array of sort. So if I want to disable callback x, essentially, I cannot do it since reference is no longer there unless it was added as a function, and not as a lambda and do `Events.emitter.removeListener("mutation.childList", callback_x);`

I hope, I clarified this point a bit better..

**Comment by pendo324** [comment]
Oh ok, got it!

**Comment by Confuseh** [comment]
I tried to debug issue with `./GPUSettings` and I couldn't find the issue, seems to be something with remote/rpc server that it attempts to load it from `app` directory rather than from the asar file. 
There is an ugly workaround which is to make `GPUSettings.js` and literally have it export `GPUSettings.js` from asar. for example:
```
const path = require('path')
module.exports = require(path.join(__dirname, '..', 'app.asar', 'GPUSettings.js'));
```
