### ISSUE TITLE
Themes are broken

### ISSUE THREAD

**Issue by Seshef** [Jiiks/BetterDiscordApp#598]
My themes won't show, it's just black
![13cdd7c67888d751b937acfbad494b26](https://user-images.githubusercontent.com/33138139/32080854-d3b04388-ba66-11e7-913d-3db1682bde15.png)
![2c7e237280cb937dc02f71a590501f74](https://user-images.githubusercontent.com/33138139/32080862-d8b6a796-ba66-11e7-9773-4635d63b9fb4.png)
Is there a way to fix it?

**Comment by JoelZimmerman** [comment]
You're not alone with that issue.

**Comment by MelodyTheFolf** [comment]
So stupid and I hate it

**Comment by incorporator** [comment]
also have this issue on macOS 10.13 using the latest discordPTB

**Comment by its-Chris** [comment]
same for me and my friend

**Comment by SkyfrostN7** [comment]
For me, the themes are also broken

**Comment by ThibautSF** [comment]
I add one report, theme broken with black background (no background image), but the coloration (button, hover...) still work.

Version : v0.2.82:1.792

**Comment by Arcuss** [comment]
same issue here ;-;

**Comment by StarWolf3000** [comment]
I was able to fix some issues with the Nova theme, I posted them at thebasshunter/theme-fixes#3

**Comment by rauenzi** [comment]
This is not a BD issue though, it is an issue with the themes themselves. The best you can do is try this: https://gist.github.com/intrnl/9f623d1a89e416d2fe4f1a3aca721653

Please close this issue.
