### ISSUE TITLE
Better Discord Not Working After Computer Restart?

### ISSUE THREAD

**Issue by Sephraem** [Jiiks/BetterDiscordApp#603]
I normally do not restart my desktop often, but I did so tonight. After that, I was unable to utilize various emotes in Discord that I was able to prior to the restart. I uninstalled discord, reinstalled it, and did a fresh install of BD, but nothing worked. Did I perhaps do something wrong? Any guidance would be greatly appreciated!

**Comment by Surisnek** [comment]
Cheers, I am also having this issue. I even tried uninstalling and reinstalling Discord to see if a fresh install would work to fix this issue. I was using the latest release of BetterDiscord at the time my computer reset. (Using a Windows10 computer)

**Comment by CosignCosine** [comment]
Just as clarification, these are BD emotes you're talking about? Not Gamewisp or any external service?

**Comment by Surisnek** [comment]
I was having trouble with BD Emotes as well as Custom CSS for themes -- my theme simply stopped working completely.

**Comment by Sephraem** [comment]
@CosignCosine Yes, it was the BD emotes. I was able to get BD to work after a lot of swearing at my desktop and threatening it.
