### ISSUE TITLE
Huge RAM usage, even when having all plugins and themes disabled

### ISSUE THREAD

**Issue by SilentHammerHUN** [Jiiks/BetterDiscordApp#606]
If I leave Discord running for a while with BetterDiscord installed it starts consuming 1GB of RAM after 10 minutes of background usage. If I wait more Discord consumes even more.

**Comment by Trusty03** [comment]
I have to say the same, no matter what kind of high usage plugins I turn off, (Better)Discord just starts to eat up to 2GB of ram.  I may have to end up buying another stick (of ram) lol.
