### ISSUE TITLE
Discord Keeps Crashing

### ISSUE THREAD

**Issue by Dustyragon** [Jiiks/BetterDiscordApp#607]
I don't know exactly what is causing it, but my friends who use BetterDiscord say that it isn't crashing for them anymore after they removed it, and it seems to have only started happening after the most recent update. It'll crash out of nowhere, and I've yet to figure out what is making it happen.

**Comment by DevilsLynAvenged** [comment]
Did you download any plugins

**Comment by Dustyragon** [comment]
https://gyazo.com/750f6f0099931d10d8a12a0371cd6899 I have a few.

**Comment by Inve1951** [comment]
update horizontal serverlist if you got that one

**Comment by Dustyragon** [comment]
Don't have that one. Autogif, Better Replyer, Double click edit, Notice Me, Senpai (it's for DMs), Osu sounds.
Those are the ones I'm using.

**Comment by shinji257** [comment]
I've been having this issue lately and one of the things I just discovered (and it is rather consistent) it that Discord is erroneously using the Japanese date formatting in the discord server.  If you load to a discord server you get to see this.  When you switch servers Discord crashes and won't reload properly.  You have to exit then reload which usually corrects the date formatting error and the crash.

As of the last crash (today) I only had these plugins enabled.

BetterRoleColors 0.5.8 (Zerebos)
BlurNSFW 0.1.7 (Zerebos)
Line Numbers 1.1.6 (noodlebox)

**Comment by Inve1951** [comment]
@shinji257 update [samogot's lib](https://github.com/samogot/betterdiscord-plugins/blob/master/v1/1lib_discord_internals.plugin.js)
an outdated version caused chinese timestamps
