### ISSUE TITLE
Cannot Install BetterDiscord PTB

### ISSUE THREAD

**Issue by Brittank88** [Jiiks/BetterDiscordApp#608]
Sorry if this issue has been brought up already (although I did check to make sure there isn't already one).

When I attempt to install BetterDiscord, there are a few issues to note:

I cannot check the second or third checkboxes relating to PTB and Canary. They just remain unchecked.
When trying to install BetterDiscord to Disocrd PTB (and I'm assuming this is because I can't check the right checkbox) the installer crashes. There is no error log, only a small window notifying me of the crash and providing the option to cancel or debug.

Looking forward to a response.

**Comment by Inve1951** [comment]
is discord PTB installed?

**Comment by Brittank88** [comment]
Yes, however it is the portable fork by crazy-max: https://github.com/crazy-max/discord-ptb-portable

As far as I know this should work anyway though, crazy even has a section about installing BetterDiscord to the portable edition:

![image](https://user-images.githubusercontent.com/24266948/32717069-7684a4ca-c8ac-11e7-979b-cc3d2266da89.png)

Furthermore I must note that I can't install regular Discord PTB (in case you ask me to do that). Crazy placed a workaround in his code that allows me to actually run Discord. Without it, Discord simply won't run. We had an entire conversation on it, his workaround was the only thing that worked.

**Comment by Inve1951** [comment]
> choose the install `location discord-ptb-portable\app-x.x.x`

**Comment by Brittank88** [comment]
Doesn't stop the BetterDiscord installer from crashing.

**Comment by Inve1951** [comment]
confirm you unzipped and tick the first box, try run it as admin
if it still fails show a screenshot of the crashed installer window

**Comment by Brittank88** [comment]
![image](https://user-images.githubusercontent.com/24266948/32719463-94d96ab6-c8b4-11e7-8c18-e3e973182737.png)

![image](https://user-images.githubusercontent.com/24266948/32719469-99b5ef6e-c8b4-11e7-800f-3b986d6664b8.png)

I would screenshot what's happening in that log there on the installer window but I can't move the other window out of the way in time before the initial window disappears.

I can confirm it is unzipped, and in its own folder, run as administrator. The first box was also ticked.

**Comment by Inve1951** [comment]
the setup window is supposed to stick around until you chose an action :thinking: 
gotta know what the last thing was it attempted

either way, check the contents of the `resources` subfolder
does it have app.asar? possibly even an app folder? how about node_modules?

**Comment by Brittank88** [comment]
All 3 folders/files you have mentioned are present.

One moment and I will determine what the last thing is in the log before it crashes :)

**Comment by Brittank88** [comment]
![image](https://user-images.githubusercontent.com/24266948/32749681-27e4f302-c914-11e7-9582-d1e3e4980efb.png)

Somehow I got the photo in time!

**Comment by Inve1951** [comment]
[BD.zip](https://github.com/Jiiks/BetterDiscordApp/files/1471216/BD.zip)
^ zipped you [Zack's version](https://github.com/rauenzi/BetterDiscordApp) which can be considered a preview of the next update.

the index.js is from stable discord but it probably works despite that. drop the 2 folders from the zip into the resources folder. this is basically a manual installation.

**Comment by Brittank88** [comment]
Tried that, Discord errors on startup:
![image](https://user-images.githubusercontent.com/24266948/32798463-e64f3744-c9c8-11e7-8ea1-040e87e6b3c4.png)

**Comment by Brittank88** [comment]
Update: The app still _opens_, but there is no sign of BetterDiscord being installed:
![image](https://user-images.githubusercontent.com/24266948/32798548-24bfbd64-c9c9-11e7-8c67-951694d6326d.png)

**Comment by Brittank88** [comment]
Update 2: I stand corrected. BetterDiscord just appeared in the settings menu:
![image](https://user-images.githubusercontent.com/24266948/32798598-4afca97e-c9c9-11e7-842b-b6d0533a2e0f.png)
I am however concerned for the stability of the program though.. I don't really want to encounter an error on each startup.

**Comment by Brittank88** [comment]
Another note on stability... a restart of Discord and BetterDiscord is no longer visible:
![image](https://user-images.githubusercontent.com/24266948/32801726-fef6e900-c9d1-11e7-815d-499a32333267.png)

I get the feeling this is like the initial opening though, where it took time for whatever reason before being visible.. Not sure if that's meant to happen though.

**Comment by Brittank88** [comment]
I was right, it took some time and finally BetterDiscord was visible. Is this supposed to be taking time before becoming available?

Also sorry for so many messages, hopefully that's not too annoying for you.

**Comment by Inve1951** [comment]
the html is not supposed to get parsed. (it was that way ages ago but that was removed)
and yes, the startup takes a moment (there's a loading indicator bottom right)

**Comment by Brittank88** [comment]
Ah okay, thank you.

Strange that if it was supposed to not be parsed not a lot of plugin devs seem to know about that fact..

**Comment by Inve1951** [comment]
only place where i ever seen it is the ClearVision theme.
Non of the official plugins do that however
