### ISSUE TITLE
BetterDiscord buggued ? :/

### ISSUE THREAD

**Issue by Kuzakii** [Jiiks/BetterDiscordApp#610]
I have a problem with my BD since 3-4 weeks . The background image and so doesn't wanna show anymore when I didn't change anything and worked fine before D: . I just have that background now ^^'
![image](https://user-images.githubusercontent.com/33605727/32702318-8275d334-c7e5-11e7-8d4f-1ab73870d073.png)

**Comment by William1Gray** [comment]
That's because discord updated and the maker of your theme hasn't updated it to work with the new update

**Comment by Inve1951** [comment]
^

you can try theme fixer tho: <https://github.com/xNightWulf/ThemesForBetterDiscord/blob/master/zThemeFix.theme.css>

**Comment by Kuzakii** [comment]
Where do I put it ?

2017-11-13 9:49 GMT+01:00 Inve1951 <notifications@github.com>:

**Comment by Kuzakii** [comment]
I mean at which line of the CSS

2017-11-13 10:09 GMT+01:00 Hizuk Iga <hadrien691@gmail.com>:

**Comment by Inve1951** [comment]
install it like any other theme
