### ISSUE TITLE
BetterDiscord COMPLETELY screwed itself today

### ISSUE THREAD

**Issue by luxidoptera** [Jiiks/BetterDiscordApp#611]
So I was in a voicecall with a friend of mine and while I was sending links to my friends, Discord refreshed itself, then BetterDiscord took much longer to load than usual and when it finally decided to load, well...

![image](https://user-images.githubusercontent.com/15697751/32704226-c066c0d8-c7cf-11e7-81ee-8373ec391dbf.png)

_This_ started happening. It appears BetterDiscord is attempting to reload itself every couple seconds or so? Either way, the "public" indicator quickly filled my entire sidebar, and this process of BD repeatedly reloading itself on top of itself ate up a MASSIVE amount of RAM. Restarting Discord fixed the issue, but you might want to look into this.

**Comment by Inve1951** [comment]
disable the public button in BD core settings (the feature is broken) then reload with ctrl+R
