### ISSUE TITLE
autogif play issue

### ISSUE THREAD

**Issue by CamTro** [Jiiks/BetterDiscordApp#612]
It is working with all gifs but nitro avatars and mine has stopped animated since im trying to get it work but gave up. Is there anyway to get my avatar being animated without hovers again?

**Comment by Inve1951** [comment]
css can do it
```CSS
:-webkit-any(.avatar-small, .avatar-large)[style*="/avatars/your user id here/"] {
  background: url(link to gif here) 50%/cover !important;
}```

**Comment by CamTro** [comment]
Hmm, still dont work. :(
