### ISSUE TITLE
A JS Error; Cannot convert undefined or null to object.

### ISSUE THREAD

**Issue by DelPyth** [Jiiks/BetterDiscordApp#616]
I have been seeing this everytime Discord starts up. Nothing has changed to discord besides a fading logo at the bottom right.
The errors seem harmless to me, my best guess it something to do with a JSON file having a null variable and it's not wanting to work with it.
![image](https://user-images.githubusercontent.com/23638456/32907297-95b1be82-cacd-11e7-9d98-d51c0fa11b90.png)

**Comment by Inve1951** [comment]
found a solution?

**Comment by DelPyth** [comment]
@Inve1951, No, I just found a plugin that'd fix it.

**Comment by Inve1951** [comment]
don't tell me it's [this one](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/FixTwitchEmotes)
what plugin?

**Comment by DelPyth** [comment]
It's a tempfix plugin that I found to "fix" this.
On monitored networks it glitches, which I don't mind since I'm mostly doing work vs chatting around.
But on a normal network, it works fine. minor lag (Mostly 'cause slightly crappy computer)
I can give you the file if you'd like.

**Comment by Inve1951** [comment]
just wondering cuz the source of the error is outside of a plugin's reach
