### ISSUE TITLE
BetterDiscord Linux Errors (Lubuntu 16.04)

### ISSUE THREAD

**Issue by WilliamEpsilon** [Jiiks/BetterDiscordApp#617]
![2017-11-16-220410_1280x800_scrot](https://user-images.githubusercontent.com/13991546/32927819-d93c4114-cb1c-11e7-83f7-960211d00f73.png)

**Comment by KaidenTBIO** [comment]
Also happens in mine;
`$ touch /var/local/BetterDiscord//bdstorage.json` of course leads to an empty json file; the JS requires an attribute that, of course, it's not there
