### ISSUE TITLE
.asar files missing

### ISSUE THREAD

**Issue by SquidPlayZYT** [Jiiks/BetterDiscordApp#618]
hello, I just installed betterdiscord because I got a new computer, but its saying I have missing asar files. I have been looking at some articles but none have helped me. i found a screenshot showing a bunch of files in resources, but i have no files in resources. please help me

**Comment by SquidPlayZYT** [comment]
![image](https://user-images.githubusercontent.com/33473322/32986124-4997fe22-cc98-11e7-9593-b654b777a6a7.png)

**Comment by SquidPlayZYT** [comment]
![image](https://user-images.githubusercontent.com/33473322/32986128-66cf125a-cc98-11e7-8f9d-8b40ae9d5678.png)

**Comment by SquidPlayZYT** [comment]
@Jiiks

**Comment by DevilsLynAvenged** [comment]
[resources.zip](https://github.com/Jiiks/BetterDiscordApp/files/1485232/resources.zip)
you need this

**Comment by DevilsLynAvenged** [comment]
it has the folders that you're missing
