### ISSUE TITLE
BD not working on macos Sierra?

### ISSUE THREAD

**Issue by Sethwoolf2** [Jiiks/BetterDiscordApp#619]
BD used to work just fine for me on my iMac about a month ago until one day when it stopped working completely. I reinstalled it, but it only shows the BD logo in the corner and loads one plugin (role colours are text colours or something) and nothing else, no themes either. I can't access anything from settings, either. The emoji menu (where you enter a message) also stops working whenever I install BD. I have reinstalled Discord itself and BD countless times and it still doesn't work, does anyone know how to fix this?

**Comment by DevilsLynAvenged** [comment]
try emptying out your plugins folder and see if that fixes it and emoji menu where you enter the message?

**Comment by Sethwoolf2** [comment]
by emoji menu i meant this:
![screen shot 2017-11-21 at 00 56 19](https://user-images.githubusercontent.com/33819203/33049228-e7661aac-ce56-11e7-929c-0c5b409f74bf.png)
I've also emptied the plugins folder and themes folder and nothing has happened

**Comment by DevilsLynAvenged** [comment]
Hmmmm try reinstalling BetterDiscord then
    On Monday, November 20, 2017, 7:58:48 PM EST, Sethwoolf2 <notifications@github.com> wrote:  
 
 
by emoji menu i meant this:

I've also emptied the plugins folder and themes folder and nothing has happened

**Comment by Sethwoolf2** [comment]
i've reinstalled it quite a few times and it still doesn't work

**Comment by Sethwoolf2** [comment]
I reinstalled discord and betterdiscord a few times and now it works 😄
