### ISSUE TITLE
Editing a twitch emote into a discord emote crashes Discord

### ISSUE THREAD

**Issue by iamartn** [Jiiks/BetterDiscordApp#620]
If you send a message with a twitch emote, then edit that message and add a discord emote into it, it causes you and anyone else in that channel at the time to crash (if they have BetterDiscord installed). This is obviously a pretty big issue as you can easily crash someone elses discord just by sending and editing a message.

**Comment by Inve1951** [comment]
can reproduce on my end, even on zerebos fork

**Comment by iamartn** [comment]
Weird, we have gotten multiple people to crash this way and I tried it on multiple servers. Can you explain exactly how you are doing it?

**Comment by Inve1951** [comment]
i said i can reproduce :thinking:
send an emote as message, edit and replace it with an emoji, confirm/save/send edit

**Comment by iamartn** [comment]
oh, i am bad at reading
