### ISSUE TITLE
Additions to the emote filter

### ISSUE THREAD

**Issue by Inomares** [Jiiks/BetterDiscordApp#621]
Some fairly common words. Very jarring to have emotes pop up in their place. Suggest adding these to emotefilter.json:

- ~~"HYPE"~~
- "meditation"
- "Kisses"
- "ghillie"
- "Poked"
- "Unacceptable"
- ~~"rekt"~~
- "Hello" (seriously?)
- ~~"Kill"~~
- "Watching"
- "Doktor" (quick explanation, this is the word for "Doctor" in many european languages, not as big of a deal as the other ones)
- "Graham" (Not-so-uncommon English name/surname)
- "Friendship"

**Comment by Inve1951** [comment]
forwarded to zerebos

**Comment by Inomares** [comment]
Added another emote to first post: "meditation". Also is anyone actually maintaining the emotefilter? It's been two months.

**Comment by Inve1951** [comment]
@rauenzi did you include em? i forgot about this

**Comment by Inomares** [comment]
Added another one; "ghillie". Not as normal as the other ones, but it's just a normal word and should not be changed into an emote without any abnormal capitalization.

For anyone else finding this issue, [this plugin, EmoteBlacklistRedux](https://github.com/mashirochan/Mashiro-chan/tree/master/Plugins/EmoteBlacklistRedux) works as a local fix, though any friends with betterdiscord will still see the emotes.

**Comment by Inomares** [comment]
Another one, "Poked"

**Comment by Inomares** [comment]
Another one, "Unacceptable".

**Comment by Inve1951** [comment]
HYPE and meditation were added
these are still missing `Kisses, ghillie, Poked, Unacceptable, rekt`
here's the list btw [BBD/emotefilter.json](https://github.com/rauenzi/BetterDiscordApp/blob/master/data/emotefilter.json)
@Inomares @rauenzi

**Comment by Inomares** [comment]
This one is particularly bad:
"Hello" is apparently an emote now. This is not a BTTV emote, and I don't have FFZ emotes enabled. Where are these coming from?

**Comment by Inomares** [comment]
Thanks for the information, @Inve1951. Are these emotes the ones that can be opted into by the broadcaster, similar to OMEGALUL etc? (i.e. they are not enabled by default even in twitch). They do not show up for me in twitch ([others that are not opt-in, such as SourPls, show up just fine](https://i.imgur.com/3kezgO9.png)). If that is the case, maybe we could consider excluding these opt-in emotes entirely? Their naming scheme is clearly very lax and presumably that is the reason broadcasters have to explicitly opt into them.

**Comment by Inomares** [comment]
And another: "Watching".
