### ISSUE TITLE
JS issue

### ISSUE THREAD

**Issue by Trevert** [Jiiks/BetterDiscordApp#622]
Recently reinstalled BD after going without it for a few months. When discord starts i get this JS error and BD never loads just stuck in a loop and i get no options under my settings
![error](https://user-images.githubusercontent.com/33936783/33182158-c77eb442-d040-11e7-89fa-8f86f2ae43dc.png)

**Comment by DevilsLynAvenged** [comment]
try closing discord completely and put the emote.zip and extract it here %appdata%\BetterDiscord\ then open discord https://cdn.discordapp.com/attachments/280806472928198656/369115721218916352/emotes.zip
