### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by FrostyModz** [Jiiks/BetterDiscordApp#624]
Hey, I have been wanting to install this on macOS forever but no luck. Any update on whether or not mac is supported??

**Comment by Inve1951** [comment]
you want this <https://github.com/denBot/BetterDiscordOSXInstaller>

**Comment by FrostyModz** [comment]
Inve1951. It installs fine but discord doesn't open after. It crashes

**Comment by DevilsLynAvenged** [comment]
what error do you get?

**Comment by FrostyModz** [comment]
@DevilsLynAvenged https://i.imgur.com/SWoMej3.png

**Comment by DevilsLynAvenged** [comment]
https://www.dropbox.com/s/auxfr9q2fjizt6g/Discord.zip?dl=0 get the zip from here and extract it and try the app and see if it works

**Comment by DevilsLynAvenged** [comment]
and make sure it's in the application folder

**Comment by Inve1951** [comment]
the serverlist feature is broken, it's a known issue.
