### ISSUE TITLE
Remove/disable emotes?

### ISSUE THREAD

**Issue by PlumpSSB** [Jiiks/BetterDiscordApp#626]
Alright so I have no clue if this is FrankerFaceZ or BetterTTV, but some emotes that replace text ((such as "NOOOO" (with a red moon) and "Lolololol" (some face idfk)) really disturb me and I find no use for them, and I'd just like to have the message written as it originally was. Is there any way to choose from a list or something some emotes that you don't want to be replaced on text, and disable them?

**Comment by Inve1951** [comment]
<https://github.com/Jiiks/BetterDiscordApp/blob/master/Plugins/emoteBlacklist.plugin.js>
