### ISSUE TITLE
high CPU usage when using a theme

### ISSUE THREAD

**Issue by d0tmoe** [Jiiks/BetterDiscordApp#627]
heya, i tried to use betterdiscord a couple of times, but every time i use a theme, discord use 20~% CPU, i don't think it's normal, i tried with another theme but same problem, any idea?
If discord is reduced, it only takes 0-2% CPU, but when i leave it "open", it takes a lot of my CPU.

specs (if it can help):

CPU: i5 4670k @4GHz
16 gb ram
Windows 10 64 bits 
Discord (32 bits)

Screenshot when discord is reduced: https://i.imgur.com/ZIZRRM6.png (both discord process use 0%)
When i leave it open and dont reduce: https://i.imgur.com/pAgHKZX.png

**Comment by Inve1951** [comment]
still sounds like a theme issue
what themes did you try?

**Comment by d0tmoe** [comment]
Tried twitch theme and all clearvision themes but i don't think it's because of the theme, because my friend (who gave me twitch theme) dont have this issue

**Comment by Inve1951** [comment]
try something simple like [this](https://github.com/redsauce117/SauceysDiscordThemes) for example

**Comment by d0tmoe** [comment]
thanks for help, but i tried this theme and same issue :/
https://i.imgur.com/JiQWOEg.png

**Comment by Inve1951** [comment]
that's really odd. i can't explain it. i'm getting ~0.5% usage with a full theme.
i searched around the net a bit but didn't find any promising solutions. my best bet at this point is update your drivers.

**Comment by d0tmoe** [comment]
Just a quick update to say it still use 20 or 25% cpu for no reason, it's been one year im trying to use better discord but i still have this problem
(and nope, update drivers dont works)

**Comment by Inve1951** [comment]
to identify the root of your issue you could check a [js cpu profile](https://developers.google.com/web/tools/chrome-devtools/rendering-tools) (devtools are bound to ctrl+shift+i in discord) or have a look with [other debug tools](https://docs.microsoft.com/en-us/sysinternals/downloads/) but this is where it gets very technical.

one more classic thing you could try is running discord/BD with your AV disabled.

good luck.

**Comment by d0tmoe** [comment]
I already tried to run BD with my AV disabled but same problem, i'll take a look for js cpu profile, thanks
