### ISSUE TITLE
Issuing Running The Installer

### ISSUE THREAD

**Issue by Feminyxx** [Jiiks/BetterDiscordApp#63]
I don't know if I have everything to successfully install, but I got the latest Downloader and ran it on nodejs but when I type Y to accept, it does nothing, and if it does pend, it crashes. Help?

**Comment by Jiiks** [comment]
Post a screenshot of the error, if you are on windows then try the new windows installer: https://github.com/Jiiks/BetterDiscordApp/releases/tag/WindowsInstaller

**Comment by Feminyxx** [comment]
http://prntscr.com/9b147q and http://prntscr.com/9b15kj

**Comment by Jiiks** [comment]
Just updated the installer, it was missing a dependency that asardotnet uses. 
Try downloading it again :)

**Comment by Feminyxx** [comment]
It's still not working... http://prntscr.com/9b1kxg
Is there anything I'm missing? I tried both launchers

**Comment by Jiiks** [comment]
You should have all these files:
![ss](http://puu.sh/lLBRF.png)

**Comment by Feminyxx** [comment]
Yeah
I just open the app in the center right? 'Cause that's what I've been doing

**Comment by Jiiks** [comment]
Yes, do you have at least .net 4.0 installed?  https://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by Feminyxx** [comment]
It says I already have 4.5 installed

**Comment by Jiiks** [comment]
At what point does it crash now with the Newtonsoft.Json.dll library?

**Comment by Feminyxx** [comment]
The same point - When it's extracting the app

**Comment by Jiiks** [comment]
Do you have all the files in: %localappdata%\Discord\app-0.0.283\resources\

You should have the following files:
app.asar
atom.asar
dictionaries directory
node_modules directory
sounds directory

**Comment by Feminyxx** [comment]
Yeah I believe so. Hard to tell 'cause it's all spread out

**Comment by Jiiks** [comment]
Should be right next to each other
![ss](http://puu.sh/lLDlD.png)

**Comment by Feminyxx** [comment]
http://prntscr.com/9b1yuk oh I see, like this?

**Comment by Jiiks** [comment]
Is 0.0.280 the latest version you have? You should update Discord first if it is.

**Comment by Feminyxx** [comment]
Whenever it tried to update it fails

**Comment by Jiiks** [comment]
I'd recommend completely reinstalling Discord.

Delete the Discord folder in %localappdata% and in %appdata%

Then download the latest version from their website.

**Comment by Feminyxx** [comment]
Okay, how can you see the current version?

**Comment by Feminyxx** [comment]
And having Windows 10 doesn't effect it by any chance, does it?

**Comment by Jiiks** [comment]
No, your version is the same as the folder. Latest would be app-0.0.283

**Comment by Feminyxx** [comment]
Yep I got it

**Comment by Feminyxx** [comment]
Yo, it worked this time

**Comment by Feminyxx** [comment]
btw, do sub emotes work?

**Comment by Jiiks** [comment]
Yes, all Twitch emotes work.
All default bttv emotes listed here: https://nightdev.com/betterttv/faces.php
All FrankerFaceZ emotes lited here: http://jiiks.net/projects/betterdiscord/ffz/

Good to hear you got it working :)

**Comment by Feminyxx** [comment]
Thanks so much, and I'll see ya on the channel :D Take care bud

**Comment by Jiiks** [comment]
No problem :)
