### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by nuclearintel** [Jiiks/BetterDiscordApp#630]
And it's a long one too.
![thisbasically](https://user-images.githubusercontent.com/29177818/33804871-a59c93a2-ddb6-11e7-8c1e-4835a9f58ab2.png)

**Comment by Inve1951** [comment]
for future refference, unpack [emotes.zip](https://github.com/Jiiks/BetterDiscordApp/files/1545733/emotes.zip) into your BD folder
`%appdata%\BetterDiscord` on windows
