### ISSUE TITLE
I can't send Twitch emotes

### ISSUE THREAD

**Issue by Heeelix** [Jiiks/BetterDiscordApp#631]
I can't or I don't know how to

**Comment by DevilsLynAvenged** [comment]
did you turn on Twitch Emotes in the Emote Setting?

**Comment by Inve1951** [comment]
you'll need [this](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/FixTwitchEmotes) until jiiks finally accepts the PR with all the fixes
