### ISSUE TITLE
BetterDiscord Doesn't work after last update (11 december)

### ISSUE THREAD

**Issue by BateauSD** [Jiiks/BetterDiscordApp#632]
Howdy all, after last Discord update "BetterDiscord features" stopped displayed (Personal themes etc). Reinstall did not help.

**Comment by DevilsLynAvenged** [comment]
did it give you any errors?

**Comment by tegenton** [comment]
I just reinstalled after the new update and it still works for me, unless you're using Canary.

**Comment by BateauSD** [comment]
No errors, runs as normal Discord, without plugins

**Comment by Kynaren** [comment]
This happened to me too. I reinstalled Better Discord, said 1 error, and does not work.

**Comment by AndreiJuxtapus** [comment]
This happened to me too. How can i fix this?

**Comment by SirAzazel** [comment]
Just reinstalled BD on new update, made sure to not have any non-latin letters in path to installer, workd fine for me.

**Comment by KKKompot** [comment]
Hey, just made an account to say that reinstalling BD (No non-latin letters in the path) did not fix better discord, it almost looks like discord is completely ignoring anything the installer does or that the installer is not even doing anything, any way for me to check what's wrong ?

**Comment by KKKompot** [comment]
Sorry for misinforming people, 10 minutes after the installation BD just magically started to work...

**Comment by BateauSD** [comment]
Problem solved, thx

**Comment by doctortee** [comment]
It seems to be a problem with twitch emotes

`
[INF][13/11/2017 19:32:46] Parsing: Twitch Global Emotedata
[INF][13/11/2017 19:32:46] Saving resource to file Twitch Global Emotedata
[INF][13/11/2017 19:32:46] Loading Resource (Twitch Subscriber Emotedata)
[INF][13/11/2017 19:32:46] Downloading Resource: twitchemotes.com/api_cache/v3/subscriber.json
[INF][13/11/2017 19:37:55] Parsing: Twitch Subscriber Emotedata
[INF][13/11/2017 19:37:55] Validating Twitch Subscriber Emotedata
[INF][13/11/2017 19:37:56] Twitch Subscriber Emotedata is valid
[INF][13/11/2017 19:37:57] Saving resource to file Twitch Subscriber Emotedata`

While it is loading this file, BD is trying to load, and when it finishes to download this one, BD starts.

**Comment by h3rs** [comment]
after launching mine was stuck with 'betterdiscord is loading...' in the bottom right. pressing CTRL+R seemed to fix it.
