### ISSUE TITLE
BetterDiscord error

### ISSUE THREAD

**Issue by Parelynna** [Jiiks/BetterDiscordApp#634]
After the recent update, BetterDiscord stopped working so I tried re-installing. The install process went fine without any errors but when I start discord I get this and BetterDiscord doesn't work.
![image](https://user-images.githubusercontent.com/24868158/33916585-41fb1aa0-dfb2-11e7-966c-e28655b33775.png)

**Comment by DevilsLynAvenged** [comment]
fully close discord 
put this zip https://cdn.discordapp.com/attachments/280806472928198656/386821567260393472/emotes.zip in the betterdiscord folder and extract it and the open discord again

**Comment by Parelynna** [comment]
Where is the betterdiscord folder?

**Comment by DevilsLynAvenged** [comment]
no problem

**Comment by Parelynna** [comment]
UPDATE: After turning off discord for the night I got the same error as soon as I started it up today. Will I have to replace the files every time I close Discord or is there a permanent solution?

**Comment by DevilsLynAvenged** [comment]
I mean I can't find the permanent solution for it really so, yeah

**Comment by Parelynna** [comment]
I see, thanks,
