### ISSUE TITLE
Windows Installer Issue (Canary)

### ISSUE THREAD

**Issue by rauenzi** [Jiiks/BetterDiscordApp#635]
Hey Jiiks,

As you probably already know Canary has switched how they are handling their internals, they have moved all the desktop-specific code into a discord_desktop_core module located at `%appdata%\discordcanary\0.0.xxx\modules`. This means you no longer have to unpackage the app.asar, and instead need to inject into the file `mainScreen.js`. The injection needs to be changed up slightly since `fs` isn't used in this file, possible look for `var _url` to inject the
```js
var _betterDiscord = require('betterdiscord');
var _betterDiscord2;
```
The rest of the file parsing should be the same for the installer. 

Since the injection is occurring in this folder however, the BetterDiscord.js lib will need to be in a node_modules folder in the folder above or even just in `%appdata%\discordcanary` to make updating for versions and such easier.

Hopefully you can get around to fixing this before they move these changes over to stable which it seems they do intend to do.

**Comment by Inve1951** [comment]
this change to canary was rolled back for now.

**Comment by rauenzi** [comment]
The change has occurred again, it seems this will be their new structure going forward.
