### ISSUE TITLE
BetterDiscord Not Working

### ISSUE THREAD

**Issue by minjinim** [Jiiks/BetterDiscordApp#636]
So the past few months, BetterDiscord hasn't been working for me at all. I've tried reinstalling multiple times but to no avail. When I install it, it says there are 0 errors and when I start Discord, it says "BetterDiscord Loading..." in the bottom right corner but nothing ever happens; I see no BetterDiscord options. :( What do? I'm using Windows 10

**Comment by DevilsLynAvenged** [comment]
go to %appdata%\betterdiscord\ and see if you can upload your logs.log here

**Comment by minjinim** [comment]
[INF][15/11/2017 13:54:42] Hooking dom-ready
[INF][15/11/2017 13:54:42] Checking data/cache
[INF][15/11/2017 13:54:42] Cache expired or null
[INF][15/11/2017 13:54:42] Using repository: Jiiks and branch: master
[INF][15/11/2017 13:54:42] Getting latest hash
[INF][15/11/2017 13:54:43] Downloading Resource: api.github.com/repos/Jiiks/BetterDiscordApp/commits/master
[INF][15/11/2017 13:54:43] Hash: 4a377d964871a480dc663d921f1680ff7aeff4b3
[INF][15/11/2017 13:54:43] Getting updater
[INF][15/11/2017 13:54:44] Downloading Resource: raw.githubusercontent.com/Jiiks/BetterDiscordApp/4a377d964871a480dc663d921f1680ff7aeff4b3/data/updater.json
[INF][15/11/2017 13:54:44] Latest Version: 0.2.7
[INF][15/11/2017 13:54:44] Using CDN: cdn.rawgit.com
[INF][15/11/2017 13:54:44] Updating ext data
[INF][15/11/2017 13:54:44] Hooked dom-ready
[INF][15/11/2017 13:54:45] Loading
[INF][15/11/2017 13:54:45] Hooking ipc async
[INF][15/11/2017 13:54:45] Hooked ipc async
[INF][15/11/2017 13:54:45] Loading Resource (jQuery)
[INF][15/11/2017 13:54:45] Invalid plugin detected: config.json
[INF][15/11/2017 13:54:45] Loading plugin: CreationDate
[INF][15/11/2017 13:54:45] Loading plugin: crr
[INF][15/11/2017 13:54:45] Loading plugin: dblClickEdit
[INF][15/11/2017 13:54:45] Loading plugin: ownerTag
[INF][15/11/2017 13:54:45] Invalid plugin detected: plugin.js
[INF][15/11/2017 13:54:45] Loading Resource (jQueryCookie)
[INF][15/11/2017 13:54:45] Loading Resource (Main CSS)
[INF][15/11/2017 13:54:45] Loading Resource (Main JS)
[INF][15/11/2017 13:54:46] Loading Resource (Twitch Global Emotedata)
[INF][15/11/2017 13:54:46] Downloading Resource: twitchemotes.com/api_cache/v3/global.json
[INF][15/11/2017 13:54:46] Parsing: Twitch Global Emotedata
[INF][15/11/2017 13:54:46] Saving resource to file Twitch Global Emotedata
[INF][15/11/2017 13:54:46] Loading Resource (Twitch Subscriber Emotedata)
[INF][15/11/2017 13:54:46] Downloading Resource: twitchemotes.com/api_cache/v3/subscriber.json
[INF][15/11/2017 13:54:54] Parsing: Twitch Subscriber Emotedata
[INF][15/11/2017 13:54:54] Validating Twitch Subscriber Emotedata
[INF][15/11/2017 13:54:55] Twitch Subscriber Emotedata is valid
[INF][15/11/2017 13:54:57] Saving resource to file Twitch Subscriber Emotedata
[INF][15/11/2017 13:54:58] Loading Resource (FrankerFaceZ Emotedata)
[INF][15/11/2017 13:54:58] Downloading Resource: cdn.rawgit.com/Jiiks/BetterDiscordApp/4a377d964871a480dc663d921f1680ff7aeff4b3/data/emotedata_ffz.json
[INF][15/11/2017 13:54:58] Parsing: FrankerFaceZ Emotedata
[INF][15/11/2017 13:54:58] Saving resource to file FrankerFaceZ Emotedata
[INF][15/11/2017 13:54:58] Loading Resource (BTTV Emotedata)
[INF][15/11/2017 13:54:58] Downloading Resource: api.betterttv.net/emotes
[INF][15/11/2017 13:54:58] Parsing: BTTV Emotedata
[INF][15/11/2017 13:54:58] Validating BTTV Emotedata
[INF][15/11/2017 13:54:58] BTTV Emotedata is valid
[INF][15/11/2017 13:54:58] Saving resource to file BTTV Emotedata
[INF][15/11/2017 13:54:58] Loading Resource (BTTV Emotedata)
[INF][15/11/2017 13:54:58] Downloading Resource: cdn.rawgit.com/Jiiks/BetterDiscordApp/4a377d964871a480dc663d921f1680ff7aeff4b3/data/emotedata_bttv.json
[INF][15/11/2017 13:54:59] Parsing: BTTV Emotedata
[INF][15/11/2017 13:54:59] Saving resource to file BTTV Emotedata
[INF][15/11/2017 13:54:59] Starting Up

**Comment by DevilsLynAvenged** [comment]
what's .crr and what's .plugin.js? delete them and reload discord
