### ISSUE TITLE
Help: Better Discord Not Working

### ISSUE THREAD

**Issue by AccelerateIzaya** [Jiiks/BetterDiscordApp#639]
I just installed better discord from the site and tried it. Well, everything ran smooth. It killed discord, added some stuffs and then reopened it. But when I go to the settings, I don't find anything "Better Discord" options. Is it just me, or do I have to something else?

**Comment by Denny966** [comment]
Also got this

**Comment by LilyMaster** [comment]
You don't have it at all (there is not even a logo of BD flashing in the bottom right corner)?

Because if there is, chances are, it is updating/downloading requirements in the background. It takes at least half a minute on my installation.

**Comment by rainiette** [comment]
also have this problem. reinstalled it and nothing.

**Comment by Denny966** [comment]
I think it's a plugin problem, deleted some plugins and the settings appears again

**Comment by test112x** [comment]
Weird. It restarted discord and its just say error. I go in settigns - No # BetterDiscord ### Here

**Comment by kylespadaro2** [comment]
same. It worked earlier, but I uninstalled a few months ago and it's not working now
