### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Cenabi** [Jiiks/BetterDiscordApp#643]
Every time I attempt to install BetterDiscord, I always install with one error and the error says "Error: index.js not found."

**Comment by AlexHaber** [comment]
Use this: https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by Cenabi** [comment]
It only makes better discord load forever

**Comment by AyanamiRei1** [comment]
Yep same here.

**Comment by AlexHaber** [comment]
Try using the installer again, but select Use Zere's (unofficial) fork.

**Comment by rauenzi** [comment]
@Cenabi @AyanamiRei1 do what AlexHaber suggested

**Comment by Bogus1989** [comment]
@AlexHaber I just registered on github right now to say thank you for the tip! Zere's (unofficial) fork fixed my index.js error. Youre awesome!

**Comment by Rockorory** [comment]
Hi @rauenzi , I use windows, how will BetterDiscordMacOS.zip help me? Solo downloading the .exe by itself crashes the program.

**Comment by Wolveriot1122** [comment]
@AlexHaber Thank you man, for second I thought it was over. xD
