### ISSUE TITLE
React issues (Canary)

### ISSUE THREAD

**Issue by rauenzi** [Jiiks/BetterDiscordApp#646]
React (and react-dom) is no longer included in canary's node_modules folders and is webpacked elsewhere. This means `require('react')` errors and BD cannot load. In my fork I have fixed it by using Samogot's webpackmodules search and finding react and reactdom through that.

**Comment by Shoumil** [comment]
Mind making a tutorial for the Canary users?

**Comment by rauenzi** [comment]
For those looking for a temporary solution, you can use my installer found here: https://github.com/rauenzi/BetterDiscordApp/releases/download/0.2.82/BetterDiscordWI.exe

Be sure to select "Use Zere's Fork."

**Comment by rauenzi** [comment]
This and #635 have made it to stable @Jiiks, breaking changes for BD. You can check my fork for how I have solved it for the installer. I described above how I worked around the non-requireable react.
