### ISSUE TITLE
Betterdiscord no longer working

### ISSUE THREAD

**Issue by H2OScorpio** [Jiiks/BetterDiscordApp#647]
After Discord updated the app on 11th of December BetterDiscord stopped working, I tried reinstalling it, restarting discord, even restarting my PC but nothing worked...
(Windows 10)

**Comment by Portee** [comment]
Same, With the new update that rolled out yesterday I've been getting JavaScript errors and can't use BetterDiscord. Discord works fine without it.

**Comment by H2OScorpio** [comment]
I just noticed it keeps saying "BetterDiscord" is updating in the bottom right

**Comment by blizzard2023** [comment]
I am getting the same thing... just a betterdiscord flashing logo.

**Comment by DevilsLynAvenged** [comment]
If it's keeps blinking, remove the plugins to the desktop and reload

**Comment by H2OScorpio** [comment]
I tried that, removed all the plugins and themes but there's no difference.. still just says loading

**Comment by H2OScorpio** [comment]
Thanks a lot DevilsLynAvenged! I removed all the plugins and themes to desktop, restarted discord and it worked just fine, moved them back one by one until one the themes said it needs to update... I updated it and now it works again!
