### ISSUE TITLE
Better Discord is not working

### ISSUE THREAD

**Issue by Marker2018** [Jiiks/BetterDiscordApp#648]
Hello, i also have a problem, it appeared after Discord update on 11 or 12th December Better Discord at start always crashed with this message that is on the **image**. After the crash Discord opens but it's just simple Discord version without any Better Discord options i tried to delete and reinstall Discord and better discord more than 10 times, but it is all the same Error, Please help. I have Windows 7 64.

https://i.imgur.com/E39M3Wb.png

**Comment by DevilsLynAvenged** [comment]
Go to either the BD Main Server or Better Discord 2nd server(doesn't matter) and in pinned messages there's an emote.zip, after downloading the zip, fully close discord,open up the BetterDiscord folder extract the emote.zip that you downloaded in there and then open Discord again

**Comment by Marker2018** [comment]
Merry Christmas! and Thank you Very Much!

**Comment by DevilsLynAvenged** [comment]
No problem
