### ISSUE TITLE
Getting a JavaScript error.

### ISSUE THREAD

**Issue by Drufearr** [Jiiks/BetterDiscordApp#650]
Ever since the last Discord update (21st of December) I've been getting this JavaScript error followed by the loading BetterDiscord icon on the bottom right. I've tried deleting my cache, reinstalling BetterDiscord, reinstalling Discord itself (after deleting everything related on my PC) and I still get the same error.

![](https://image.prntscr.com/image/-1bqpRXSQE2-2WaZjibvZw.png)

**Comment by danail23** [comment]
same

**Comment by DevilsLynAvenged** [comment]
Both of you go to the pinned messages and you should see the emote.zip, after downloading the zip, fully close discord, extract the zip in the BetterDiscord folder and then open Discord back again

**Comment by Drufearr** [comment]
Still getting the same error.
