### ISSUE TITLE
hi, i cant install better discord

### ISSUE THREAD

**Issue by anki020131** [Jiiks/BetterDiscordApp#651]
when i try to install better discord it crashes, plz help

**Comment by anki020131** [comment]
it crashes when extracting app asar, what do i do?

**Comment by PastelHusky** [comment]
If its during the installing process of BetterDiscord, then it's supposed to. If it's not, then I don't know. I got it to download by doing this. 

Install better discord and open the downloaded file. 

You can extract the files by clicking on one and it might say something like this relies on other files here would you like to exact it? Say yes and pick a destination. (I put it in my documents folder).

It should open that file, Open the BetterDiscord application that has the red and black logo. Install it, one of the options will be "Restart discord" or something, check it so it can install.

It should install with no issues. And then to get Themes and Plugins follow the guides.

Installing Themes : https://betterdocs.net/documentation/install_theme.html

Installing Plugins : https://betterdocs.net/documentation/install_plugin.html
