### ISSUE TITLE
Electron installer crash on NixOS

### ISSUE THREAD

**Issue by antflga** [Jiiks/BetterDiscordApp#652]
Install directions followed, output here

```
λ ~/.local/src/BetterDiscordApp/Installers/Electron/ master* ./node_modules/.bin/electron ./src/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/alice/.local/src/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/electron ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

If this is unfixable due to Nix's package management, I would appreciate redirection to an adequate manual installation tutorial.

**Comment by DevilsLynAvenged** [comment]
This is Linux installment?

**Comment by antflga** [comment]
That's correct.

**Comment by DevilsLynAvenged** [comment]
https://www.youtube.com/watch?v=h1R2NTX-6C8&feature=youtu.be You can try this and see if you gain any luck

**Comment by vkLVGFTvJhSnvRZ** [comment]
@antflga I kind-of resolved this on another unrelated project so thought I'd share what I did. It may work for this project as well.

The same ENOENT error occurs with the bare bones [electron-quick-start](https://github.com/electron/electron-quick-start) app as well. I got around it by defining a `default.nix` in the root of the package that will use `electron` from the NixOS package manager, e.g.

[`default.nix`]:

```
with import <nixpkgs> {}; {
   nodeEnv = stdenv.mkDerivation {
     name = "node-backend";
     buildInputs = [ nodejs-8_x electron ];
   };
 }
```

I removed `electron` from the package.json in electron-quick-start, but that may not be required. Then ran `nix-shell`, the typical `npm install`, then `npm start` and it ran without an error. Obviously this is less than ideal, but it may get something working for you.

**Comment by trusktr** [comment]
@querie-cc I have this issue with my own electron app. I don't see an `electron` app in `nixpkgs`. Do you mind providing some insight over at https://discourse.nixos.org/t/running-node-electron-app-gives-enoent-error-in-nixos/5590? That would be greatly appreciated!
