### ISSUE TITLE
Index.js not found when installing to canary

### ISSUE THREAD

**Issue by pazon12** [Jiiks/BetterDiscordApp#654]
_just_ updated canary, and wanted to install BD...
Every time index.js is not found, and there is no change to canary.
How do I fix this?

**Comment by Inve1951** [comment]
get the updated installer from here <https://github.com/rauenzi/BetterDiscordApp/releases>

**Comment by pazon12** [comment]
Doesn't work either :/

**Comment by DevilsLynAvenged** [comment]
I don't think canary is working right now, try stable

**Comment by AlexHaber** [comment]
Use the updated installer above, but select Use Zere's (unofficial) fork.

**Comment by chaos234** [comment]
This also happendds for PTB-Version - Installerlog:

```
Killing DiscordPTB
Deleting old cached files
Deleting temp path
Downloading Resource: BetterDiscord.zip
Extracting BetterDiscord
Deleting C:\Users\gifsu\AppData\Local\DiscordPTB\app-0.0.41\resources\app
Deleting C:\Users\gifsu\AppData\Local\DiscordPTB\app-0.0.41\resources\node_modules\BetterDiscord
Extracting app.asar
Moving BetterDiscord to resources\node_modules\
Error: index.js not found
Finished installing BetterDiscord with 1 errors
```

Pls fix this as soon as possible, thanks.

**Comment by AlexHaber** [comment]
@chaos234 Did you use the updated installer, or the official one?

**Comment by SfSuicune** [comment]
Same error happening with latest normal version now.

**Comment by chaos234** [comment]
@AlexHaber BD0.2.82Windows

**Comment by chaos234** [comment]
Any possibility to block the update? Or will there be an update from BD soon?
Also BDs official Discord Server is rly often down for me. This should be fixed I would say.

**Comment by MaiYui** [comment]
Discord just updated, the updated version of BD is not working for me.

**Comment by AlexHaber** [comment]
@chaos234 Use this installer: https://github.com/rauenzi/BetterDiscordApp/release 
Make sure to select "Use Zere's (unofficial) fork"

@MaiYui When discord updates install it again.

**Comment by SfSuicune** [comment]
Ah, with Zere it works. Thanks :3

**Comment by Inve1951** [comment]
@chaos234 you can disable discord updates by changing the version in `app/build_info.json` to `"0.0.0"`
