### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by ereDaMeme** [Jiiks/BetterDiscordApp#655]
I do the install.bat and this happens I have been trying to fix this all day please help me. I am on the latest version of windows 10.
![y36mbqhpt82cra3bkowz9w](https://user-images.githubusercontent.com/35110449/34634277-6cbd0efa-f250-11e7-95a9-3c712a5e3ffa.png)

**Comment by ereDaMeme** [comment]
omg im still trying 2 do dis
bruh

**Comment by ne1za** [comment]
yep, same problem

**Comment by Tmp341** [comment]
What is that "system32\index.js"? Is there a file like that?

**Comment by ereDaMeme** [comment]
this is triggering me

**Comment by ereDaMeme** [comment]
@Jiiks you know a fix?

**Comment by Inve1951** [comment]
official installer: <https://github.com/Jiiks/BetterDiscordApp/releases>
updated installer: <https://github.com/rauenzi/BetterDiscordApp/releases>
