### ISSUE TITLE
index.js not found on Stable

### ISSUE THREAD

**Issue by luxidoptera** [Jiiks/BetterDiscordApp#656]
Discord Stable updated today (January 8) and now BetterDiscord has decided not to work. No flashing BD logo in the bottom right, doesn't seem to even be installed. Now, normally, when this happens after an update, I can just run the installer to I guess verify the file integrity or w/e and that fixes the issue, but this time around that's not working. I run the installer and it throws an "index.js not found" error and, once Discord is booted back up, there's still no BD logo.

Note that this is happening on Stable- I've heard of similar issues happening on Canary but since that's the less stable branch I didn't think much of it until now.

Tried replacing the installer and that didn't do anything, I'm not sure what to do from here. Anyone got any tips?

**Comment by tehbasshunter** [comment]
Until Jiiks updates the installer you have to use Zerebos installer. Make sure you check the last box or it won't work.  
  
[Unofficial Installer](https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82)

**Comment by luxidoptera** [comment]
Oh thank you, that fixed the issue!
