### ISSUE TITLE
A special person banned me from the BD2 Discord

### ISSUE THREAD

**Issue by xstefen** [Jiiks/BetterDiscordApp#657]
I would prefer it be reversed, please :)

**Comment by MaxNvy** [comment]
Are you sure GitHub is the place you want to put this message?

**Comment by xstefen** [comment]
Did you have something better in mind?

**Comment by DevilsLynAvenged** [comment]
Well yeah someone did ban you because you mention them for a picture, but if I have time I can probably unban you

**Comment by xstefen** [comment]
# MVP

**Comment by Puv1s** [comment]
https://i.imgur.com/FOmRbv8.png

**Comment by xstefen** [comment]
https://www.youtube.com/watch?v=WO1RSIliVJg
