### ISSUE TITLE
A better installer for linux?

### ISSUE THREAD

**Issue by jeffshee** [Jiiks/BetterDiscordApp#659]
Please, please improve BetterDiscord installer for Linux. It is so buggy, and seem not being updated anymore. 

1) Text on DialogBox and FileBrowser doesn't display correctly. I tried to install the font provided, it doesn't help. 
2) Uninstall button literally do nothing.
3) Too complicated. Just follow the steps found in https://betterdocs.net/documentation/install_linux.html still doesn't enough. More tricks found in Youtube required to make things work. Hope to get something that is easier to use. 

Using Fedora 27
![screenshot from 2018-01-09 19-01-02](https://user-images.githubusercontent.com/25530920/34716603-b43d521e-f573-11e7-9a2b-2248a6da2b3b.png)

**Comment by AlexHaber** [comment]
If Jiiks won't fix issues with the windows installer, chances are he won't fix issues with the linux one.

**Comment by jeffshee** [comment]
Well, that's sad... Will try whether can fix the problems or not...

**Comment by AlexHaber** [comment]
This fork may be useful for you: https://github.com/thomas-hori/BetterDiscordApp

**Comment by jeffshee** [comment]
Thanks. 
Also, I tried to changes some paths in source code, so that installation can go successfully, as the path of index.js changed on Discord 0.0.4. (https://github.com/Jiiks/BetterDiscordApp/issues/656) Well this time, BetterDiscord just doesn't want to launch...
Maybe I should leave BetterDiscord alone for now lol

**Comment by piks** [comment]
the file location of index.js like you said has been changed, so far until @Jiiks makes an "official" patch the only means of installing without doing a full manual install is to you one of the patched forks such as https://github.com/thomas-hori/BetterDiscordApp or https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by bb010g** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/betterdiscordctl?h=betterdiscord-rauenzi-git is a script that works along with https://github.com/rauenzi/BetterDiscordApp. Assumes by default that discord will be at `/opt/discord`, `/opt/discord-canary`, or `/opt/discord-ptb`, your Discord modules will be at `~/.config/discord/0.0.X/modules`, and that you keep an up-to-date copy of BetterDiscordApp's `stable16` tree at `/usr/lib/betterdiscord-rauenzi-git` for symbolic linking. All of those assumptions can be changed to work with whatever your distro or custom setup uses (read the `--help`). If you use Arch Linux and the `discord` AUR package, just installing `betterdiscord-rauenzi-git` and running `betterdiscordctl install` should be enough. (I may end up moving the script into an actual repo soon.)

**Comment by ObserverOfTime** [comment]
I wrote a [script](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172) that works for any distro and automates most of the process, using @bb010g's script for the installation. All you have to do is specify the discord path.

**Comment by bb010g** [comment]
`betterdiscordctl` is now an actual thing: https://github.com/bb010g/betterdiscordctl

Should be nicer for most users now. If your installation isn't in `/opt`, then you can scan somewhere else with `-s`/`--scan`, you can set it to Canary or PTB with `-f`/`--flavor` (i.e. `-f Canary`) if you have multiple installs, and it'll automatically manage BD (BandagedBD by default) and `asar` for you. I also tried to make `status`'s diagnostics good enough to where it's useful for figuring out what state BD is in, even if you don't manage with it.

**Comment by jeffshee** [comment]
@bb010g Thanks!! Tested on Discord 0.0.4, and it works!
