### ISSUE TITLE
BetterDiscord doesn't work after upgrading to Discord Nitro

### ISSUE THREAD

**Issue by AnimeMafiaLeader** [Jiiks/BetterDiscordApp#660]
After deciding to upgrade to Discord Nitro, my background theme and everything else about BetterDiscord immediately stopped working after restarting Discord. After about 2 re-installations of BetterDiscord, this problem still exists. I would like to know if there is a fix for this because I want my custom text colors and background back (Staring at a grey background and white text isn't appealing to me). Someone please help me.

**Comment by AlexHaber** [comment]
Try using this updated installer: https://github.com/rauenzi/BetterDiscordApp/releases
Make sure to select "Use Zere's (unofficial) fork"

**Comment by AnimeMafiaLeader** [comment]
Thanks, this worked for me.
