### ISSUE TITLE
Error: index.js not found

### ISSUE THREAD

**Issue by LeutnantRC** [Jiiks/BetterDiscordApp#661]
I tried to install the newest BetterDiscord. After installation it said "Finished installing BetterDiscord with 1 errors". Since then Discord is without BetterDiscord. The whole text said:

Killing Discord
Deleting old cached files
Deleting temp path
Downloading Resource: BetterDiscord.zip
Extracting BetterDiscord
Deleting C:\Users\Anwender\AppData\Local\Discord\app-0.0.300\resources\app
Deleting C:\Users\Anwender\AppData\Local\Discord\app-0.0.300\resources\node_modules\BetterDiscord
Extracting app.asar
Moving BetterDiscord to resources\node_modules\
Error: index.js not found
Finished installing BetterDiscord with 1 errors

Hope I can find help here, looked it up in the forums but found nothing. Thanks in advance!

**Comment by V0rdox** [comment]
same here

**Comment by coyboy60** [comment]
Same.

**Comment by Zelgadiss** [comment]
Same.

**Comment by gun95** [comment]
same

**Comment by stephen-netu** [comment]
Same here.  Not sure what else to report that would be helpful.  Thanks to anyone has any ideas!

**Comment by Zelgadiss** [comment]
Discord was updated to 3.0 version and broke better-discord :(

**Comment by gun95** [comment]
use this https://github.com/rauenzi/BetterDiscordApp/releases
it work for me

**Comment by Oskz45** [comment]
same, when i try downloading it says" Error: Index.je not found  " , but it was all working yesterday for me and gun95 that link didnt work for me.

**Comment by DevilsLynAvenged** [comment]
Did you checkmark Zere's fork?

**Comment by stephen-netu** [comment]
@gun95 Thanks, my dude!  That worked flawlessly.  🥇

**Comment by Alex-gnzl** [comment]
Are there any forks that work on Linux?

**Comment by Z0MBIE2** [comment]
Can also confirm that gun95's link works.

**Comment by clubby789** [comment]
Worked great for me too

**Comment by Ryahn** [comment]
@gun95 post did the charm for me

**Comment by DefinitelyNotSai** [comment]
I have the same problem. If anyone comes up with a solution, that would be great.

**Comment by noblereign** [comment]
this might be the problem: [](https://github.com/Jiiks/BetterDiscordApp/blob/master/NodeInstaller/index.js)
it's literally just gone. the entire blob folder.
use this instead  `https://github.com/rauenzi/BetterDiscordApp/releases` it works perfectly.

**Comment by dodi2** [comment]
@gun95 Thank you that helped alot I'm gonna make a report about how to fix it thanks to you.

**Comment by RoseFox81** [comment]
Was also having the same index.json error, tried the fork and works like a gem, Thank you so much for the fork <3

**Comment by warcry16** [comment]
@gun95 

why does windows says its a virus?

**Comment by gun95** [comment]
@warcry16 
i don't know it not my work i juste find this in other thread

**Comment by piks** [comment]
Unfortunatly for unix users, @rauenzi fork does not work.

**Comment by intrnl** [comment]
@piks could try doing a manual installation for now though?

**Comment by KaKi87** [comment]
Hi, I have the same issue with a Debian-based Linux distrubution, but @intrnl the manual installation is very ambiguous...

![manual install](https://i.goopics.net/9WdDV.png)

Would you help us with that please ?

Thanks ! :)

**Comment by ObserverOfTime** [comment]
You can use my [script](https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172) for Linux. @piks @KaKi87

**Comment by KaKi87** [comment]
It worked, thanks @ObserverOfTime !
