### ISSUE TITLE
BetterDiscord emotes not working even after using the updated installer

### ISSUE THREAD

**Issue by victoriqueII** [Jiiks/BetterDiscordApp#662]
My BetterDiscord emotes don't work even after using the updated installer. I get this message once I open discord but even after waiting for hours they don't work
![image](https://user-images.githubusercontent.com/24868158/34742676-a33001d0-f58f-11e7-868c-ab88e83fd525.png)

**Comment by DevilsLynAvenged** [comment]
Try clearing the emote cache

**Comment by victoriqueII** [comment]
Still doesn't work

**Comment by sl1msh4dy** [comment]
Have you tried restarting your computer and installing it again?

**Comment by victoriqueII** [comment]
Just tried it and emotes still don't work

**Comment by DevilsLynAvenged** [comment]
then grabbing the emote.zip in the BD2 server pinned messages in #supprt and fully close discord, extract the zip in the BetterDiscord folder and then open Discord again

**Comment by SILICON-HAWK** [comment]
is it just me or whenever i click on a emoji discord sends a msg saying subscribe to nitro and i cant use any nitro emojies
![image](https://user-images.githubusercontent.com/93534675/145564676-0867eb9f-e561-4ae6-b919-4c4cb7dc50d1.png)

**Comment by SILICON-HAWK** [comment]
is it just me, but why do i keep getting a msg that get discord nitro whenver i click on a emoji. do i have to enable some setting or something
![image](https://user-images.githubusercontent.com/93534675/145564816-af5b3764-aade-4762-9a2c-bac6368164cc.png)
