### ISSUE TITLE
index.js not found (windows 10)

### ISSUE THREAD

**Issue by EricTheEpic13** [Jiiks/BetterDiscordApp#663]
I've reinstalled both Discord and DiscordPTB, and gotten this error.
I've downloaded the latest version of BetterDiscord, and gotten this error.
I've even tried downloading DiscordCanary, and gotten this error.
It's always the same error, and I'm not sure what is going wrong.
...
Killing Discord
Deleting old cached files
Deleting temp path
Downloading Resource: BetterDiscord.zip
Extracting BetterDiscord
Deleting C:\Users\NAME\AppData\Local\Discord\app-0.0.300\resources\app
Deleting C:\Users\NAME\AppData\Local\Discord\app-0.0.300\resources\node_modules\BetterDiscord
Extracting app.asar
Moving BetterDiscord to resources\node_modules\
Error: index.js not found
Finished installing BetterDiscord with 1 errors

**Comment by FoxFireMC** [comment]
Hey, same issue here. Idk what to do next. It was working yesterday too. Then discord just wouldnt start BD so I reinstalled and got this.

**Comment by 83nn15** [comment]
Same problem over here! Had to reinstall Discord and also BetterDiscord. First, Discord.exe wasnt starting at all but after running it as administrator it works finally. Then the installisation of BetterDiscord returned the same error like above. Since the new version/ update of Discord its broken (the update with gif-emotes). It says that its installed, but mothing is installed at all. Just a blank file.

Hope it can be fixed soon.

**Comment by dodi2** [comment]
Hey guys found a way to fix it here is the link use the bd.exe https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by 83nn15** [comment]
Yeah... my AntiVirus loves that "release" too

**Comment by AlexHaber** [comment]
Use this updated installer: https://github.com/rauenzi/BetterDiscordApp/releases
Make sure to select "Use Zere's (unofficial) fork"

@83nm15 It is completely safe. You can go through the source code and build it yourself if you are unsure.

**Comment by rauenzi** [comment]
You don't have to trust my release, but you also don't need BD, but that _is_ the official fix for now

**Comment by 83nn15** [comment]
@AlexHaber Thanks man, worked like a charm! I just dont trust some kind of links, after i had to completely re-setup my pc just a few weeks ago (Malware).

The Design is also better in this version/ fix. Think i'll stick with it ;D

**Comment by EricTheEpic13** [comment]
Thank you rauenzi, it works perfectly. If anyone else has this problem, use the link above!
