### ISSUE TITLE
Broke it

### ISSUE THREAD

**Issue by pshaper** [Jiiks/BetterDiscordApp#666]
So i was trying to join someone else's discord server, and the BD UI disappeared and was replaced with the factory Discord UI. I deleted all discord files and BD files and reinstalled but now im stuck at the extracting core.asar step https://gyazo.com/87ddc64dd4053373595dab982f21aae9   Also the BD support server is unavailable due to a "temporary outage".

**Comment by DevilsLynAvenged** [comment]
restart your computer and see if it fixes it 
reason for temporary outage is because of max capacity of people

**Comment by pshaper** [comment]
Doesn't fix it. Before I uninstalled both BD and Discord and when I'm trying to reinstall BD it gets stuck on that installation phase

**Comment by DevilsLynAvenged** [comment]
Try Zere’s fork in the BD2 server if you have access to it

**Comment by pshaper** [comment]
Okay i tried that installer with zeres fork and the installer crashes at the extracting core.asar step

**Comment by pshaper** [comment]
Fixed it thanks for your help
