### ISSUE TITLE
New installer does not handle PTB or Canary

### ISSUE THREAD

**Issue by HellPie** [Jiiks/BetterDiscordApp#667]
The 0.3.0 installer breaks during the installation process and doesn't properly recognize the module/Discord (PTB and Canary are installed) paths.

Before starting the installation, right after accepting the license, the following stacktrace comes up as a popup, I'm sorry if some text isn't in english, this is not my main PC and running Windows 10 Insiders I can't install lang packs.

```
System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\HellPie\AppData\Roaming\Discord'.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileSystemEnumerableIterator`1.CommonInit()
   in System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   in System.IO.Directory.GetDirectories(String path)
   in BetterDiscordWI.panels.ConfigPanel.GetLatestVersion(String path)
   in BetterDiscordWI.panels.ConfigPanel.LocateDiscord()
   in BetterDiscordWI.panels.ConfigPanel.cbStable_CheckedChanged(Object sender, EventArgs e)
   in System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   in System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   in System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   in BetterDiscordWI.panels.ConfigPanel.ShowPanel()
   in BetterDiscordWI.FormMain.SwitchPanel(Int32 index)
   in BetterDiscordWI.FormMain.btnNext_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

The handling of Discord PTB/Canary, according to the stacktrace output is unexistant, and no warning is presented to the user from the program except for the automatically generated error popup.

**Comment by HellPie** [comment]
Issue seems to come from https://github.com/Jiiks/BetterDiscordApp/blob/master/Installers/dotNet2/BetterDiscordWI/panels/ConfigPanel.cs#L47-L50 that really can't care less whether or not the Discord version exists, they still execute because all checkboxes are checked by default in the designer.

The code is a mess, the linking with asardotnet is broken, the custom button control is not recognized, I'm using Visual Studio 2017 and for that matter until I come back from work I refuse to fix through a PR.

I hope Jiiks will get back to this asap since it's a really quite breaking piece of code and will technically break for everyone who doesn't have all discord versions installed.

I may provide a hacked-together fix for the already hacked-together installed as soon as I get a working build.

**Comment by HellPie** [comment]
Ok I got it to work, it's a mess, the code works 50%, the "not found" text does not properly name the correct version missing, but it hides the right checkbox and it may or may not crash AFTER it successfully installs.

This, for anyone who finds this issue before the fix is added to the code, is a WORKING INSTALLER.
The zip includes the .config file which idk if it's needed or not, and the .ptb file to debug the application if you fancy doing so. The exe is not tampered in any way, I just broke the broken code enough for it to not break anymore. Feel free to just trust me on this one.

https://drive.google.com/file/d/1fYKAVJHBa3hXquOexRUNWaBlKNxPLpw4/view?usp=sharing

**Comment by Henbun** [comment]
Seems to work for me as well, although it wanted to install to the "app-0.0.300" folder where "app.asar" is located, rather than "0.0.300" where "desktop_core" is located.
After changing the paths though, it works though.

**Comment by HellPie** [comment]
Since Discord officially stated BetterDiscord and all client mods are to be considered as breaking the ToS I'm removing the link to my build of the installer to discourage installing it.

Besides, Jiiks cares about the issue as much as the codebase and tbh I didn't see care at all in the code, especially considering it is an open source project affecting thousands of users' daily life on Discord.

Seeing the lack of care after half a month, I'm closing this issue because there is no need to keep it open anymore, due to a high chance to end up with an insecure, flawed Discord client or getting straight up banned for violating the ToS.

**Comment by Inve1951** [comment]
kk, here's a working one then <https://github.com/rauenzi/BetterDiscordApp/releases>
