### ISSUE TITLE
Themes aren't working

### ISSUE THREAD

**Issue by torchick11** [Jiiks/BetterDiscordApp#668]
I find that the bakground of themes only seem to work in settings, it doesn't appear behind messages anymore?

**Comment by nobibo** [comment]
Same here, it's been like that since 0.2.82 and it still isn't working with the new installer

**Comment by DevilsLynAvenged** [comment]
what themes are you guys using?

**Comment by nobibo** [comment]
I was using a theme that was made when an even older version of BetterDiscord was still around, I just downloaded a new one and it's working just fine.
