### ISSUE TITLE
I CAN'T DELETE BETTER DISCORD !

### ISSUE THREAD

**Issue by WanTeDxz** [Jiiks/BetterDiscordApp#672]
When i Delete it its come back 
i can't delete it 
PLEASE HELP ME !

**Comment by Tmp341** [comment]
Try to delete with a hard deleter app, like [This](https://sourceforge.net/projects/eraser/files/Eraser%206/6.2/)

**Comment by Inve1951** [comment]
4th party tools? no
reinstalling discord _should_ remove BD, i can't say for sure if it does after latest discord changes
if it does not then do the following (assuming windows here):
* go to `%appdata%\discord\0.0.300\modules\discord_desktop_core`
* delete the `app` folder and `index.js`
* rename `index.js.old` to `index.js`
* restart discord

**Comment by GRIMMMMM** [comment]
just delete th folder in %appdata% called better discord

**Comment by Inve1951** [comment]
that won't remove BD @GRIMMMMM

**Comment by MAX0342** [comment]
just reinstall discord

**Comment by brettshaffett** [comment]
@Inve1951 I've done all of your steps and they basically _broke_ my Discord. I even try reinstalling and it **STILL** does not work.

**Comment by Kushinaa** [comment]
@TheDankestWaffle Wich folder did you delete??
I have 14 files and one _**installed.json**_
I'm not even sure I'm in the right place...
![image](https://user-images.githubusercontent.com/43581157/46027101-0891f280-c0bb-11e8-83ca-dd05b059aeb8.png)

**Comment by Kushinaa** [comment]
I found an easier way check the link guys ;)
https://gist.github.com/intrnl/09db7693fba679d78d9003d676e189c3
