### ISSUE TITLE
Half Appeared

### ISSUE THREAD

**Issue by OhSugoi911** [Jiiks/BetterDiscordApp#673]
My betterdiscord themes aren't working in chats. When I open them, I only see it for 1 second and then disappears. I can only see the sidebar; servers, groups and friends but I can't go into them to read their conversations.

**Comment by Inve1951** [comment]
try together with [theme fixer](https://github.com/xNightWulf/ThemesForBetterDiscord/blob/master/zThemeFix.theme.css). outdated themes need it.
