### ISSUE TITLE
Error while attempting to Install BetterDiscord.

### ISSUE THREAD

**Issue by JeanAbdel** [Jiiks/BetterDiscordApp#676]
Hello there !
I have an Issue with BD's installation. It always says this when I try to install BD :

Searching for Discord core in: C:\Users\ADMIN\AppData\Roaming\Discord\0.0.297\modules\discord_desktop_core
core.asar does not exist in: C:\Users\ADMIN\AppData\Roaming\Discord\0.0.297\modules\discord_desktop_core!
Unable to continue installation.

Please can you tell me the way to fix this ? 
Thank you ;)

**Comment by DevilsLynAvenged** [comment]
Try this fork <https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>

**Comment by JeanAbdel** [comment]
Oh yeah it worked ! thank you very much for the fast reply :) :)

**Comment by sethpeace** [comment]
I'm having the same problem... and the fork doesn't run at all on my computer...

**Comment by ShadowDevilsAvenged** [comment]
You're 3 years late on this issue

**Comment by sethpeace** [comment]
Oh... lol nvm then
