### ISSUE TITLE
I get a JavaScript error on startup

### ISSUE THREAD

**Issue by thang1160** [Jiiks/BetterDiscordApp#680]
I follow this guide but it didn't work https://github.com/Jiiks/BetterDiscordApp/wiki/FAQ
Tried to reinstall both discord and BD but it didn't work either
![bug](https://user-images.githubusercontent.com/35557579/35086161-20237652-fc5e-11e7-8a8d-b5ce41c8b2c9.png)

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82> here and choose Zere's fork
