### ISSUE TITLE
Cannot read property 'forEach' 

### ISSUE THREAD

**Issue by goonboy123** [Jiiks/BetterDiscordApp#683]
Keep getting this error on startup. Reinstalled Discord and BetterDiscord and it's still wont work

![untit222led-1](https://user-images.githubusercontent.com/35635155/35186082-b1b4d2ce-fe38-11e7-8764-22c7244050f8.jpg)

**Comment by Inve1951** [comment]
use this to install Zere's fork which supposedly fixes it <https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>
