### ISSUE TITLE
Emote Menu Not Appearing

### ISSUE THREAD

**Issue by skibblesx** [Jiiks/BetterDiscordApp#684]
I guess i can't seem to get it to show up or maybe I'm doing something wrong? It doesn't seem like anything changes when i disable the emoji menu and I don't see any options for frankerfacez or BTTV.

I've completely wiped and reinstalled all instanced of BetterDiscord and Discord itself to start fresh, still nothing. I just have the standard emote menus.

**Comment by DevilsLynAvenged** [comment]
Fully close discord. Extract this in `%appdata%/betterdiscord/`https://cdn.discordapp.com/attachments/119918741516451840/345554778832633867/emotes.zip <--- and restart discord and see if it works

**Comment by Inve1951** [comment]
needs BBD afaik
