### ISSUE TITLE
Installed 0.3.0, still shows 0.2.82?

### ISSUE THREAD

**Issue by MadMakz** [Jiiks/BetterDiscordApp#685]
![bdv](https://user-images.githubusercontent.com/3930214/35198319-5c276b04-feed-11e7-8479-9a912be2b594.jpg)

> Searching for Discord core in: C:\Users\MyUser\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core
> Located core.asar in: C:\Users\MyUser\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core
> Killing Discord Processes
> Extracting core.asar
> Finished extracting core.asar
> Injecting BetterDiscord to C:\Users\MyUser\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core\core
> Rewriting index.js
> Finished injecting BetterDiscord
> Fetching latest hash
> Downloading BetterDiscord package
> Finished downloading BetterDiscord package
> Deleting old BetterDiscord
> Extracting BetterDiscord package
> Deleting temp file C:\Users\MyUser\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core\BetterDiscord.zip
> Verifying installation
> Verifying: Discord files
> Verifying BetterDiscord package
> Verification successful
> Restarting Discord
> Finished installing BetterDiscord!

**Comment by Inve1951** [comment]
known, only shows the wrong version number
