### ISSUE TITLE
better discord java script error

### ISSUE THREAD

**Issue by killermonkTR** [Jiiks/BetterDiscordApp#687]
![image](https://user-images.githubusercontent.com/35770544/35336505-aa142f08-0129-11e8-81ec-00e4cc71aa6d.png)

**Comment by DevilsLynAvenged** [comment]
download this zip https://cdn.discordapp.com/attachments/280806472928198656/386821567260393472/emotes.zip fully close discord and then extract the zip to the betterdiscord folder and then open discord again

**Comment by Inve1951** [comment]
`%appdata%\betterdiscord` ^

**Comment by NdMSnIpEz** [comment]
Exact same issue. I've tried both the official release and Zere's unofficial fork, completely un-installing in 
between each attempt. I've also unzipped the emotes .json files into the %appdata%\betterdiscord folder as suggested and no change, I'm faced with the same two errors on start up either way. Works perfectly fine on my main PC, but not on this laptop.
![1](https://user-images.githubusercontent.com/3456983/35340880-3a274070-011c-11e8-82d2-e755b51f6efe.png)
![2](https://user-images.githubusercontent.com/3456983/35340881-3a3e2326-011c-11e8-9fe8-ab84b1303bda.png)

**Comment by Inve1951** [comment]
k, reinstall using zere's fork -> <https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>

**Comment by killermonkTR** [comment]
thank you

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-25 11:56 GMT+03:00 Inve1951 <notifications@github.com>:
