### ISSUE TITLE
Can't uninstall after 0.3.0

### ISSUE THREAD

**Issue by Top-Nep** [Jiiks/BetterDiscordApp#688]
I accidentally installed Better Discord to the wrong installation of Discord (I have two installations) and despite following the uninstall instructions from the FAQ it seems I can't due to not having this path: %localappdata%\Discord\app-0.3.000\resources\node_modules

I was able to delete everything else but I couldn't find this and when I reinstall discord all the better discord folders pop back up.

**Comment by 4D48** [comment]
Same problem here.

**Comment by 4D48** [comment]
1. Delete Discord (from Apps and Features on Windows 10)
2. Delete following folders:
	C:\Users\User\AppData\Roaming\BetterDiscord
	C:\Users\User\AppData\Roaming\discord
3. Install Discord back
