### ISSUE TITLE
Virus block from Bitdefender

### ISSUE THREAD

**Issue by Daisenki** [Jiiks/BetterDiscordApp#689]
BetterDiscordWI.exe blocked by Bitdefender Antivirus Plus 2018 (Build 22.0.17.209) with code Trojan.GenericKD.12786310

**Comment by Shoumil** [comment]
same, I just turned off BitDefender temp to bypass

**Comment by LukeMageSlayerYT** [comment]
i didnt have this problemit installed fine here
 u setup ur bitdefender wrong?
