### ISSUE TITLE
Cannot Install Better Discord On Linux

### ISSUE THREAD

**Issue by cfonash1** [Jiiks/BetterDiscordApp#690]
I am having a problem with installing better discord. when i try to install it a window pops up saying error /usr/share/discord/resources/app/index.js not found (i have seen people that fixed it but none have been for ubuntu)

**Comment by DevilsLynAvenged** [comment]
https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172 use this link
