### ISSUE TITLE
Error has been here for months now. What the hell.

### ISSUE THREAD

**Issue by RichHammond** [Jiiks/BetterDiscordApp#691]
Every time I boot up discord with BD installed, this pops up in the top left.

https://u.lewd.se/JNTGw8_Discord_2018-01-30_18-18-08.png

Betterdiscord clearly has a broken installer if something is missing.

This issue has existed for months.

**Comment by Inve1951** [comment]
grab [BBD (zere's fork)](https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82)
