### ISSUE TITLE
BetterDisccord is loading...

### ISSUE THREAD

**Issue by wafebreaker** [Jiiks/BetterDiscordApp#692]
Everytime i start discord its shows the icon bottom right with "BetterDiscord is loading....". Started Discord a few times but i have the same problem everyday. Also reinstallation didnt work at all. And pls dont tell me i have to wait because first installation or first start would take a while, no its definitly not working.

What can i do?

**Comment by Inve1951** [comment]
grab [BBD (zere's fork)](https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82)
