### ISSUE TITLE
Theme images not working!!!!

### ISSUE THREAD

**Issue by BrokenProton** [Jiiks/BetterDiscordApp#693]
For the past couple hours I've been trying to get themes to work on my discord but no background images are showing anywhere. I've tried several themes ut one I especially wanted was the Nova theme as I thought it looked the best, please help!!!!

**Comment by DevilsLynAvenged** [comment]
try adding this to the custom css!!!!

/* fix not having a background image anymore */
.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
  background: transparent !important;
}
/* optionally adjust background brightness (0: original image, 1: black) */
.layers-20RVFW {
  background: rgba(0,0,0, 0.3) !important;
}

**Comment by BrokenProton** [comment]
i added it to the end but it didnt work

**Comment by Schwartzu** [comment]
add it to the console

**Comment by BrokenProton** [comment]
What do you mean put it in the console?

**Comment by DevilsLynAvenged** [comment]
he mean to say to go to BetterDiscord Settings > Custom CSS and put the code there and make sure you click on save and update

**Comment by BrokenProton** [comment]
the background flashes whenever i transition but doesnt stay
