### ISSUE TITLE
Unexpected token in JSON at position 0 help?

### ISSUE THREAD

**Issue by blackthunder9000** [Jiiks/BetterDiscordApp#694]
![betterdiscord error](https://user-images.githubusercontent.com/36028934/35666540-52e13634-06df-11e8-9115-34fa33600aea.PNG)

I keep getting this issue when I launch discord. before I deleted both discord and better discord it wouldn't even launch. after deleting both fully from my pc and fully reinstalling both it shows that in the upper left. the only JSON files in my  discord 0.0.300 are all fine I think (not an IT nor big tech expert). any help would be appreciated!

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82> try using this fork and see if the problem goes away

**Comment by blackthunder9000** [comment]
@DevilsLynAvenged thank you mate It worked!

**Comment by MentosPL** [comment]
not working
