### ISSUE TITLE
A JavaScript  error occurred in the main process

### ISSUE THREAD

**Issue by CallyyllaC** [Jiiks/BetterDiscordApp#695]
Not really sure whats going on, tried reinstalling the latest version and still nothing, always the same error message:
Uncaught exception:
SyntaxError: Unexpected token
![2018-02-01_08-15-59](https://user-images.githubusercontent.com/16276325/35668227-95562684-0728-11e8-8375-fda438b2f135.png)

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>  try using this

**Comment by CallyyllaC** [comment]
That worked thanks
