### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by K3KEK** [Jiiks/BetterDiscordApp#697]
I can download it normally yeah but everytime I start up discord its back to normal and plus its in the wrong appdata so im trying to change the installation folder but it cant find the appdata im using. With this I cant even put themes for it as it says location not found. Help please

**Comment by DevilsLynAvenged** [comment]
yeah it's suppose to turn back to normal and are you using this `%appdata%\betterdiscord\` ?

**Comment by K3KEK** [comment]
no im using %appdata%\local(or roaming)

**Comment by K3KEK** [comment]
there are multiple accounts here so its using the admin one
