### ISSUE TITLE
Cannot install BetterDiscord.

### ISSUE THREAD

**Issue by Blitzshake481** [Jiiks/BetterDiscordApp#698]
I run the BetterDiscordWI.exe, it finds the discord core thing, and it runs. It closes Discord, discord restarts during installation and the installer says done. Did that twice, then forced discord to close before running the installation AGAIN so it wouldn't pop up at all during the installation and nothing has changed. I'm not getting any emotes or anything.

**Comment by DevilsLynAvenged** [comment]
you used this? <https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>

**Comment by ThatCrapOsuPlayer** [comment]
i tried that link and it isn't working
