### ISSUE TITLE
Better discord wont uninstall

### ISSUE THREAD

**Issue by Reapercomic** [Jiiks/BetterDiscordApp#699]
So i deleted all the betterdiscord files and also re installed discord itself and the files just keep duplicating is there any fix ?

**Comment by DevilsLynAvenged** [comment]
try restarting your computer and try again

**Comment by Reapercomic** [comment]
I already have i formated my second hardrive to get rid of it idk what happened but they really need to add an uninstall feature

**Comment by HoldenRiot** [comment]
Yeah, I just deleted all the files and restarted and still nothing. Still there. I also Attempted to Uninstall Discord and Reinstall and Still there...
