### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by taion** [Jiiks/BetterDiscordApp#7]
I want to Kappa spam my way through all of the new Reactiflux on Discord from my dev box.

Looks like the installer currently assumes Windows. I'll try to put a PR together when I get a chance.

**Comment by Candunc** [comment]
I'm currently working on an OS X release, since it looks like it hasn't yet been integrated. I'll probably have a testing branch out later tonight (~1:00 AM UTC)

**Comment by taion** [comment]
Oh, dang. You beat me to it. Sorry!

**Comment by Candunc** [comment]
Hmm, looks like there is a major difference between OS X and the Windows installs. It might take me a little while to figure out how to get around this.

**Comment by Candunc** [comment]
It seems to mostly work, I created a pull request.

**Comment by Candunc** [comment]
Completed in release v0.1.5 with OS X support, can close this issue.

**Comment by taion** [comment]
Thanks!
