### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by Qwula** [Jiiks/BetterDiscordApp#701]
Hi,

I just installed better discord yesterday. I am not very tech savvy with these kinds of installations. Basically, I wanted to get a transparent discord theme. So I found this https://github.com/HoLLy-HaCKeR/BetterDiscord-Themes-and-Plugins/blob/master/Plugins/transparency_patcher.md. However, after carefully following the instructions I get stuck on the step of installing the plugin. Where you are suppose to "Click Enable Patch." But each time I click that I get this message "Unable to read file C:\Users\Asus\AppData\Local\Discord\app--0.0.300\resources\app.asar/index.js. See console for error object." I tried looking at the console, but heck as I know what it means. It mentioned that there were 12 errors or something. I then tried installing another theme, then another theme none of them worked. They moved around somethings, but in general it looked like a giant mess and not like the theme that was pictured.

Any help is greatly appreciated!

**Comment by DevilsLynAvenged** [comment]
get the latest patcher by Zerebos in the plugin-repo in either BD servers

**Comment by jbdizzle** [comment]
For anyone that wants to know how. Install the following

https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/TransparencyPatcher


https://github.com/rauenzi/BetterDiscordAddons/tree/master/Themes/TransientMaterial


and then add the following code to css: #app-mount {
    background: transparent !important;
}
