### ISSUE TITLE
Sidebars on servers grey box, not transparent anymore

### ISSUE THREAD

**Issue by StrikeExia** [Jiiks/BetterDiscordApp#702]
![ss 2018-02-08 at 01 34 17](https://user-images.githubusercontent.com/36275623/35988747-bc394026-0cd5-11e8-982b-8f0d9fb4bf52.png)

Been like this since latest discord update, how to fix? It's usually transparent to show my background, only this part of discord is grey.

**Comment by rauenzi** [comment]
This is an issue with your theme, and not with BD itself. Talk to the developer of your theme.

If your issue is resolved, please close it.

**Comment by StrikeExia** [comment]
I don't remember where I downloaded the theme or who's it is, isn't there anyway to just edit the css or do a custom css to fix it?

**Comment by rauenzi** [comment]
Yes but that's something to ask on the BD server's css channel. Not to open an issue on github.

If your issue has been resolved, please close it.
