### ISSUE TITLE
Tried to remove betterdiscord, now normal discord won't even open?

### ISSUE THREAD

**Issue by zelanai** [Jiiks/BetterDiscordApp#704]
So I downloaded betterdiscord just to see what it was like, didn't find it that great and went to remove it. That in itself was a hassle as I'd delete the files and then they'd reappear when opening the discord app. Finally I got rid of them but now discord won't even open saying a fatal javascript error occured, cannot find module 'betterdiscord' so it can't run. I've tried reinstalling discord multiple times but it's exactly the same. What the heck do I do??

**Comment by Modder4869** [comment]
just go to "%AppData%\discord\0.0.300\modules\discord_desktop_core" and edit index.js and replace ./core with ./core.asar
or check the wiki on how to uninstall it

**Comment by zelanai** [comment]
Well I don't know in what way you mean to edit index.js but the ./core is already ./core.asar

**Comment by Modder4869** [comment]
you see index.js file? just open it with notepad or any text editor and replace this line
`module.exports = require('./core');`
with
`module.exports = require('./core.asar');`

**Comment by zelanai** [comment]
Oh I see, got confused by the wording! That worked, thank you very much for your help!

**Comment by Modder4869** [comment]
alright, no problem
