### ISSUE TITLE
BetterDiscord setup error

### ISSUE THREAD

**Issue by PenDriveBR** [Jiiks/BetterDiscordApp#706]
I started the installer and from this error can anyone help me?
Killing Discord
Deleting old cached files
Deleting temp path
Downloading Resource: BetterDiscord.zip
Extracting BetterDiscord
node_modules doesn't exist, creating
Extracting app.asar
Moving BetterDiscord to resources\node_modules
Error: index.js not found
Finished installing BetterDiscord with 1 errors

**Comment by rauenzi** [comment]
Perhaps try the latest version of the installer
