### ISSUE TITLE
TypeError: self.try is not a function

### ISSUE THREAD

**Issue by BetterDiscordUser** [Jiiks/BetterDiscordApp#707]
I get this after installing BD 0.3.0 to DiscordCanary 0.0.202:

![grafik](https://user-images.githubusercontent.com/36449905/36159020-03f41d6c-10de-11e8-8aa4-5115a400d9e4.png)

I have to click on OK two times then discord starts but without BD

**Comment by DevilsLynAvenged** [comment]
Use the latest installer in pinned messages

**Comment by BetterDiscordUser** [comment]
Which one? 😕
