### ISSUE TITLE
betterDiscord not working

### ISSUE THREAD

**Issue by corgerino** [Jiiks/BetterDiscordApp#708]
i previously had betterdiscord installed and then it randomly started to stop working so i re installed and the download went perfectly fine no errors or anything bad, discord restarted but BetterDiscord wasnt enabled on it, if anyone knows how to fix this please tell me.

**Comment by Modder4869** [comment]
use this <https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82>

**Comment by corgerino** [comment]
@Modder4869 I installed it but it didnt fix the problem, betterdiscord is still not on it

**Comment by Modder4869** [comment]
any error? do you have any plugins installed ? try to remove it before

**Comment by corgerino** [comment]
@Modder4869 no errors, and no plugins installed

**Comment by Modder4869** [comment]
are you sure that path is correct when you run the installer? and you have last discord version installed?

**Comment by corgerino** [comment]
the path is correct and i have the latest version of discord

**Comment by corgerino** [comment]
C:/Users/(name)/AppData/Local/Discord/app-0.0.300

**Comment by Modder4869** [comment]
in installer the path something like this `C:/Users/(name)/AppData/Local/Discord/app-0.0.300\discord\0.0.300\modules\discord_desktop_core` if this was not the problem then
you can try to move this folder to another location `%AppData%\BetterDiscord\`
then open run (winkey+r) and paste this `taskkill /IM discord.exe /F` then try again if that didn't work.
uninstall discord normally , make sure `%AppData%\Discord` , `%LocalAppData%/discord` and `%AppData%\BetterDiscord\` (or move bd one if you want your previous settings) folders are deleted. then install discord and try the link i posted above

**Comment by corgerino** [comment]
there isnt another discord folder inside C:/Users/(name)/AppData/Local/Discord/app-0.0.300

**Comment by Modder4869** [comment]
sorry i mistype it `C:\Users\Modder4869\AppData\Roaming\discord\0.0.300\modules\discord_desktop_core`

**Comment by Modder4869** [comment]
if you can join BD discord server i might be able to help you better (just mention me Modder4869#2901)

**Comment by Modder4869** [comment]
@corgerino maybe try to run installer as administrator too

**Comment by Inve1951** [comment]
install BBD (zere's fork) and don't have the used CDNs blocked, you can check discord's console for connection errors (ctrl+shift+i)
