### ISSUE TITLE
BetterDiscord not loading

### ISSUE THREAD

**Issue by w4tchdoge** [Jiiks/BetterDiscordApp#709]
I've got BD v0.3.0 and all was well until Discord auto installed the Feb 15 update. Now after I open Discord, BD doesn't load, there's just the BD logo pulsing in the bottom-right corner.

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82 use this and checkmark Zere's fork during installation

**Comment by w4tchdoge** [comment]
Thanks @DevilsLynAvenged , BD is working now. I'll be closing this issue then
