### ISSUE TITLE
BetterDiscord stuck

### ISSUE THREAD

**Issue by SacredStep** [Jiiks/BetterDiscordApp#710]
I didn't have a discord_desktop_core file, so I made one and also the core.asar with it. I now get this and only this when I download it. Searching for Discord core in: C:\Users\#######\AppData\Roaming\Discord\0.0.298\modules\discord_desktop_core
Located core.asar in: C:\Users\######\AppData\Roaming\Discord\0.0.298\modules\discord_desktop_core
Killing Discord Processes
Extracting core.asar
And it ends there. No progress while downloading.

**Comment by rauenzi** [comment]
Update your discord... current version is 0.0.300, the changed architecture didn't happen until then so of course those files didn't exist.

**Comment by SacredStep** [comment]
How do I update, exactly?

**Comment by rauenzi** [comment]
run discord and right click check for updates, or run the updater.exe

**Comment by SacredStep** [comment]
Where would the location of updater.exe be?

**Comment by rauenzi** [comment]
C:\Users\your username here\AppData\Local\Discord\update.exe

**Comment by SacredStep** [comment]
When I run updater, it just opens cmd and closes it super quickly

**Comment by SacredStep** [comment]
nvm
