### ISSUE TITLE
betterdiscord setup freezes

### ISSUE THREAD

**Issue by miumiu11** [Jiiks/BetterDiscordApp#711]
when i try to install betterdiscord, the installer stops at "downloading to:..." nothing else happens after. if i try to start discord, a fatal javascript error occures. (see screenshot) [https://imgur.com/a/eFPFA](url)

**Comment by DevilsLynAvenged** [comment]
try this installer and choose <https://github.com/rauenzi/BetterDiscordApp/releases/> also I wasn't able to see the screenshot

**Comment by rauenzi** [comment]
Try what devils said, github changed their certificate style so the normal installer may have issues
