### ISSUE TITLE
javascript main error

### ISSUE THREAD

**Issue by gco360** [Jiiks/BetterDiscordApp#712]
i dont know what to do all i get it is javascript main error and discord hangs please help me with it

**Comment by Modder4869** [comment]
try this installer https://github.com/rauenzi/BetterDiscordApp/releases/ and choose BandagedBD and then while running the installer checkmark Zere's fork

**Comment by gco360** [comment]
thank you but this theme does not work https://github.com/gco360/better-discord-theme-gco

**Comment by gco360** [comment]
thank you but this theme does not work https://github.com/gco360/better-discord-theme-gco
im using BandagedBD

**Comment by DevilsLynAvenged** [comment]
gco it must be 
//META{"name":"A_GCO_theme","description":"made by reuben owner of gco","author":"reuben","version":"1.0"}*//{}

**Comment by DevilsLynAvenged** [comment]
that's why it's not working
