### ISSUE TITLE
Discord keeps crashing!

### ISSUE THREAD

**Issue by Crixton** [Jiiks/BetterDiscordApp#715]
My discord keeps crashing.....
I will be in a call and randomly after 15 minutes - 2 hours it will crash and i can still hear the people speaking but if i speak they cant hear me, if i leave the call discord freeze's and i have to restart my whole computer for it to work again, i use the app discord on my pc please help!!!!!!!

- Its not the Overlay

**Comment by Modder4869** [comment]
seems like Discord issue not BD(assming you removed all plugins) , reinstall discord after you remove it completely

**Comment by CrixMC** [comment]
I already reinstalled discord

I think I unistalled it completely

**Comment by rauenzi** [comment]
This is not a BD issue

**Comment by Crixton** [comment]
what does that mean?

**Comment by Crixton** [comment]
Oh .......
