### ISSUE TITLE
Unexpected token in JSON at possition 0

### ISSUE THREAD

**Issue by molnia2145** [Jiiks/BetterDiscordApp#716]
Help me please, always when I run the discord I get an error 
`BetterDiscord - Somphing went wrong :( Unexpected token in JSON at possition 0`
How to fix it, im reinstall discord, betterdiscord and still this error occurs. This error got out of me somewhere in November, and I do not remember how, but I fixed it, but now I can not, help please

**Comment by DevilsLynAvenged** [comment]
try deleting user.json in
%AppData%\BetterDiscord\ and see if that works

**Comment by blxss** [comment]
That worked.
