### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by harvo900** [Jiiks/BetterDiscordApp#717]
Searching for Discord core in: C:\Users\Harvo\AppData\Roaming\DiscordCanary\0.0.203\modules\discord_desktop_core
Located core.asar in: C:\Users\Harvo\AppData\Roaming\DiscordCanary\0.0.203\modules\discord_desktop_core
Killing Discord Processes
Extracting core.asar

[It just freezes and doesnt do anything]

**Comment by harvo900** [comment]
ive also tried reinstalling the Setup program and ive tried it with discord PTB and discord Canary

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/ try using this and click on the bandaged BD option

**Comment by harvo900** [comment]
I tried it but its still doing the same thing

Searching for Discord core in: C:\Users\Harvo\AppData\Roaming\DiscordCanary\0.0.203\modules\discord_desktop_core
Located core.asar in: C:\Users\Harvo\AppData\Roaming\DiscordCanary\0.0.203\modules\discord_desktop_core
Killing Discord Processes
Extracting core.asar
