### ISSUE TITLE
themes not working

### ISSUE THREAD

**Issue by gco360** [Jiiks/BetterDiscordApp#718]
thank you but this theme does not work https://github.com/gco360/better-discord-theme-gco
im using BandagedBD 
![screenshot_1](https://user-images.githubusercontent.com/31587917/36656597-245072c0-1aef-11e8-886a-0a17b6984133.png) it becomes like this instead of this 
![screenshot_2](https://user-images.githubusercontent.com/31587917/36656809-ea4402da-1aef-11e8-8a61-efa55850254a.png)

**Comment by Modder4869** [comment]
https://pastebin.com/aaDxbwzs copy all to custom css click save then update and themes are not BD Issue , join BD server if you need help :)

**Comment by gco360** [comment]
@Modder4869 quoter plugin not working

**Comment by Modder4869** [comment]
@gco360 just update it or something , still not BD issue.
