### ISSUE TITLE
Don't react to "Show windows stacked" Win 10

### ISSUE THREAD

**Issue by c20xh2** [Jiiks/BetterDiscordApp#719]
On the vanilla Discord program the "Show windows stacked" and  "Show windows side by side" from Windows 10 works (right click on taskbar to show the options). 

After installing BetterDiscord those function don't work anymore, Discord windows stay the same size and is not moved by windows. Would love to get those function working again.

**Comment by Modder4869** [comment]
well it is unlikely that it is BD issue 🤔 , either way https://github.com/rauenzi/BetterDiscordApp/releases/ try using this and click on the bandaged BD option.
it works for me so..

**Comment by c20xh2** [comment]
Bandaged BD gave me back the  "Show windows stacked" and "Show windows side by side", thank you.

**Comment by Modder4869** [comment]
@c20xh2 no problem , you can close the issue now 😄
