### ISSUE TITLE
Installation error on Linux: "Weird error" followed by "Command not found".

### ISSUE THREAD

**Issue by fhuewhd** [Jiiks/BetterDiscordApp#721]
I can't install BetterDiscord.  
I use Linix (Zorin OS 9, a variation of Ubuntu Trusty Tahr which uses the Gnome destop insteadd of the Unity one.)
I followed the steps on the Tutorials page (https://github.com/Jiiks/BetterDiscordApp/wiki/Tutorials), but when I got to "npm install", a lot of stuff scrolled past, but ended in:
`npm http 304 https://registry.npmjs.org/is-utf8
npm http 304 https://registry.npmjs.org/error-ex
npm http GET https://registry.npmjs.org/is-arrayish
npm http 304 https://registry.npmjs.org/is-arrayish

> electron-prebuilt@1.2.8 postinstall /home/ab/BetterDiscordApp/Installers/Electron/node_modules/electron-prebuilt
> node install.js

/home/ab/BetterDiscordApp/Installers/Electron/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ab/BetterDiscordApp/Installers/Electron/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 8
npm ERR! not ok code 0
`

On entering the command "sudo ./node_modules/.bin/electron ./src", I got 
`sudo: ./node_modules/.bin/electron: command not found`

Any idea how to resolve this, please?  Would be much appreciated, as I just can't stand Dicsord's default uinterface.  I've tried the BetterDiscordCTL program but that failed in a different way, which I'll post on THAT Issues page.

**Comment by Modder4869** [comment]
try this or join BS support server
https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by fhuewhd** [comment]
Um, thanks but um, that's the BetterDiscordCTL program I said wasn't working.  

As for joining the support server, if you mean on Discord itself, the thing is that with my sensory issues I really CAN'T hold a coherent conversation on Discord as is, I could only use it if I had some way of switching off the animations.  (e.g. the flashing dots when someone's typing, etc.)  That's why I was trying to install BetterDiscord!  Also, Discord itself seems to be broken at the moment, unless it's just updating really slowly - it's been hanging at the updater stage (the one that says "Readying the felines..."  :-D  ) for ten minutes now.  Perhaps one or otherof these installation attempts upset it.

**Comment by Modder4869** [comment]
you could use browser or something (like your phone) it makes thing easier, invite in wiki anyway
yea i know but your problem seems to be with npm , well for animation (might work for you) you can change it ***temporary***, when discord open press ctrl shift i , click on element , there is style tab and + button click it
it will make something like  body{ } and there is file inspector-stylesheet , click on that then paste below there
```css
*{
    animation:none !important;
}
```
this should stop animation.

**Comment by fhuewhd** [comment]
Tried to do this as best I could understand it ( it didn't display quite the same things you said, perhhaps you're not using Firefox), but it didn't stop any of the animations.  (I have no smartphone.)  Never mind, no great hurry, I'll wait to see if anything else comes up on here.  Thaks for the effort.

**Comment by Modder4869** [comment]
Oh it was for discord application , well for FireFox just install this https://addons.mozilla.org/en-US/firefox/addon/live-editor-for-css-and-less/
then click on its icon and add this
```css
* {
    -moz-animation: none !important;
    animation: none !important;
}
```
@fhuewhd

**Comment by fhuewhd** [comment]
Issue fixed by uninstalling everything very thoroughly and then reinstalling again using BetterDiscordCTL method, following exact instructions word for word.  I'd been trying the main method and then the BetterDiscordCTL method haphazardly, switching to one when the other failed, and I think that must have muddled things up.  Lesson, don't mix the two, if one fails then uzninstall BetterDiscrod, Node and NPM completely before trying again with the other.  Thanks very much for all the help here and in chat, Mdder.
