### ISSUE TITLE
BdApi GetIdByName and GetNameById are broken

### ISSUE THREAD

**Issue by Ubiw** [Jiiks/BetterDiscordApp#722]
![issue](https://user-images.githubusercontent.com/26337371/36884619-b56bb2e6-1da7-11e8-97c4-d862240fddf7.png)

**Comment by rauenzi** [comment]
Yes these functions are unreliable and have been for quite some time. There are alternative methods however.

**Comment by Ubiw** [comment]
I'll use discord api with token..

**Comment by rauenzi** [comment]
Please don't, we don't support nor condone that and it's a great way to get yourself banned. If you need that info use internals/webpack modules.
