### ISSUE TITLE
error when loading discord with better discord

### ISSUE THREAD

**Issue by ashley2222** [Jiiks/BetterDiscordApp#723]
![error](https://user-images.githubusercontent.com/11374770/36895716-d2a2c790-1e07-11e8-80d5-ba24906b0b06.PNG)
i get this error every time i load discord with better discord installed and i tried reinstalling better discord but it doesnt work after

**Comment by Modder4869** [comment]
try using this https://github.com/rauenzi/BetterDiscordApp/releases , choose bandagedBD

**Comment by ashley2222** [comment]
now it giives me
![capture](https://user-images.githubusercontent.com/11374770/36907885-a7957e9c-1e31-11e8-8559-afc492ee62fb.PNG)

**Comment by rauenzi** [comment]
delete this folder `%appdata%\discord\0.0.300` run discord then try to reinstall BD/BBD
