### ISSUE TITLE
Option names barely legible on light theme

### ISSUE THREAD

**Issue by mkahvi** [Jiiks/BetterDiscordApp#724]
BetterDiscord option names are barely legible if user has light theme selected. They should change with the selected theme like the normal options names.

I have no CSS added to BetterDiscord yet, so this is just default theme failure.
![2018-03-10-10_49_03-discord](https://user-images.githubusercontent.com/8120158/37240196-f3837708-2450-11e8-84fb-a31c9b467ae7.png)

**Comment by DevilsLynAvenged** [comment]
```CSS
.theme-light #bd-settingspane-container .ui-switch-item .style-description {
    color: black;
}``` this will change the font color only in light theme mode

**Comment by enmoku** [comment]
That doesn't seem to have any effect. Saved, updated, and even restarted Discord. Tried modifying that bit of CSS and I couldn't make it do anything.
