### ISSUE TITLE
It's illegal

### ISSUE THREAD

**Issue by MAX0342** [Jiiks/BetterDiscordApp#726]
Discord doesnt officially support this stuff and it's against the ToS please stop

**Comment by MuperMumpjanSario** [comment]
Against the ToS != Against the law

And please specify what part of the ToS this project is going against.

**Comment by MAX0342** [comment]
Are you fucking serieous

**Comment by intrnl** [comment]
We never said that it wasn't against the Terms of Service in the first place.
It's up to you whether you want to use it or not, we're not held liable for you getting banned over the client modification.

People have been coming to us about that Reddit comment which was edited recently, it's just a clarification of earlier statement.

**Comment by MAX0342** [comment]
You agree not to (and not to attempt to) (i) use the Service for any use or purpose other than as expressly permitted by these Terms or (ii) copy, adapt, modify, - Discord ToS RIGHTS TO USE THE SERVICE Paragraph 2

**Comment by intrnl** [comment]
What about it?

**Comment by intrnl** [comment]
As long as you're not stupid like abusing their API, you'd be pretty much safe.

They said that their actions can range from not doing anything to a service ban.
