### ISSUE TITLE
Syntax Error: Unexpected Token

### ISSUE THREAD

**Issue by GeorgeCY2** [Jiiks/BetterDiscordApp#728]
i keep on getting this now i installed betterdiscord, had to uninstalled untill i find help, also couldnt join the betterdiscord server!

**Comment by Modder4869** [comment]
huh? use this 
https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by GeorgeCY2** [comment]
![image](https://user-images.githubusercontent.com/36137970/37374051-0382bd20-2722-11e8-99e8-0d0c2e416c8b.png)
same thing

**Comment by GeorgeCY2** [comment]
nvm issue is closed!
