### ISSUE TITLE
Better Discord Background

### ISSUE THREAD

**Issue by NeoGPT** [Jiiks/BetterDiscordApp#730]
I recently tried using Better Discord and used this theme: https://github.com/Xteal/Red-n-Black
But, my background ALWAYS shows as completely black. I've also tried using another CSS. 
Any suggestions on what the problem might me?

**Comment by intrnl** [comment]
This isn't a problem with BetterDiscord, it's just your CSS theme.

Contact your theme author about it.

**Comment by Modder4869** [comment]
@NeoGPT , this might work https://pastebin.com/aaDxbwzs and what intrnl said 😄

**Comment by NeoGPT** [comment]
that cant be because i tried installing others and nothing

**Comment by NeoGPT** [comment]
@Modder4869 that worked thank you!
