### ISSUE TITLE
Can't See nor use the emote menu.

### ISSUE THREAD

**Issue by ImLavius** [Jiiks/BetterDiscordApp#731]
i tried installing this: 

https://cdn.discordapp.com/attachments/119918741516451840/345554778832633867/emotes.zip

but to no avail, looked around but couldnt find anything, really sick and tired of scrolling through the tiny, default emoji menu in discord.

**Comment by jacobmix** [comment]
Same here. The Twitch emotes work. The menu just doesn't show up.
Changing the option in the settings does nothing, and turning off all my plugins doesn't help either.

**Comment by jacobmix** [comment]
Using [BandagedBD](https://github.com/rauenzi/BetterDiscordApp/releases) seems to fix it. Also made some of my plugins work again.

**Comment by ImLavius** [comment]
thank you man, you fixed it! one more thing, i cant seem to be able to favourite non twitch emotes?
