### ISSUE TITLE
A JavaScript Error Occurred in the Main Processes

### ISSUE THREAD

**Issue by TonyChen0801** [Jiiks/BetterDiscordApp#732]
When I tried installing better discord on my laptop this happened
![image](https://user-images.githubusercontent.com/37592131/37671273-c0464eb2-2c41-11e8-8f92-90ad871ea7a5.png)

**Comment by SamboyCoding** [comment]
Same just happened to me

**Comment by DominykasPetke** [comment]
Temporary workaround: https://github.com/rauenzi/BetterDiscordApp/releases/ , Choose bandagedBD.exe

**Comment by Syer10** [comment]
Did not work, It started after an update for discord that I got today.
Here is the full error.

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught exception:
 TypeError: self.try is not a function
    at C:\Users\Syer10\AppData\Roaming\discord\0.0.300\modules\discord_desktop_core\core\node_modules\BetterDiscord\lib\Utils.js:258:25
    at C:\Users\Syer10\AppData\Roaming\discord\0.0.300\modules\discord_desktop_core\core\node_modules\BetterDiscord\lib\BetterDiscord.js:183:13
    at IncomingMessage.<anonymous> (C:\Users\Syer10\AppData\Roaming\discord\0.0.300\modules\discord_desktop_core\core\node_modules\BetterDiscord\lib\Utils.js:40:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[OK]

**Comment by TonyChen0801** [comment]
I found out that after i restarted my computer it fixed itself and better discord started working might not work for everyone but it did for me
