### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by ThatOneWeeb55** [Jiiks/BetterDiscordApp#733]
So whenever I open Discord with B.D. active this pops up, i'm not very good with coding or files, so i don't understand what any of it means. B.D. was working when i first downloaded it but I went on to Discord a few weeks later (as the computer I had it on wasn't at my home) & it came up with the "unexpected token in JSON at possition 0" message at the top. I reinstalled both B.D. & Discord and it fixed it but B.D. wasn't working, I have deleted & reinstalled both many more times, but nothing has worked, does anyone know how to fix it?

![hhvt344](https://user-images.githubusercontent.com/37614292/37700094-581aed86-2d3e-11e8-8124-e2dfa70d32b3.jpg)

**Comment by Modder4869** [comment]
use this https://github.com/rauenzi/BetterDiscordApp/releases
if you got same error then get https://cdn.discordapp.com/attachments/280806472928198656/406142867749208064/emote_data.zip
and extract it in %AppData%\BetterDiscord\

**Comment by ThatOneWeeb55** [comment]
wow, that was fast

**Comment by Modder4869** [comment]
well support server has git channel , anyway that fix your problem? if so you can close the issue

**Comment by ThatOneWeeb55** [comment]
yes i did, and that's a good idea lol
