### ISSUE TITLE
Javascript error please help

### ISSUE THREAD

**Issue by KneeGrowth** [Jiiks/BetterDiscordApp#734]
![capture](https://user-images.githubusercontent.com/37646849/37749831-32e2797c-2d60-11e8-869e-4ea83700d435.PNG)

i am dumb dumb baby please help

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases> use this and choose bandagedBD.exe and run it on the desktop

**Comment by KneeGrowth** [comment]
Thanks mate
