### ISSUE TITLE
foreach is undefined

### ISSUE THREAD

**Issue by ultrabeast12** [Jiiks/BetterDiscordApp#735]
Issue on startup- it was fine and just now started doing this. Can't find a working solution.
![screenshot_22](https://user-images.githubusercontent.com/37648914/37752669-8e9ae06a-2d6f-11e8-9218-0aa7980e352b.png)

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases> use this and choose bandagedBD.exe and run it on the desktop

**Comment by ultrabeast12** [comment]
dope, that worked. thanks
