### ISSUE TITLE
Themes not working after fixing javascript error

### ISSUE THREAD

**Issue by jck-n** [Jiiks/BetterDiscordApp#737]
http://prntscr.com/iv3zkq

Here's a screenshot of my error, I installed BandagedBD and now BD itself works, but my themes do not.

Anyone know how to get my themes working? It says the themes load, but they never actually appear.

For context on how this started I got mad and hit a key on my keyboard and then when I tried going to my discord DM's, it would just open it in my browser, so I restarted discord and had to fix a javascript error.

**Comment by DevilsLynAvenged** [comment]
what theme are you trying to use?

**Comment by Modder4869** [comment]
if it is clear vision just download it again , and not really BD issue (if that particular theme won't work)
