### ISSUE TITLE
BetterDiscord setup keeps freezing need help.

### ISSUE THREAD

**Issue by DroidGamingXD** [Jiiks/BetterDiscordApp#738]
When i do the setup and its almost done
Searching for Discord core in: C:\Users\Zintis\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core
Located core.asar in: C:\Users\Zintis\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core
Killing Discord Processes
Extracting core.asar
Finished extracting core.asar
Injecting BetterDiscord to C:\Users\Zintis\AppData\Roaming\Discord\0.0.300\modules\discord_desktop_core\core
Rewriting index.js
Finished injecting BetterDiscord
Fetching latest hash
Downloading BetterDiscord package

its just freezes help plz.

**Comment by DevilsLynAvenged** [comment]
use this <https://github.com/rauenzi/BetterDiscordApp/releases/> and choose bandagedBD.exe and run it
