### ISSUE TITLE
Javascrip error

### ISSUE THREAD

**Issue by koquei** [Jiiks/BetterDiscordApp#739]
http://prntscr.com/ivfd6t

**Comment by DevilsLynAvenged** [comment]
use this <https://github.com/rauenzi/BetterDiscordApp/releases/> and choose bandagedBD.exe and run it on the desktop

**Comment by Jollyx3** [comment]
This is weird, i launched bandagedBD.exe on desktop and it when i accept terms it takes a long time and says killing discord processes for about 5 mins, how long is it suppose to take?

**Comment by koquei** [comment]
thanks :)

**Comment by koquei** [comment]
my bandageBD just take a few seconds to install @Jollyx3

**Comment by M0nkey1** [comment]
@Jollyx3 Same

**Comment by M0nkey1** [comment]
@DevilsLynAvenged Even when I fully closed discord it didn't work

**Comment by Worths** [comment]
For some reason I went into minimum and now I'm stuck.
