### ISSUE TITLE
BetterDiscord JavaScript error, Please help!

### ISSUE THREAD

**Issue by nageekabe** [Jiiks/BetterDiscordApp#740]
I have opened up my discord to this message; http://prntscr.com/ivnjjz

if you can find a fix to this please reply, I cant seem to find anything, I have tried uninstalling both BetterDiscord and Discord itself. I have also tried moving some of the files, but nothing seems to work. This is not like any of the other JavaScript errors I have seen on other posts, for some reason it isn't nearly about what they are getting. Anyways if you can help please reply.

**Comment by DevilsLynAvenged** [comment]
go here <https://github.com/rauenzi/BetterDiscordApp/releases/> and choose bandagedBD.exe and then fully close discord and run the installer on the desktop
