### ISSUE TITLE
JavaScript error persists even with BandagedBD

### ISSUE THREAD

**Issue by RyujiShiryu** [Jiiks/BetterDiscordApp#743]
https://cdn.discordapp.com/attachments/401953279266783242/428356998468337696/unknown.png

I tried using the **Bandaged BD Installer** but I still get these JavaScript errors...any ideas as to why it isn't working? I tried using the installer loads of times...

**Comment by DevilsLynAvenged** [comment]
try running it on the desktop and run it as admin too

**Comment by Modder4869** [comment]
Oh well that connection issue , either disable anything that blocks request or use VPN

**Comment by RyujiShiryu** [comment]
Tried running it on Desktop as an Admin and it just worsened the error, now closing Discord results in a crash, with the same error popping up...any suggestions?

**Comment by takeserelly** [comment]
Try Cleaning and uninstalling both discord and BD deleting both and trying again with BBD
