### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by ToyoTheFox** [Jiiks/BetterDiscordApp#744]
Whenever I try to download BetterDiscord, everything seems to run smoothly... until the end... whenever it tries to download the files from the GitHub source, it just doesn't want to finish doing whatever it needs to do, and I end up uninstalling it mid-download meaning I have to uninstall discord entirely, then reinstall, so for now I cant enjoy the wonderful perks of BetterDiscord, if anyone finds a solution, or has had this problem and fixed it, please reply.

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases/> use this and choose bandagedBD.exe and run it on the desktop as admin

**Comment by ToyoTheFox** [comment]
thank you so much :3
