### ISSUE TITLE
Stuck on installation!

### ISSUE THREAD

**Issue by GhostfaceG99** [Jiiks/BetterDiscordApp#745]
It started with that everytime I started Discord/BetterDiscord i got an error that i just had to click "Ok" on and Betterdiscord still worked. After a while I googled the error and and my conclusion was that I needed to use BandagedBD. I started BandagedBD and it worked just fine untill i got stuck on "Extracting BandagedBD package/Renaming package dir". After 20min i closed BandagedBD and tried to start discord but I just got an error (not the same error as i used to have) so i decided to reinstall discord. I uninstalled discord and tried to reinstall it but i got an error, after alot of helpless googleing I somehow solved the problem myself. I tried to install BetterDiscord but it got stuck on "Extracting BandagedBD package/Renaming package dir" (the same as when i tried to use BandagedBD). I tried to use BandgedBD again but it gave me the same error. What am I doing wrong?
When I use BandagedBD I do it on the desktop and I run it as Administrator!
Edit: I wiped my whole pc (factory reset) and it still gets stuck on renaming dir!

**Comment by Modder4869** [comment]
if  you run it on desktop then move it to another location and run as administrator

**Comment by Modder4869** [comment]
and if you can join BD support server that will help

**Comment by MatAnd21** [comment]
Не получается установить BandagedBD package Не помогает перемещение , запуск от имени администратора даже VPN
Что делать?
![image](https://user-images.githubusercontent.com/97650846/155871553-61af61a0-e6cd-4245-a8d0-68896f914ff9.png)
