### ISSUE TITLE
BandagedBD gets stuck at renaming package dir

### ISSUE THREAD

**Issue by Aymt** [Jiiks/BetterDiscordApp#747]
![image](https://user-images.githubusercontent.com/23024256/38146456-e42c0c36-3402-11e8-9ca1-77486cde52f6.png)
Any ideas? Ran as admin in multiple locations, it shouldn't matter that I'm running it from a secondary HD right?

**Comment by Modder4869** [comment]
disable antivirus / malware byte , and try to uncheck restart discord

**Comment by Modder4869** [comment]
and running it from a secondary HD might cause problem iirc

**Comment by Modder4869** [comment]
you are not the first one to tell me that , just **disable** Malwarebytes

**Comment by Aymt** [comment]
I just checked the source and did it manually, thanks!

**Comment by Modder4869** [comment]
np , you can close the issue now
