### ISSUE TITLE
BetterDiscord Blue should be disabled by default

### ISSUE THREAD

**Issue by jpratt9** [Jiiks/BetterDiscordApp#748]
This doesn't make any sense and it seems like a visual bug when paired ~~when~~ with native dark mode.

**Comment by Modder4869** [comment]
goaway

**Comment by jpratt9** [comment]
Sorry?

**Comment by jpratt9** [comment]
@Modder4869 Why? It's a legitimate concern and I'd be interested in seeing it discussed.
