### ISSUE TITLE
The Same Javascript error even after installing BandagedBD

### ISSUE THREAD

**Issue by GamerDudeMarche** [Jiiks/BetterDiscordApp#749]
![image](https://user-images.githubusercontent.com/37951250/38161113-3b1d3008-34fb-11e8-9e17-4053e9aaadff.png)

**Comment by tehbasshunter** [comment]
Different error.  
  
Go to `%appdata%/betterdiscord` and delete bdstorage.json.  
  
Be warned that will delete any customCSS you had along with your favorited emotes.  
  
Sidenote delete user.json as well as that's for the other error.

**Comment by GamerDudeMarche** [comment]
That worked, thanks !

**Comment by fuckbetterdiscord** [comment]
didnt work because its garbage, can't uninstall because its garbage
