### ISSUE TITLE
can't install betterdiscord

### ISSUE THREAD

**Issue by therockey** [Jiiks/BetterDiscordApp#750]
After one of the discord updates, the betterdiscord stopped working. So I went to reinstall it. I downloaded the installer and opened it. But it did something it didn't do before - it asked me for admin rights. Even when I type in the password, it doesn't work - it searches for discord in the admin files, but Discord is installed  in MY appdata folder, not THE ADMIN.

(Sorry for bad English)

**Comment by Modder4869** [comment]
Choose BandagedBD (if stuck then move installer to desktop and run as admin) <https://github.com/rauenzi/BetterDiscordApp/releases>
change path if it is wrong

**Comment by iB0ss** [comment]
Someone help, in the setup there is no option for where I could download Better Discord to
