### ISSUE TITLE
Still cannot fix the issue of BandagedBD

### ISSUE THREAD

**Issue by RyujiShiryu** [Jiiks/BetterDiscordApp#751]
Things I attempted 
- Deleting the **bdstorage.json and user.json files**
- Reinstalling Discord itself and THEN injecting the BandagedBD
- Search WHERE was the exception to see what could have been causing it (fruitless results)

And the error in this image persists. What is this **self.try function it mentions, anyway?**
https://cdn.discordapp.com/attachments/401953279266783242/428356998468337696/unknown.png

**Comment by Modder4869** [comment]
connection error , either ***disable*** antivirus , firewall , malwarebytes or use vpn

**Comment by Modder4869** [comment]
and join support server 🤷‍♀️
