### ISSUE TITLE
Better Discord Wont Install Properly

### ISSUE THREAD

**Issue by laceliteanonymous** [Jiiks/BetterDiscordApp#752]
Better Discord has not been installing properly. In the installer it will have its usual installment. Then it gets to the end of the installment, it gets stuck on downloading the .zip file. When I go to the folder location the .zip file is there but its empty. So I closed the installer and tried to open Discord. That's when i got this error
https://imgur.com/GVIWpH3 . If someone could please help me with this. I have tried all sorts of different ways to install it. I don't know if this is important or not but my labtop is running windows 8 (yes i know, its really outdated).

**Comment by Modder4869** [comment]
Choose BandagedBD (if stuck then move installer to desktop and run as admin) https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by laceliteanonymous** [comment]
Thank you, its working perfectly now!

**Comment by Fauzz** [comment]
not working in my PC

**Comment by Eian0** [comment]
Mine's stuck on "attempting to kill discord"
