### ISSUE TITLE
Starting up discord with better discord installed gives this java error message

### ISSUE THREAD

**Issue by Sonicbob1337** [Jiiks/BetterDiscordApp#753]
![2 12 12 12 12 12 12 12capture](https://user-images.githubusercontent.com/38022197/38223563-8ad44e5a-36b9-11e8-9a85-7fa4faa07c4e.PNG)

**Comment by Sonicbob1337** [comment]
Whenever I installed Better Discord and restarting and turning on Discord, this error message pops up everytime.

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases> use this and choose bandagedBD.exe and run it

**Comment by quentinguyot2** [comment]
thx @DevilsLynAvenged ^^
