### ISSUE TITLE
Better Discord JavaScript

### ISSUE THREAD

**Issue by misrine** [Jiiks/BetterDiscordApp#754]
![screenshot_2](https://user-images.githubusercontent.com/38026613/38229281-c36ee340-3710-11e8-9f57-ea9bca18454f.png)

I tried to delete its folder and to re-install it but it doesnt work , please help

**Comment by qwerasd205** [comment]
There are currently a lot of issues with BetterDiscord.
Instead use Bandaged BetterDiscord, a patched version of BetterDiscord.
https://github.com/rauenzi/BetterDiscordApp/releases
Gets stuck while installing? Move to desktop, run as admin.

**Comment by misrine** [comment]
thank you! my discord is working again xD
