### ISSUE TITLE
Twitch emotes not showing up

### ISSUE THREAD

**Issue by dnc510** [Jiiks/BetterDiscordApp#755]
A few weeks ago my twitch emotes stopped working. Happened before and i fixed it with downloadin an installer from here. but this time around I've tried everything, reinstalling BD, from both the site, and BandagedBD, and they still refuse to show up. Everything emote related in the settings is turned on, so it's not that, I'm at a complete loss. Any ideas?

**Comment by DevilsLynAvenged** [comment]
download this zip https://cdn.discordapp.com/attachments/280806472928198656/406142867749208064/emote_data.zip and then fully close discord and extract the zip in the betterdiscord folder and then reload discord and if it still doesn't show up, then try clicking on the clear emote cache and see what happens

**Comment by dnc510** [comment]
Where is there a clear emote cache button? I'm not sure if i'm just not seeing it or if I don't have one. The former is very well possible, but i've looked in every possible menu as far as I know.
