### ISSUE TITLE
Betterdiscord issue

### ISSUE THREAD

**Issue by strawberrybelts** [Jiiks/BetterDiscordApp#756]
I already have betterdiscord installed and themes too. Everything looks like the quiet theme except the member list (it's the default discord look). How do I fix that?

**Comment by DevilsLynAvenged** [comment]
```CSS
.scroller-fzNley.members-1bid1J {
    background: rgba(0,0,0,0.3);
}``` copy this code in the custom css

**Comment by strawberrybelts** [comment]
@DevilsLynAvenged it worked!! thank you!!
