### ISSUE TITLE
Javascript error on startup?

### ISSUE THREAD

**Issue by AJdisco** [Jiiks/BetterDiscordApp#758]
Starting up the app works fine without better discord installed, However with it installed it will launch, and then on plugin initi it will freeze up and produce this java error
![image](https://user-images.githubusercontent.com/26025947/38369165-04bbd2ac-38df-11e8-8d3e-a2e6867e2c9b.png)

**Comment by Modder4869** [comment]
probably it is one of your plugins , anyway use BandagedBD if you are not https://github.com/rauenzi/BetterDiscordApp/releases
