### ISSUE TITLE
Better Discord failed to start on Win10

### ISSUE THREAD

**Issue by CHENS85** [Jiiks/BetterDiscordApp#759]
when I launch discord with betterdiscord installed, it shows this
![betterdicorderror](https://user-images.githubusercontent.com/5460820/38398191-06405554-3910-11e8-9767-8b0a539fa423.PNG)

**Comment by DevilsLynAvenged** [comment]
<https://github.com/rauenzi/BetterDiscordApp/releases/> use this choose bandagedBD.exe and run it on the desktop as admin

**Comment by CHENS85** [comment]
Thx its working now
