### ISSUE TITLE
A JavaScript  error occurred in the main process

### ISSUE THREAD

**Issue by BruninGamer** [Jiiks/BetterDiscordApp#760]
%appdata%/BetterDiscord
Inside there are 2 folders, plugins and themes. Either of them has to contain folders

**Comment by DevilsLynAvenged** [comment]
then that means that it hasn't downloaded correctly 🤔 
use this <https://github.com/rauenzi/BetterDiscordApp/releases/> and choose bandagedBD.exe and run it and see if they return
