### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by FlintnSteal** [Jiiks/BetterDiscordApp#762]
When I turn on discord I get the error cannot read property 'forEach' of undefined. Not sure how to fix

**Comment by Modder4869** [comment]
Choose BandagedBD (Mac or Windows)(if stuck then move installer to desktop and run as admin for [windows]) <https://github.com/rauenzi/BetterDiscordApp/releases>

**Comment by Modder4869** [comment]
and maybe look into previous issues before creating one :/
