### ISSUE TITLE
Discord Startup - JavaScript error

### ISSUE THREAD

**Issue by XMChEeSeCaKEG** [Jiiks/BetterDiscordApp#763]
![capture](https://user-images.githubusercontent.com/6087590/38429665-f15e8280-39b6-11e8-83aa-434ebfb40c92.PNG)

Discord starts up and then displays this error message. Better discord continues to load on a loop in the bottom right corner without fully loading. 
Any idea of what the issue is?

**Comment by DevilsLynAvenged** [comment]
use this <https://github.com/rauenzi/BetterDiscordApp/releases/> and choose bandagedBD.exe and run it

**Comment by XMChEeSeCaKEG** [comment]
This worked, Thank you for the help.
