### ISSUE TITLE
Better Discord JavaScript Error Occurred in the main process

### ISSUE THREAD

**Issue by Arenexity** [Jiiks/BetterDiscordApp#764]
Error Popup: https://prnt.sc/j26fuh

**Comment by AkaiiKitsune** [comment]
Download BandagedBD.exe from here
https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by allansramblings** [comment]
BandagedBD fixes the javascript error but seems to stop BD from running at all.

**Comment by TheJollyDEV** [comment]
![image](https://user-images.githubusercontent.com/31150975/40262522-d4514b88-5abc-11e8-817a-f8306464310c.png)
This appears even when I use Bandaged BD
