### ISSUE TITLE
A JavaScript error occurred in the main process (Uncaught exception; cannot read forEach)

### ISSUE THREAD

**Issue by Gooobis** [Jiiks/BetterDiscordApp#765]
Error: https://puu.sh/zYpTo/fbb2fd758f.png

Tried reinstalling, didn't fix, tried spamming ctrl+r and it works 1/100 times.

**Comment by DevilsLynAvenged** [comment]
Download BandagedBD.exe and run it. If it's stuck, move the installer to your desktop and run it as an administrator.
https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by Gooobis** [comment]
u fixed it and so quickly my god thank
