### ISSUE TITLE
Better discord doesent work on the latest update

### ISSUE THREAD

**Issue by Neutrideo** [Jiiks/BetterDiscordApp#766]
Just stops working.

**Comment by Modder4869** [comment]
if you just updated discord and BD isn't working, reinstall BetterDiscord with this link: 
https://github.com/rauenzi/BetterDiscordApp/releases
If it's stuck on "Killing Discord Proccesses", move the installer to the desktop and run it as administrator (Windows Only)

**Comment by theace0296** [comment]
I would just like to affirm that this does fix the issue ^
Thank you!

**Comment by LenKagetsu** [comment]
Every time I try to download it from there (or here for that matter) I get the "This XML file does not appear to have any style information blah blah blah" screen. Doesn't matter what browser I use. The zips work but those are of no use to me.

**Comment by YorkshirePhoenix** [comment]
@Modder4869 jeesh dude, THANK YOU!

I haven't been able to load BetterDiscord since the 3.0 update, tried everything even blamed Windows and re-installed it (RIP).
Installed the linked release and it worked fine after restarting Discord <3

**Comment by guavajason** [comment]
thx

**Comment by hibikiw0** [comment]
it says NOT found!

**Comment by Hypnos-Discord** [comment]
When I tried to do the move to desktop and rerun as administrator thing, it still gets stuck on "Killing Discord Processes"

**Comment by Linkys0805** [comment]
it doesn't work...
i install BD many times, i also uninstall and install discord and BD again but nothing
