### ISSUE TITLE
Java Script Error

### ISSUE THREAD

**Issue by Andrew-MJ** [Jiiks/BetterDiscordApp#767]
Every Time I Open Discord And Hope That Better Discord Works I See This. I Have Tried Reinstalling Both And It Didnt Work. If You Can Help Me Jiiks That Would Be Great.
![unknown png](https://user-images.githubusercontent.com/38384494/38771392-2c007d94-3fe8-11e8-9dcb-02f7049fd52b.jpg)

**Comment by Modder4869** [comment]
https://gist.github.com/Jiiks/14a75d4b7efc8fa12cc23e03a882283b#doesntwork
