### ISSUE TITLE
BetterDiscord OSX Issue

### ISSUE THREAD

**Issue by sqlty** [Jiiks/BetterDiscordApp#768]
The Installing part is great but importing themes and plugins are NOT working.
Open Theme folder ==> Drag .css in ==> Command + r ==> **no themes installed** same with plugins

**Comment by DevilsLynAvenged** [comment]
install this https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBDMacInstaller.zip if you haven't already and see if it works

**Comment by intrnl** [comment]
Make sure that the file name ends in `.theme.css` or that the file starts with `//META`
