### ISSUE TITLE
Java Script Error

### ISSUE THREAD

**Issue by NRGmomo** [Jiiks/BetterDiscordApp#769]
![reeeeeeeeeeeeeeeeeeeeeeeeeeeeeee](https://user-images.githubusercontent.com/38430140/38811629-4f7359e2-418a-11e8-82d6-1e15c1eab6e5.png)

**Comment by DevilsLynAvenged** [comment]
use this https://github.com/rauenzi/BetterDiscordApp/releases/ and choose bandagedBD.exe and run it on the desktop as admin
