### ISSUE TITLE
Java Script Error (Syntax Error: Unexpected Token)

### ISSUE THREAD

**Issue by BoxloxxD** [Jiiks/BetterDiscordApp#770]
![screenshot 155](https://user-images.githubusercontent.com/38437402/38825515-dba270a2-417a-11e8-8b3a-d81b78779c25.png)
Please help me im unable to use my discord

**Comment by DevilsLynAvenged** [comment]
it's probably the plugins causing it try moving them to the desktop and reload and then put them back in the folder one by one
