### ISSUE TITLE
Stops Responding While Installing on Mac

### ISSUE THREAD

**Issue by Pirateboy04** [Jiiks/BetterDiscordApp#771]
<img width="796" alt="screen shot 2018-04-16 at 18 17 12" src="https://user-images.githubusercontent.com/25210618/38838026-6e48b82c-41a2-11e8-9bbd-5203dec4e0e4.png">
It stays in this screen, not responding, for as long as I've let it run.

MacBook Pro (15-inch, 2017)
macOS 10.13.4

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBDMacInstaller.zip use this and run the installer

**Comment by Pirateboy04** [comment]
That is what I did.

**Comment by tterb** [comment]
I had a similar issue and the linked file seems to have fixed it.
Thanks!
