### ISSUE TITLE
Better Discord JavaScrpit issue...

### ISSUE THREAD

**Issue by beweress** [Jiiks/BetterDiscordApp#773]
[Sceenshot with error](http://puu.sh/A7ETK/9ac8a9aaa5.png)

**Comment by intrnl** [comment]
i'd rather recommend you going to our support server instead.

**Comment by coolmanbo1** [comment]
Im having the same exact error

**Comment by intrnl** [comment]
yea except this place is a bad place to get help

**Comment by coolmanbo1** [comment]
Gonna go to the support server then

**Comment by beweress** [comment]
oh, i solved my problem, i just downloaded another version from here: https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.3.0i

**Comment by coolmanbo1** [comment]
Yeah i did the same
