### ISSUE TITLE
A Java Script Error

### ISSUE THREAD

**Issue by NexusNovaz** [Jiiks/BetterDiscordApp#775]
![image](https://user-images.githubusercontent.com/19374500/39087585-efd4e298-459a-11e8-8cee-4a2a56337a11.png)
I keep getting this as i try to launch Discord after installing BD

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe download this and then run the installer on the desktop as admin

**Comment by 4rz0** [comment]
@DevilsLynAvenged Thanks, "solved" the problem for me as well.
