### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by JustSomeGoat** [Jiiks/BetterDiscordApp#776]
![oof](https://user-images.githubusercontent.com/34248571/39100068-c691fd32-461f-11e8-97f4-306533dec901.PNG)

**Comment by DevilsLynAvenged** [comment]
try using the vpn and then run this installer on the desktop as admin https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe

**Comment by intrnl** [comment]
I'd recommend that you go to our support server instead.

**Comment by gco360** [comment]
download bbd
