### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by SydoxParadox** [Jiiks/BetterDiscordApp#779]
i keep geting a java error that is 

Uncaught exception:
  TypeError" Cannot read properly 'isFocused' of null
   at WebContents. <anonymous>
(C:\Users\Ower\AppData\Roaming\discord\0.0.300\modules\discord_desktop_core\co...:31)
  at emitOne (events.js:101:20)
  at WebContents.emit (events.js:188:7)

i tried bandage and reinstaling discord, updating java and still nothing.

**Comment by DevilsLynAvenged** [comment]
try running the installer on the desktop as admin

**Comment by SydoxParadox** [comment]
Still nothing. I rebooted my pc and discord loaded but the theme was off (by this I mean it was not loading the background photo). So I reran the bandage app on my desktop and now I am still getting the same error.

**Comment by MrJeffOfficial** [comment]
help! i have the same error! i runned discord as a admin but it the discord launched for 2 seocnds and then it showed me the error.

**Comment by thesnorki** [comment]
so i had this problem too and i fixed it with opening task manager and turning of a process called "igfxm module".

**Comment by Winterr88** [comment]
i'm having the same problem

**Comment by NelsonAngel** [comment]
@thesnorki It is either called "igfxm module" or "In Game Manager" in Task Manager, that fixed it for me too. Then after hitting OK discord restarted itself and booted fine.

**Comment by HelloThisIsDaniel** [comment]
there's no process called igfxm module in Task Manager but I still got that error. help?

**Comment by HelloThisIsDaniel** [comment]
nevermind. in case no igfxm module appears in Task Manager, just close any or all of the Discord processes. worked for me.

**Comment by KuraideWolfie** [comment]
I don't know if this'll help, but I was having the same issue just a few moments ago and tried these steps, and I seem to be up and running:
- Delete the 'discord' folder in your '%appdata%' folder
- Delete the 'Discord' folder in your '%localappdata%' folder
- Re-download the Discord installer and run it

I deleted the folders and then re-installed Discord, and I did take notice it installed some updates before crashing while trying to authenticate on my machine; however, rerunning it caused it to get another update, and now it seems to be fine for me.

**Comment by Andronachi-Marian** [comment]
Me too:
`Uncaught exception:
TypeError" Cannot read properly 'isFocused' of null
at WebContents. 
(C:\Users\Ower\AppData\Roaming\discord\0.0.300\modules\discord_desktop_core\co...:31)
at emitOne (events.js:96:13)
at WebContents.emit (events.js:188:7)`

After restart the PC the error appears again.

**Comment by astromeme** [comment]
this error literally caused my computer to crash and not be able to start up properly since :/
