### ISSUE TITLE
[Tutorial] Remove unnecessary files.

### ISSUE THREAD

**Issue by Bluscream** [Jiiks/BetterDiscordApp#78]
If you installed manually you may end up having way more files in your Discord folder then you need.

In the folder ``` %localappdata%\Discord\app-<VERSION>\resources\node_modules\BetterDiscord ``` You'll only need:
![needed files](http://i.imgur.com/7OjufmG.png)

And in the folder ``` %localappdata%\Discord\app-<VERSION>\resources\node_modules\BetterDiscord\lib ``` You'll only need:
![needed files](http://i.imgur.com/tCr4YcG.png)

**Comment by DoNotSpamPls** [comment]
*Added to wiki*
#Close
