### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Genomatsu** [Jiiks/BetterDiscordApp#780]
I installed and used BandagedBD.exe and nothing, pls help.
I used BetterDiscord for a month ago, today i reseted my pc and throw me that error.
(Sorry for my bad english, i speak Spanish :/)
![image](https://user-images.githubusercontent.com/38803403/39392089-a7647b32-4a85-11e8-92e0-d41e3c396289.png)

**Comment by DevilsLynAvenged** [comment]
try running it on the desktop as admin and see what happens

**Comment by Genomatsu** [comment]
I tried right now and nothing happened, same error.

**Comment by rauenzi** [comment]
borra esto: `%appdata%\discord\0.0.300`, comenza Discord y trata usar BandagedBD.exe otra vez
