### ISSUE TITLE
help! i have an error ! (fixed)

### ISSUE THREAD

**Issue by MrJeffOfficial** [Jiiks/BetterDiscordApp#781]
ive tried running discord as a admin and still nothing 

A javascript error occured in the main process

Uncaught exception: 
TypeError: Cannot read property "isFocused" of null
 at WebContents. anonymous
(C:/Users/********/AppData/Roaming/discord/0.0.300/modules/discord_dekstop_core/core...:31)
at emitOne (events.js:96:13)
at WebContents.emit (event.js: 188:7)

**Comment by MrJeffOfficial** [comment]
no one is answering you basterds

**Comment by CallyyllaC** [comment]
Delete discord from /appdata/local and appdata/roaming
reinstall from their website
run bandaged discord as admin
worked for me when nothing else would

**Comment by mcclureski** [comment]
CallyllaC your solution did not work, the error still persists after reinstall

**Comment by Monomian** [comment]
How did you fixed it? Im having the same problem and I had this problem at the same time as you.

**Comment by RodjGaming** [comment]
This worked for me and I grabbed this from another GitHub: Go to your Task Manager and end this task: "igfxm module"/"igfxem module" or "In Game Manager"
