### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by OneShotCode** [Jiiks/BetterDiscordApp#784]
![discorderror](https://user-images.githubusercontent.com/38807977/39394671-01480b4c-4ad5-11e8-9d8a-ba404a6ffdca.JPG)

Error persists after reinstall of discord, running as admin, using BanagedBD.exe, removing only the corrupted part and let discord update it again didnt work at all. 

All on desktop. 

Any other known way of trouble shooting?

**Comment by DeadMasterBG** [comment]
Same problem
