### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by zhrprkp** [Jiiks/BetterDiscordApp#786]
![screenshot_128](https://user-images.githubusercontent.com/38815419/39398593-a7cee1f0-4b18-11e8-9eaf-e1afeccbf1cc.png)

**Comment by DeadMasterBG** [comment]
Use that: https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by zhrprkp** [comment]
This doesn't solve my problem. I tried Re-instail BD and discord many times
