### ISSUE TITLE
None of my plugins work and i'm showing offline

### ISSUE THREAD

**Issue by jlkjlkjkljkljlkjkljkljkl** [Jiiks/BetterDiscordApp#788]
I have a few plugins installed but none of them seem to show up or work.

For example i have the quoter plugin but the quote button doesn't show up. 

Also I'm not showing as online, My name does show up in the member list as online but when clicking on my name it shows me as offline and my spotify status doesn't show either. (Not entirely sure if this is better discord or just discord itself)

**Comment by DeadMasterBG** [comment]
Thats Discord side problem i think... there are several bugs at latest build

**Comment by exoboi14** [comment]
Yea I got it too... should be discord because of the latest build.
