### ISSUE TITLE
The newest version of Discord broke BD completely

### ISSUE THREAD

**Issue by Bernd-L** [Jiiks/BetterDiscordApp#790]
After reinstalling, instead of working better, the BD tab completely disappeared from the settings.

When starting Discord, the BD logo flashes a few times, but then disappears.

RIP

**Comment by intrnl** [comment]
You should try asking for support in the server.

This whole repo is deprecated.

**Comment by Wiress** [comment]
You need to install BandagedBetterDiscord. For whatever reason, the new update caused a bunch of errors in BD that need to be fixed. 

Link: https://github.com/rauenzi/BetterDiscordApp/releases/

**Comment by DOTD100** [comment]
Confirmed that downloading the latest version of BandagedBetterDiscord fixed the problem.

**Comment by xMikasa** [comment]
os x still not working with bangagedbetterdiscord

**Comment by Pacecca** [comment]
I went to this link: https://github.com/rauenzi/BetterDiscordApp/releases/ and downloaded it for mac.
I found it didn't work, but simply turning off the option to restart discord made it work! Hope this helps!
