### ISSUE TITLE
BetterDiscord is Broken (JavaScript Error)

### ISSUE THREAD

**Issue by Phaanta** [Jiiks/BetterDiscordApp#791]
Alright, so every once in a while, BetterDiscord just **breaks down.** Sometimes it takes me hours just to figure out the problem. This time though, the problem feels a big more drastic and unavoidable. As seen below:
![bandicam 2018-04-30 17-23-33-900](https://user-images.githubusercontent.com/35129124/39451166-b7792bd6-4c9b-11e8-93f6-22f5e0a4ae57.png)
I was wondering if there is any way to get around this, help would be appreciated, thank you.

**Comment by PLOliwier** [comment]
Q: "Betterdiscord doesn't work"
A: Changes were made in discord that haven't been fixed in the installer.
S: Use this for now: https://github.com/rauenzi/BetterDiscordApp/releases/
Linux users use this - https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by Phaanta** [comment]
Thank you, I realized just before you posted.
