### ISSUE TITLE
Won't reinstall and the support server is down

### ISSUE THREAD

**Issue by fastpager200** [Jiiks/BetterDiscordApp#792]
So, Discord updated today which naturally meant for a BD reinstall. Problem is, it's saying that "core.asar does not exist in modules/discord_desktop_core", so I tried going to the support server, only to find it was down due to an "outage", so here was the only place I could ask for help. How do I fix this?

**Comment by tehbasshunter** [comment]
You want to use the installer from here https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by intrnl** [comment]
Seems like you have a pretty old Discord version.

**Comment by tehbasshunter** [comment]
That too.

**Comment by fastpager200** [comment]
I already tried BandagedBetterDiscord and it had the same results. Also, if it updated this morning, how is it old? Did it down-date itself?

**Comment by StrikeExia** [comment]
Yeah bandagedBD isn't loading for me, it gets stuck on killing discord process

**Comment by komackie** [comment]
What do you mean running as admin?
