### ISSUE TITLE
Better Discord not working

### ISSUE THREAD

**Issue by ThotExterminatus** [Jiiks/BetterDiscordApp#794]
Closed Better Discord, came home to start it up and it opened normal Discord. Refreshing didn't work, neither did reinstalling. Tried to access Better Discord directly in the files and it gives me this message: 

![image](https://user-images.githubusercontent.com/38965096/39608044-9b26c222-4ef3-11e8-8f2f-0323f5040aed.png)

**Comment by intrnl** [comment]
It'd be better if you ask in our support servers first.
