### ISSUE TITLE
Bad with CSS

### ISSUE THREAD

**Issue by DestroyerShimakazeChan** [Jiiks/BetterDiscordApp#796]
Im bad at this (Never wrote code or anything before) 
![bdtrouble](https://user-images.githubusercontent.com/38992456/39654067-72b3c398-4fc1-11e8-9022-e507bf276d8b.png)

Only started having this problem after the most recent update; never had issues with the exact same text before

**Comment by DevilsLynAvenged** [comment]
.members-1bid1J > .members-1998pB

**Comment by DestroyerShimakazeChan** [comment]
Looks like thats what fixed it. Thanks for that.
Kind of curious though as to why that previous text worked before and not now, but whatever.
