### ISSUE TITLE
Bad token

### ISSUE THREAD

**Issue by guiltyakaii** [Jiiks/BetterDiscordApp#797]
![image](https://user-images.githubusercontent.com/38133500/39665939-21ed2090-509c-11e8-9794-7333a9019e62.png)
this error always happen and keep deleting BetterDiscord, is there a "counter" ?
(I've tried to uninstall discord a couple of times)

**Comment by DevilsLynAvenged** [comment]
https://cdn.discordapp.com/attachments/119918741516451840/414036980276527104/Betterdiscord_Folder_Opener.bat run this and delete the `user.json`

**Comment by guiltyakaii** [comment]
thanks
