### ISSUE TITLE
Mac settings doesn't work

### ISSUE THREAD

**Issue by vincentzirah** [Jiiks/BetterDiscordApp#798]
Hi, 
The mac settings aren't showed even if I install bandagedbd for mac. I try to reinstall discord, bandagedbd and betterdiscord several times without sucess;
Any fix ?

PS : I know that it's a problem for discord side since the last update but since it exists a fix for windows maybe it's possible to do something for mac :)

Have a nice day !

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBDInstaller_Mac.zip run this I believe it has been updated now

**Comment by vincentzirah** [comment]
I run this, reinstall betterdiscord and it doesn't work

**Comment by vincentzirah** [comment]
So  ?

**Comment by ixje** [comment]
fyi; the link above works for me for Discord 0.0.251

**Comment by deshario** [comment]
@DevilsLynAvenged  Link broken
