### ISSUE TITLE
BetterDiscord not loading

### ISSUE THREAD

**Issue by qmaz246** [Jiiks/BetterDiscordApp#799]
Tried to reinstall. I have NET 4.5. And no, the discord server is currently down so I cannot ask there.

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe did you use this, if not then run it

**Comment by qmaz246** [comment]
When i run BandagedBD.exe, it gives me this in the log:
`Searching for Discord core in: C:\Users\The EnQuinnridian\AppData\Roaming\discord\0.0.301.0\modules\discord_desktop_core
Located core.asar in: C:\Users\The EnQuinnridian\AppData\Roaming\discord\0.0.301.0\modules\discord_desktop_core
Killing Discord Processes
`

And Better Discord is still not working.
