### ISSUE TITLE
Severe lag since install

### ISSUE THREAD

**Issue by khionu** [Jiiks/BetterDiscordApp#80]
Everytime I use Ctrl+R.... well, I might as well just end Discord instead of using Ctrl+R. My computer is high-end for a laptop (http://iamtrue.net/khio-files/MySpecs.txt - DxDiag) and the resources are not even spiking like I would expect from lag, in fact, while this is going on, CPU for Discord alone was between 0.5-7.5%. Memory was less than 50%, SSD was barely active... and, while this has happened before install, it was only once every couple weeks. Now, this is guaranteed if I use Ctrl+R, and happens other times too.

If you don't have a solution, I would rather just remove it, as the functionality is really mostly limited to Cosmetics. As a Technic Moderator, I was hoping for tools like getting UserIDs...

**Comment by Jiiks** [comment]
Does this happen on all channels or only on the BetterDiscord general channel?

As for the user ids there is a api call here: https://github.com/Jiiks/BetterDiscordApp/blob/master/js/main.js#L1440

**Comment by khionu** [comment]
I've left the BetterDiscord server. This happens no matter where I am, in voice or not, no matter the server size, etc.

**Comment by Bluscream** [comment]
https://github.com/Bluscream/BetterDiscord-Plugins-and-Themes/blob/master/plugins/1_userinfo.js (Still WIP)

**Comment by Jiiks** [comment]
I'm unable to reproduce any lag. Have you tried turning all settings off and testing them 1 by 1 to see if anything in particular causes it?

**Comment by khionu** [comment]
I just updated to the latest and read the changelog.... there was a crash that was happening when people refreshed? There's a chance this was said issue, but somehow the errored exit never occurred?

Testing, issue seems to have been solved.

**Comment by Jiiks** [comment]
Yes there was an issue that caused bd to pretty much crash discord completely when discord reloaded or ctrl+r. Glad to hear it's fixed ;)

**Comment by khionu** [comment]
Mhm :smile_cat: 

Though @Bluscream ..... WIP? The button does nothing :P
I'll take this to your Issue tracker

**Comment by Bluscream** [comment]
Fixed in https://github.com/Bluscream/BetterDiscord-Plugins-and-Themes/commit/0dfec2df9712f022af43e7af11c00199d872a845.
