### ISSUE TITLE
BandagedBD Stuck and Support Server Down

### ISSUE THREAD

**Issue by Fubub** [Jiiks/BetterDiscordApp#800]
Hey all, I hadn't signed into my discord on my PC in about a week so of course I only find out today how screwy the new update made BD. I checked out the BandagedBD file but when I run it (from admin/normally) it always gets stuck on killing discord processes. And just my luck that the support server seems to be down. Was just wondering if anyone else either had a fix or was experiencing the same thing. 

Here is what BandagedBD looks like when it freezes up
![image](https://user-images.githubusercontent.com/39016817/39668875-da686dbc-50a8-11e8-82c7-b2036943ed7b.png)

**Comment by intrnl** [comment]
If you find that the Installer is stuck when trying to kill Discord processes, try moving it to another folder like your Desktop and running with or without administrator.

**Comment by DevilsLynAvenged** [comment]
and the server is down because of the server capacity
