### ISSUE TITLE
BetterDiscord not working!

### ISSUE THREAD

**Issue by ArkuDada** [Jiiks/BetterDiscordApp#802]
Everything seems to install correctly with no error.
I try reinstalling discord and BD. Nothing work.
Nothing is showing in the setting even after leaving it for a few minutes.
Also, I couldn't join the support server.

**Comment by chandelure9** [comment]
is there a link that will help for mac? ive tried the bandaged version but it doesnt help...

**Comment by VaporousCreeper** [comment]
What i have notice for that passed week when i'm the discord, almost every time i wake up and look at my server list that it goes down for a short time
