### ISSUE TITLE
How to fix better discord if its not working

### ISSUE THREAD

**Issue by Ritualx** [Jiiks/BetterDiscordApp#803]
Don't know if I should post this here but,
Open run win key + r type %appdata%/Discord and delete 0.0.301 file
Open discord again then download https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe and install it.

**Comment by chandelure9** [comment]
can you explain this for mac users?

**Comment by notcarksss** [comment]
BetterDiscord was broken with the new Discord update. BandagedBD does not work either.
This is a known issue at the moment and I'm sure that it is being fixed.

I'm having the same issue and I recently found this out.

**Comment by markthewolf90** [comment]
chandelure9, you really should figure it out yourself. People who use Windows will have to do the same thing to find out how to do it on Mac that you have to do anyways. (that being, use Google.) I really don't mean to be rude, but it just doesn't make sense to ask someone with a different operating system how to solve a problem relating to your operating system.

**Comment by DangerCow** [comment]
f

**Comment by TekOskYY** [comment]
it doesn`t working

**Comment by RedstonedLife** [comment]
BandagedBD worked for me

**Comment by JGriffin34432** [comment]
Yes it also worked for me.
