### ISSUE TITLE
how can I fix this? it's not showing me the background and the text and voice part is not working either

### ISSUE THREAD

**Issue by DaKurlzz25** [Jiiks/BetterDiscordApp#806]
![image](https://user-images.githubusercontent.com/39376815/40233294-16cdbe7c-5aab-11e8-814c-e798655621e8.png)

**Comment by DevilsLynAvenged** [comment]
.theme-dark .chat form {
   background-color: transparent;
}

**Comment by DaKurlzz25** [comment]
didn't work
