### ISSUE TITLE
Better discord not working even when I use bandaged BD

### ISSUE THREAD

**Issue by TheJollyDEV** [Jiiks/BetterDiscordApp#808]
![image](https://user-images.githubusercontent.com/31150975/40262566-3644b35c-5abd-11e8-9eb3-eafeed4c2eed.png)
Even when I use Bandaged BD when I open discord (Normal And Canary) It loads this and launches normal discord - Can I get some help?

**Comment by DevilsLynAvenged** [comment]
turn off the anti-virus and firewall and use a vpn

**Comment by TheJollyDEV** [comment]
what is a vpn

**Comment by TheJollyDEV** [comment]
Sorry I do not have a "VPN" and my anti-virus is very important I keep on at all times
