### ISSUE TITLE
HELP ME I'M ON LINUX AND IT'S NOT  WORKING

### ISSUE THREAD

**Issue by Hipmix** [Jiiks/BetterDiscordApp#809]
When i try and install 
charles@Charles-PC ~/BetterDiscordApp/Installers/Electron $ sudo ./node_modules/.bin/electron ./src
/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/electron[15363]: ../../vendor/node/src/async-wrap.cc:357:void node::SetupHooks(const FunctionCallbackInfo<v8::Value> &): Assertion `env->async_hooks_init_function().IsEmpty()' failed.
 1: node::Abort() [/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/libnode.so]
 2: 0x7f1e51ef3384 [/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/libnode.so]
 3: 0x7f1e51edd705 [/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/libnode.so]
 4: 0x7f1e51a3147a [/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/libnode.so]
 5: 0x7f1e51951b3c [/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/libnode.so]
 6: 0x7f1e51951234 [/home/charles/BetterDiscordApp/Installers/Electron/node_modules/electron/dist/libnode.so]
 7: 0x79cf48463d

I was following this how to: https://www.youtube.com/watch?v=h1R2NTX-6C8

**Comment by DevilsLynAvenged** [comment]
use this https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by Hipmix** [comment]
this happens 

charles@Charles-PC ~ $ sudo betterdiscordctl install -s /usr/share/discord
[sudo] password for charles: 
ERROR: Discord installation not found.
charles@Charles-PC ~ $
