### ISSUE TITLE
FrankerFaceZ Global Emotes Not Working

### ISSUE THREAD

**Issue by rezafouladian** [Jiiks/BetterDiscordApp#81]
Emotes on https://www.frankerfacez.com/channel/__ffz_global along with some other hidden global emotes not working.

**Comment by Jiiks** [comment]
Not all FFZ emotes are added, I'll add the global ones though.
Here's a list of all the emotes supported: http://betterdiscord.net/emotes/?ed=ffz&page=1&s=

**Comment by rezafouladian** [comment]
Thanks
