### ISSUE TITLE
:tl doesn't appear to work

### ISSUE THREAD

**Issue by mtcjayne** [Jiiks/BetterDiscordApp#810]
the :tl modifier does not appear to work, and I can't find where in the code this is implemented to take a look

**Comment by tehbasshunter** [comment]
According to the info channel on the server that's not a valid modifier. Only tr, bl, and br.

**Comment by mtcjayne** [comment]
Ah the top left emote doesn't need any special modifier?

**Comment by tehbasshunter** [comment]
Correct
