### ISSUE TITLE
The usual.. "Better Discord is loading...."

### ISSUE THREAD

**Issue by Tixx7** [Jiiks/BetterDiscordApp#811]
I installed Better Discord 1 month ago. I had problems but this BandagedBD thing fixed it for me. 
Now, something resetted many settings in different programs + made BD stop working. 
I tried to uninstall and install Discord and removed all plugins from BD but it shows me this
**"Better** **Discord** **is** **loading..."** message every time in the bottom right corner.

Error Message:

![error](https://user-images.githubusercontent.com/34872850/40454384-f3034362-5ee8-11e8-9238-e613a2a67fc0.PNG)

**Comment by rauenzi** [comment]
delete `bdsettings.json` and reload
