### ISSUE TITLE
Failed installation of BD

### ISSUE THREAD

**Issue by blenk312** [Jiiks/BetterDiscordApp#812]
So I decided to install better discord on my new laptop (yey)
I install it, check discord, and no better discord
I install it again, check discord, and no better discord
I wonder if i install it 69 times will i be able to put in plugins and thats it
I wonder if after 10 years I can install it and get themes
help

**Comment by rauenzi** [comment]
Try this https://github.com/rauenzi/BetterDiscordApp/releases/latest
