### ISSUE TITLE
JavaScript error when starting Discord with BetterDiscord installed

### ISSUE THREAD

**Issue by philipcina99** [Jiiks/BetterDiscordApp#814]
This started after a Discord update a little bit ago but now most of the time when I start my discord I get this JavaScript error that causes BetterDiscord to not work at all so its just vanilla discord. I've updated to the latest BandagedBD and everything as well. I saw someone else with the same problem as me posted already but that solution of disabling firewall and antivirus and using a vpn didnt work.
![image](https://user-images.githubusercontent.com/8158943/40571246-9483c5ba-6063-11e8-9e21-b2403cc6b588.png)
![image](https://user-images.githubusercontent.com/8158943/40571249-98caad1e-6063-11e8-8b77-be6926c49958.png)

**Comment by jasonhaxstuff** [comment]
#813 I fixed mine by deleting the `Appdata/Roaming/BetterDiscord` folder and reinstalling BetterDiscord.

**Comment by jasonhaxstuff** [comment]
Uninstall Discord, delete that folder I told you about, restart your computer, reinstall Discord and BandagedBD. Make sure to use the latest installer.

**Comment by philipcina99** [comment]
i did all that and it still didnt work. my clean install of discord ran without any issues but as soon as i installed betterdiscord the errors started popping up again, and they continued after installing bandagedbd as well

**Comment by jasonhaxstuff** [comment]
Don't install BD first, install BandagedBD right after installing Discord.

**Comment by philipcina99** [comment]
ok that still didnt work

**Comment by jasonhaxstuff** [comment]
gl

**Comment by philipcina99** [comment]
thanks for trying ig

**Comment by intrnl** [comment]
Make sure that the installer you're using actually says BandagedBD with a blue dog wearing a white bandana, if not, download from [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest)

**Comment by philipcina99** [comment]
Yes it was the latest version. I made sure of it and the previous person also told me to check to make sure it was the latest version as well.
