### ISSUE TITLE
BD Not working

### ISSUE THREAD

**Issue by Nekroo** [Jiiks/BetterDiscordApp#816]
Just dont working, Im using windows 10, when i install and launch discord, nothing changes

**Comment by itsMaxra** [comment]
Same Thing Here!

**Comment by DevilsLynAvenged** [comment]
use this installer and run it https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe and if it's stuck on killing process then run it on the desktop as admin

**Comment by itsMaxra** [comment]
now i can see the options but i put the css to the folder and when i go to change it shows nothing
![screenshot_640](https://user-images.githubusercontent.com/33780640/40861279-30238bd0-65f1-11e8-9fad-5f73ee0511cd.png)

**Comment by intrnl** [comment]
Try following the instructions in this [gist](https://gist.github.com/intrnl/d692ecdd86112c739945e957d7ab49f1#how-do-i-install-themes-and-plugins).

Once you're done, please close the issue, thanks!
