### ISSUE TITLE
BBD No ffz emote

### ISSUE THREAD

**Issue by 0196071** [Jiiks/BetterDiscordApp#817]
like the title says cant see ffz emotes in bandaged better discord.

**Comment by DevilsLynAvenged** [comment]
https://cdn.discordapp.com/attachments/280806472928198656/406142867749208064/emote_data.zip download this, then fully close discord and then put this in the betterdiscord folder and then reopen Discord

**Comment by intrnl** [comment]
Try following this, https://gist.github.com/intrnl/d692ecdd86112c739945e957d7ab49f1#discord-seems-to-be-giving-an-error-about-parseemotedata

**Comment by 0196071** [comment]
Where are those emotes suposed to be?
