### ISSUE TITLE
Betterdiscord not working at ALL

### ISSUE THREAD

**Issue by discordpro** [Jiiks/BetterDiscordApp#818]
so i loaded up betterdiscord installer and installed it and it doesn't even show up on discord
![image](https://user-images.githubusercontent.com/24377875/40881009-f6db07e2-6689-11e8-9957-c232f03f33b0.png)
does anyone know whats wrong?

**Comment by discordpro** [comment]
i selected the stable discord version and that is stable version
![image](https://user-images.githubusercontent.com/24377875/40881015-278de42c-668a-11e8-830e-7b2d2086b076.png)

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe use this and run it and if it's stuck on killing process then run it on the desktop as admin

**Comment by discordpro** [comment]
ok

**Comment by discordpro** [comment]
i will try that

**Comment by discordpro** [comment]
OH NVM

**Comment by discordpro** [comment]
IT JUST STARTED TO WORK

**Comment by discordpro** [comment]
now i have to open a new issue
._.

**Comment by intrnl** [comment]
Can you close this one then if you decide to open a new one?

**Comment by GE0NE** [comment]
I'm having this same issue. Trying to use BandagedBD, the installer is telling me 
core.asar does not exist in: C:\Users\{USERNAME}\AppData\Roaming\discord\0.0.299\modules\discord_desktop_core!
