### ISSUE TITLE
Betterdiscord emotes not showing

### ISSUE THREAD

**Issue by discordpro** [Jiiks/BetterDiscordApp#819]
so i got bd fixed now emotes dont show
![image](https://user-images.githubusercontent.com/24377875/40881092-72d7a7c2-668c-11e8-95ae-70e5f31a879d.png)

**Comment by discordpro** [comment]
this was fixed. i just had to wait

**Comment by intrnl** [comment]
Can you close this one then if it's fixed?

**Comment by discordpro** [comment]
how?

**Comment by intrnl** [comment]
![](https://pillow.is-my.store/0k4jVZA.png)
