### ISSUE TITLE
Betterdiscord not working

### ISSUE THREAD

**Issue by JoonaOfficial** [Jiiks/BetterDiscordApp#820]
It dosen't show that thing in the Settings place, i tried installing DiscordCanary, Discord PTD and BandagedBD. None of them worked. What should i do, oh billy. Don't blame me im Finnish.
![nayttokuva 48](https://user-images.githubusercontent.com/34300216/40889381-481fbf3c-676e-11e8-846c-f2b17194c993.png)

**Comment by ST6Daniel** [comment]
You can change language setting to english.

**Comment by JoonaOfficial** [comment]
That wasn't the problem m8

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe use this and run it and if it's stuck on killing process then run it on the desktop as admin

**Comment by Hi-ImKyle** [comment]
BandagedBD doesnt even work, gets stuck on Extracting core.asar

**Comment by PranavHiregange** [comment]
> https://github.com/rauenzi/BetterDiscordApp/releases/download/0.3.0i/BandagedBD.exe use this and run it and if it's stuck on killing process then run it on the desktop as admin

Thanks a lot! It's working for me.

**Comment by GE0NE** [comment]
I'm having this same issue. Trying to use BandagedBD, the installer is telling me
core.asar does not exist in: C:\Users\{USERNAME}\AppData\Roaming\discord\0.0.299\modules\discord_desktop_core!
Unable to continue installation.
