### ISSUE TITLE
Core.asar missing even with Zere's fork?

### ISSUE THREAD

**Issue by Rykoshet05** [Jiiks/BetterDiscordApp#821]
![image](https://user-images.githubusercontent.com/31403132/41021017-102b051c-69b9-11e8-81c8-47f408d2eb43.png)

I'm not even sure what's wrong anymore, I've tried both the regular and Bandaged version, I still get this error.

EDIT: Never mind, apparently my Discord version was just outdated. Please close this issue thanks ^^

**Comment by intrnl** [comment]
How about you close this yourself?
