### ISSUE TITLE
BD is not working after Discord update - using Linux

### ISSUE THREAD

**Issue by fhuewhd** [Jiiks/BetterDiscordApp#822]
I haven't used Discord since at least the end of April, having been away.  Today I loaded Discord and it insisted on installing an update before it would load.  After installing the update and trying again, I found BD was gone and is not in the Settings.  

I originally installed BD using https://github.com/bb010g/betterdiscordctl (BandagedBD doesn't appear to have a Linux installer of its own), so I tried using that to reinstall BD, but only got "ERROR: Discord installation not found.", which is ridiculous.

Any ideas please?  I can't go to the support server, as I have sensory issues and can't cope with Discord without BD to get rid of the animations!

**Comment by fhuewhd** [comment]
P.S.  I'm using Zorin 8 Linux, a variation of Ubuntu Trusty Tahr, and BDCTL says it's GitHub version 1.2.1 and accordinhg to Ubuntu Software Centre the version of Discord I've got is 0.0.5.

**Comment by intrnl** [comment]
that issue sounds like it belongs to betterdiscordctl repository and not this one.
by default, betterdiscordctl scans `/opt` for any discord install, and from what i've seen, some installation goes to `/usr/share` and you could change the scan directory by using `-s [directory]`

p.s. betterdiscordctl is like the semi official installer for bandagedbd

**Comment by fhuewhd** [comment]
That did the trick.  BD is now working fine and dandy.  Thanks very much!
