### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by MHOniiChan** [Jiiks/BetterDiscordApp#823]
I try to open BetterDiscord but it won't load

**Comment by gco360** [comment]
@MHOniiChan  use bbd if u are noy using 
if you just updated discord and BD isn't working, reinstall BetterDiscord with this link: 
https://github.com/rauenzi/BetterDiscordApp/releases/latest
If it's stuck on "Killing Discord Proccesses", move the installer to the desktop  or any other location then run it as administrator (Windows Only)
Linux users use this - https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by MHOniiChan** [comment]
Thx @gco360 . it worked

**Comment by gco360** [comment]
@MHOniiChan please follow me
