### ISSUE TITLE
Theme's Images not Working

### ISSUE THREAD

**Issue by AlphaVideo** [Jiiks/BetterDiscordApp#824]
Whenever I try to use a theme, it applies all it's changes except the background images. I've tried the fix:

/* fix not having a background image anymore */
.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
background: transparent !important;
}

But that seems to have not worked either.

**Comment by intrnl** [comment]
The issue you're having is not related to BetterDiscord.
Contact your theme's author about it.

**Comment by AlphaVideo** [comment]
This has happened to multiple themes already though, and from what I've seen nobody else is complaining about the theme I tried not working.

**Comment by intrnl** [comment]
Again, it's not related to BetterDiscord as it's the theme you're using and not BetterDiscord itself.
