### ISSUE TITLE
uninstall Mac OS

### ISSUE THREAD

**Issue by Fazorath** [Jiiks/BetterDiscordApp#827]
I have completely deleted discord from my Mac and usedSupport/discord[branch]/<version>/modules/discord_desktop_core and almost every other thing I could find and it just doesn't remove it just keeps coming back like a virus its slowing down my computer and its getting me worried

**Comment by Fazorath** [comment]
and now iw ent to join their server and it says it is down due to an outage and when to leave the server and its not letting me.  very good tool

**Comment by intrnl** [comment]
https://github.com/Jiiks/BetterDiscordApp/wiki/Uninstalling-BD
