### ISSUE TITLE
BandagedBD keeps on giving an error

### ISSUE THREAD

**Issue by DiamondSlashes** [Jiiks/BetterDiscordApp#830]
![image](https://user-images.githubusercontent.com/34142177/41308557-1d8d8b8e-6e74-11e8-86c7-4c30592f13f3.png)
This is what I get everytime I try installing BetterDiscording using it. I've tried the regular installer and that refuses to work. Whenever I install BetterDiscord with the regular installer, it never actually opens.
Better Discord Server says there is an 'outage'.
Any help?

**Comment by intrnl** [comment]
Redownload the installer, move it to another folder and try running it with or without administrator.

Next time, issues for BandagedBD goes to [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest)

**Comment by DiamondSlashes** [comment]
Thanks! Although, slightly irrelevant problem. I'm unable to access BD server for plugins because of an outage. Any help on that?

**Comment by intrnl** [comment]
This [gist](https://gist.github.com/intrnl/d692ecdd86112c739945e957d7ab49f1#file-pluginlist-md) provides a raw list of plugins
