### ISSUE TITLE
Discord PTD not working

### ISSUE THREAD

**Issue by XaxiMusic** [Jiiks/BetterDiscordApp#831]
I have it installed on mt PTB but I have no better discord settings or anything related to it.

**Comment by intrnl** [comment]
Download the installer from [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest), then move it to another folder.
Try running the downloaded installer with or without admin.

Next time, issues goes to [here](https://github.com/rauenzi/BetterDiscordApp/issues)
