### ISSUE TITLE
Error occurs whenever discord is being launched

### ISSUE THREAD

**Issue by Ztumpie905509** [Jiiks/BetterDiscordApp#832]
This error occurs whenever I start discord, no matter stable, canary or ptb.

![error](https://user-images.githubusercontent.com/38345383/41350085-86b0487e-6f44-11e8-8a76-de073cd42149.PNG)

**Comment by intrnl** [comment]
Use the installer from [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest), move it to another folder and then try running it with or without administrator rights.

I suggest you to close this issue and move it to [here](https://github.com/rauenzi/BetterDiscordApp/issues) as this repository is no longer maintained for the time being.

**Comment by gco360** [comment]
@Ztumpie905509

**Comment by intrnl** [comment]
Mentioning the user won't solve anything.
