### ISSUE TITLE
**READ THIS BEFORE CREATING A NEW ISSUE**

### ISSUE THREAD

**Issue by intrnl** [Jiiks/BetterDiscordApp#833]
Most of your issues could probably be solved if you use the installer from [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest)

If you do have an actual issue, please post it [here](https://github.com/rauenzi/BetterDiscordApp/issues/new) as this repository is no longer maintained for the time being.

**Comment by rauenzi** [comment]
Actually they're better going to one of the support servers as forks on GitHub don't have an issues page.

**Comment by jesse0319** [comment]
neither of the support servers are up half the time cause they're too big
