### ISSUE TITLE
Better Discord won't install

### ISSUE THREAD

**Issue by bumzo** [Jiiks/BetterDiscordApp#836]
Searching for Discord core in: C:\Users\pat\AppData\Roaming\Discord\0.0.297\modules\discord_desktop_core
core.asar does not exist in: C:\Users\pat\AppData\Roaming\Discord\0.0.297\modules\discord_desktop_core!
Unable to continue installation.

Anybody know a fix?

**Comment by gco360** [comment]
are u using bbd or bd

**Comment by gco360** [comment]
@bumzo

**Comment by gco360** [comment]
if not   Use this for now: https://github.com/rauenzi/BetterDiscordApp/releases/
Linux users use this - https://gist.github.com/ObserverOfTime/d7e60eb9aa7fe837545c8cb77cf31172

**Comment by bumzo** [comment]
i figured it out thanks

**Comment by gco360** [comment]
Follow up
