### ISSUE TITLE
Better Discord Not Working at all

### ISSUE THREAD

**Issue by Likeabozz123** [Jiiks/BetterDiscordApp#837]
My better discord doesn't show any of its features inside of settings and when I try to install it from other versions it still doesn't work. I tried doing the BanadagedBD thing, but it would get stuck on the extracting core.

**Comment by DevilsLynAvenged** [comment]
Use this and choose the bandagedBD Windows installer(or bandagedBDMac Installer if on Mac)

**Comment by intrnl** [comment]
Clearly you didn't read that issue with the names in all caps and surrounded with three asterisks, didn't you?

You're not going to get much help other than some copypaste here, this repository has long been unmaintained.

[This is the appropriate place to create new issues](https://github.com/rauenzi/BetterDiscordApp/issues/new)
