### ISSUE TITLE
GoogleTranslator plugin doesn't work

### ISSUE THREAD

**Issue by iishoku** [Jiiks/BetterDiscordApp#838]
The plugins shows up on the plugin page on discord. Everytime i want to 'start' the plugin with clicking on it and close the window its disabled again. can someone tell me what to do?

**Comment by DevilsLynAvenged** [comment]
Try telling the plugin developer the problem

**Comment by intrnl** [comment]
Clearly you didn't read that issue with the names in all caps and surrounded with three asterisks, didn't you?

You're not going to get much help other than some copypaste here, this repository has long been unmaintained.

[This is the appropriate place to create new issues](https://github.com/rauenzi/BetterDiscordApp/issues/new)
