### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Fr3akyBanana** [Jiiks/BetterDiscordApp#839]
Hello, I have installed BetterDiscord but with the setting | User Settings, BetterDiscord or so is not displayed.

**Comment by DevilsLynAvenged** [comment]
Use this and choose the bandagedBD Windows installer(or bandagedBDMac Installer if on Mac) https://github.com/rauenzi/BetterDiscordApp/releases/

**Comment by intrnl** [comment]
Clearly you didn't read that issue with the names in all caps and surrounded with three asterisks, didn't you?

You're not going to get much help other than some copypaste here, this repository has long been unmaintained.

[This is the appropriate place to create new issues](https://github.com/rauenzi/BetterDiscordApp/issues/new)
