### ISSUE TITLE
Better discord settings wont appear

### ISSUE THREAD

**Issue by ImSoMad** [Jiiks/BetterDiscordApp#844]
I installed better discord, Opened it, installed it, and then it opened my discord. When i click settings, none of the BetterDiscord Settings are there. I tried restarting it and it wont work. another thing is that the better discord servers are shut down and i cant ask for help there. is better discord under maintainence??? can someone pls let me know.

**Comment by ImSoMad** [comment]
also i tried re-instaling better discord many times. The problem wont fix.

**Comment by intrnl** [comment]
This repository is deprecated, if you want to make an issue, post it [here](https://github.com/rauenzi/BetterDiscordApp/issues/new)

Make sure that your installer says BandagedBD with a blue dog wearing a white bandana, if not, grab the installer [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest)
