### ISSUE TITLE
PLs help.

### ISSUE THREAD

**Issue by aguyagain** [Jiiks/BetterDiscordApp#845]
![image](https://user-images.githubusercontent.com/40712986/42123336-42a68bac-7c1e-11e8-9d7d-404741b5809c.png)

its just stuck on this :(

**Comment by DevilsLynAvenged** [comment]
Wrong installer use this and run it  https://github.com/rauenzi/BetterDiscordApp/releases/ and if it's stuck on killing process then run it on the desktop as admin
