### ISSUE TITLE
Better Discord not working [Javascript errors at discord startup]

### ISSUE THREAD

**Issue by Tixx7** [Jiiks/BetterDiscordApp#846]
![error2](https://user-images.githubusercontent.com/34872850/42130289-8a4e2eca-7ce0-11e8-8b09-11aaf5d05247.PNG)
![error3](https://user-images.githubusercontent.com/34872850/42130291-8ccf79a6-7ce0-11e8-9798-b7097442e7da.PNG)

had issues with bd before but I fixed it.
the 2 attached errors above appeared after a few days, the error messages somehow _disappeared_ again after a few days but 2 days later they _appeared again_, idk what to do :( 

### **ALSO IMPORTANT:**

-  No "BD is loading" in the bottom right corner 
-  BD _**works**_ in windows _**safe mode**_
-  No errors in Discord console

PS: feel free to ask me for logs

**Comment by intrnl** [comment]
This repository is deprecated, if you'd like to make a new issue anyway, head [here](https://github.com/rauenzi/BetterDiscordApp/issues/new)

Make sure that you are running BandagedBD, installer is [here](https://github.com/rauenzi/BetterDiscordApp/releases/latest)

**Comment by Tixx7** [comment]
@intrnl worked for me [c:] because I only had an older version of bandaged bd.

But if it stops working again [it probably will but i hope not  :c] i will post this issue [if its the same error and so on] in the new repository.

**Comment by intrnl** [comment]
You should also close this issue now that it's resolved.
