### ISSUE TITLE
Unexpected Token in JSON at Position 0

### ISSUE THREAD

**Issue by OfficerItalian** [Jiiks/BetterDiscordApp#848]
When I started up discord, it ended up saying this error message. Suggestions?

![](https://image.prntscr.com/image/OpsSb0JVRcWsQROts3qsLQ.png)

**Comment by DevilsLynAvenged** [comment]
Run this. Fully close discord then delete user.json in the folder that opens.
https://cdn.discordapp.com/attachments/119918741516451840/414036980276527104/Betterdiscord_Folder_Opener.bat

**Comment by intrnl** [comment]
This repository is deprecated, new issues should go to [here](https://github.com/rauenzi/BetterDiscordApp/issues)
