### ISSUE TITLE
better discord

### ISSUE THREAD

**Issue by lambchopsss** [Jiiks/BetterDiscordApp#849]
it says this discord_desktop_core
core.asar does not exist  but i dont know what to do.

**Comment by intrnl** [comment]
Make sure that your Discord is up to date.

This repository is deprecated, if you still want to continue this issue you should go to [here](https://github.com/rauenzi/BetterDiscordApp/issues/new)

**Comment by lambchopsss** [comment]
what do you mean by make sure its up to date and repository?

**Comment by lambchopsss** [comment]
its missing an asar thing

**Comment by intrnl** [comment]
Your Discord is out of date.

**Comment by lambchopsss** [comment]
oh thanks i got it!
