### ISSUE TITLE
core.asar does not exist

### ISSUE THREAD

**Issue by MachineGunX** [Jiiks/BetterDiscordApp#851]
I tried to instal BetterDiscord several times. I downloaded the original installer, not working. The updated installer, not working. And now with the BandagedBD, I still get the issue "core.asar does not exist in" 
Please help

**Comment by rauenzi** [comment]
Update your discord, it's likely below version 0.0.300

**Comment by MachineGunX** [comment]
I know this

**Comment by rauenzi** [comment]
right click the tray icon and select check for updates or reinstall discord

**Comment by MachineGunX** [comment]
Thank you!
