### ISSUE TITLE
BetterDiscord for canary wont work

### ISSUE THREAD

**Issue by ErtasVideos** [Jiiks/BetterDiscordApp#852]
i install betterdiscord and it wont start at all

**Comment by DevilsLynAvenged** [comment]
https://github.com/rauenzi/BetterDiscordApp/releases/ try this

**Comment by intrnl** [comment]
This repository is deprecated, if you want to continue with this issue, close this one and make another one [here](https://github.com/rauenzi/BetterDiscordApp/issues/new)
