### ISSUE TITLE
Where's The BetterDiscord Setting In Setings

### ISSUE THREAD

**Issue by fhbncghdytgf** [Jiiks/BetterDiscordApp#854]
![screenshot_4](https://user-images.githubusercontent.com/24204274/43030568-71a73698-8cc4-11e8-8f8c-8131f2fb7d30.png)
It Cant Be!!!

**Comment by fhbncghdytgf** [comment]
I install Better Discord And Where is It

**Comment by DevilsLynAvenged** [comment]
look at faq question 2 in the betterdiscord server
