### ISSUE TITLE
Custom CSS to hide blocked messages is not working (Use of !important)

### ISSUE THREAD

**Issue by CrestfallenWarrior** [Jiiks/BetterDiscordApp#860]
![untitled](https://user-images.githubusercontent.com/31358572/43678419-899365d0-97e9-11e8-927a-c8734a3a68d2.jpg)

**Comment by intrnl** [comment]
That's a warning, not an error. Also, that class is non-existent now.

This isn't an issue with BetterDiscord, so instead you should head to the support server for issues like this.

**Comment by CrestfallenWarrior** [comment]
Doesn't custom CSS only work with BetterDiscord?

**Comment by cyntalan** [comment]
It looks like a recent update to Discord appears to have broken something about this aspect of the Custom CSS, as stated above. Script does not hide the element as intended. Did they perhaps change the description of the message group in some manner?

**Comment by boogersarecool** [comment]
This works

div[class^="messageGroupBlocked-"], div[class*=" messageGroupBlocked-"] {
display: none;
}

**Comment by CrestfallenWarrior** [comment]
Thank you.

**Comment by designgears** [comment]
This will hide the message and add a line back in so it's completely seamless. 

`div[class^="messageGroupBlocked-"], div[class*=" messageGroupBlocked-"] {
    height: 0;
    line-height: 0;
    overflow: hidden;
    margin: 0 20px 0 20px;
    border-width: 1px 0 0 0;
    border-color: #3E414A !important;
}`

**Comment by wefalltomorrow** [comment]
[**@designgears**](https://github.com/designgears) commented on [23 Apr 2019, 11:20 GMT+10](https://github.com/Jiiks/BetterDiscordApp/issues/860#issuecomment-485606783 "2019-04-23T01:20:54Z - Replied by Github Reply Comments"):
> This will hide the messages blocked and add a line back in so it's completely seamless.
> 
> div\[class^="messageGroupBlocked-"\], div\[class\*=" messageGroupBlocked-"\] {  
> height: 0;  
> line-height: 0;  
> overflow: hidden;  
> margin: 0 20px 0 20px;  
> border-width: 1px 0 0 0;  
> border-color: #3E414A !important;  
> }

Thanks a ton for this!

**Comment by wefalltomorrow** [comment]
Is there a way to hide the "New Messages" line as well that still appears from blocked users? 

https://i.imgur.com/aDb9H14.png

**Comment by miguelenam** [comment]
![Screenshot_169](https://user-images.githubusercontent.com/45132978/73718500-76ace780-46fb-11ea-8575-22bdc42a8728.png)

latest discord update broke the it

**Comment by billboytm** [comment]
Gotta love how they patch things just to cause grief to the people that improve their shitty application on their own time.

**Comment by zedabeta** [comment]
`div[class^="blockedSystemMessage-"], div[class*="blockedSystemMessage-"] {
display: none;
}`

Hey guys, they changed the div for this, so now you should use the above div to block the message group.

**Comment by billboytm** [comment]
> `div[class^="blockedSystemMessage-"], div[class*="blockedSystemMessage-"] { display: none; }`
> 
> Hey guys, they changed the div for this, so now you should use the above div to block the message group.

Thanks, but there's now a transparent gap where the original "1 blocked message" usually is. The messages aren't being readjusted properly.
![off](https://user-images.githubusercontent.com/60676611/73901859-9b1ed600-4859-11ea-8d0a-5a6450bbb338.PNG)
![on](https://user-images.githubusercontent.com/60676611/73901861-9b1ed600-4859-11ea-9327-2a6760a4f00c.PNG)

**Comment by zedabeta** [comment]
`div[class^="container-"]{ min-height: 0; }
div[class^="blockedSystemMessage-"], div[class*="blockedSystemMessage-"] { display: none; }`
Pretty simple fix for that, make it so that all of the containers no longer have a minimum height.

**Comment by billboytm** [comment]
Sweet, thanks. I don't code so it's not simple, but I'm glad you do and are willing to address the situation so quickly :)

**Comment by Burday** [comment]
I can't comprehend why Discord refuses to add this and turns people to Bandaged and anti ToS shit like that. It's something that you can easily do with the basics of CSS and make it look flawless, yet they claim they aren't able to sort it out when they have direct access to their very own code. Clowns.

**Comment by zedabeta** [comment]
div[class^="wrapper-"]{ min-height: 0; } might now be needed for compact mode, just fyi

**Comment by LeifLioness** [comment]
```
div[class^="container-"]{ min-height: 0; }
div[class^="blockedSystemMessage-"], div[class*="blockedSystemMessage-"] { 
    
    display: none; 
}

div[class^="groupStart-"], div[class^="da-groupStart"] {
    display: none;
}
```

I had to add the bottom part in order to hide everything after the latest update, but it is working well for me.

**Comment by PlsBogs** [comment]
Discord doesn't load now after trying to edit the CSS on the newest version... Anyone else?

**Comment by LeifLioness** [comment]
It happened to me, although I'm not sure whether or not that is the cause.
it's related to

**Comment by Jexus11** [comment]
BetterDiscord doesn't keep any of those custom CSS when I leave the configuration page. I have the error "^= are slow".
Anyone else ?

**Comment by zedabeta** [comment]
Still works for me, btw if you want a super compact mode (zero padding between compact messages) then you can go with a `.compact-T3H92H.wrapper-2a6GCs, .cozy-3raOZG.wrapper-2a6GCs{padding-top: 0; padding-bottom: 0;}`

**Comment by BrazenFox5** [comment]
> Doesn't custom CSS only work with BetterDiscord?

It literally says "BetterDiscordApp," bruh.

**Comment by Aholicknight** [comment]
Does this still work as of December 2021?

**Comment by KaiDevrim** [comment]
FourWolves's code works for me
