### ISSUE TITLE
Double Click Edit plugin bug

### ISSUE THREAD

**Issue by dumbusernameidk** [Jiiks/BetterDiscordApp#862]
When double clicking on a message with multiple lines in it usually lets say you sent 5-6 messages clicking on the bottom one sends your scroll bar very high up. I don't know what exactly causes it but it happens even after restarting discord or re-installing the plugin.

**Comment by qwerasd205** [comment]
I am unable to reproduce this bug. I am aware that for a short period of time there was an issue with Discord which caused this bug when hitting the up arrow to edit a message. If you're sure you're on the latest version of Discord then I suggest trying to disable any themes you have on and seeing if that changes the behavior. If so then this is an issue with your theme.

**Comment by qwerasd205** [comment]
I am able to reproduce the issue with editing messages behaving poorly in Beard's Material Theme. I suggest reporting the bug to him.
