### ISSUE TITLE
.js error on start of Discord (MAC)

### ISSUE THREAD

**Issue by fonic-artes** [Jiiks/BetterDiscordApp#87]
After installing the most recent BD on MAC, when trying to start Discord I get a .js error.

**Comment by Jiiks** [comment]
Can you post the error?

**Comment by fonic-artes** [comment]
install.sh ; exit;
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/user/index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
logout

**Comment by Jiiks** [comment]
Try running the index.js directly with: node index.js

**Comment by Cylias** [comment]
I got the error that OP recieved when I ran the .sh file. I attempted to run "node index.js" directly, but got almost the exact same error:

~~~
module.js:328
    throw err;
    ^

Error: Cannot find module '/Users/[MyUserName]/index.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
~~~~

I installed the js module at https://nodejs.org/en/, and I get this message at the end:
~~~~
Node.js was installed at

   /usr/local/bin/node

npm was installed at

   /usr/local/bin/npm

Make sure that /usr/local/bin is in your $PATH.
~~~

Does this message imply I can fix this issue by just moving the index.js file or is there more to this?

Thanks for the assistance.

**Comment by Jiiks** [comment]
Use absolute paths

**Comment by Cylias** [comment]
I'm not very knowledgable about Mac filesystems. What do you mean "use absolute paths", because google's explanation is vague at best.

**Comment by Jiiks** [comment]
Like: node.js "fullpathtoindex.js"

**Comment by Cylias** [comment]
So, I attempted to do a command and this occurred:

"MAC NAME":~ "USERNAME"$ /usr/local/bin/node
> node index.js
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:221:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
> 

So is there something I'm doing wrong?

I also tried downloading the binary files and running the installer while they were in the same folder. I encountered the same folder.

Sorry for the extremely noobish questions, but would it be possible to put up a video or something to show how one installs this?

I apologize for the inconvenience and thank you for the assistance! : )

**Comment by avinashimanshu** [comment]
![node](https://cloud.githubusercontent.com/assets/11608999/12995746/db7124d0-d17d-11e5-9f70-779e31777cac.JPG)

Remove node and npm from your computer and install again.

For Video Installation please go through https://docs.npmjs.com/getting-started/installing-node.
This contains the steps and also the complete documentation.
I hope you were asking about this.

**Comment by avinashimanshu** [comment]
Remove node and npm from your computer and install again.

For Video Installation please go through https://docs.npmjs.com/getting-started/installing-node.
This contains the steps and also the complete documentation.
I hope you were asking about this.
