### ISSUE TITLE
Better discords help servers

### ISSUE THREAD

**Issue by BetaTester0704** [Jiiks/BetterDiscordApp#885]
I keep getting kicked from the better discord help servers for inactivity (I think I'm not sure why) and I need help currently.
it keeps throwing error messages on start up and I cant get to the help servers because the link is invalid.

Please help me.

**Comment by CorbsEditor** [comment]
One: The server is temporary in an outage a lot because they're so many members in the server.
Two: If the link is invalid, that is a sign that you're banned or the invite is actually invalid 🤔

**Comment by BetaTester0704** [comment]
ive tried joining both but they are both invalid.
ive tried joining multiple times.

I don't believe I was banned from them since I haven't done anything in them.
ive asked a few questions in both help servers and that's it.

**Comment by CorbsEditor** [comment]
BetterDiscord: https://discordapp.com/invite/0Tmfo5ZbOR8bKrMJ
BetterDiscord2: https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by BetaTester0704** [comment]
How can I prevent myself from being kicked from the server.
I'm learning javascript and may be making a plugin and would like to make sure I'm still there

**Comment by VaporousCreeper** [comment]
The only way to do that is to get a role. That simple

**Comment by CorbsEditor** [comment]
not really come on
