### ISSUE TITLE
BetterDiscord does not work with the lastest version

### ISSUE THREAD

**Issue by QuapiL1** [Jiiks/BetterDiscordApp#891]
Since the latest update by discord, bd no longer works.

**Comment by TheLonelyWolf1** [comment]
Did you tried the latest version? Find it here: https://github.com/rauenzi/BetterDiscordApp/releases

**Comment by AlIenPete** [comment]
Works just fine for me. Try reinstalling it.

**Comment by HigeMynx** [comment]
Reinstalled Discord and Better Discrod. Dose not work for me.
Installing Better Discord doesn't change anything in Discord.
app-0.0.305 and BetterDiscord Release 0.3.0

**Comment by MasicoreLord** [comment]
Also next time use https://github.com/rauenzi/BetterDiscordApp/issues for issues, this project is inactive, while the one over there is an actively maintained fork.
