### ISSUE TITLE
Themes not loading, crashing Discord

### ISSUE THREAD

**Issue by ShellUserMyDude** [Jiiks/BetterDiscordApp#894]
Opening Discord doesn't load the theme and leaving it open causes it to loop crash due to an attempt to load the theme.

**Comment by Viylas** [comment]
What theme exactly?

**Comment by ShellUserMyDude** [comment]
https://codedotspectra.github.io/bdthemegenerator/base_neutron.html

**Comment by ShellUserMyDude** [comment]
update: tried multiple themes none of which worked

**Comment by DevilsLynAvenged** [comment]
screenshot the theme folder

**Comment by ShellUserMyDude** [comment]
apparently it was a discord update, they fixed it as of now
