### ISSUE TITLE
BTTV api and 3rd party Twitch api for sub emotes and global emotes

### ISSUE THREAD

**Issue by jonesdj1** [Jiiks/BetterDiscordApp#9]
https://twitchemotes.com/apidocs
for twitch emotes
https://api.betterttv.net/emotes
for bttv emotes

hope you can add sub emotes and make it so you use the twitch api for global emotes so it auto updates emotes!

**Comment by Jiiks** [comment]
Sub emotes are already added i just haven't updated the lists.
Next version will use twitchemotes.com apis(i didn't use them before since they have tons of data i don't need)

**Comment by Candunc** [comment]
Is there any timeline on when this is going to be implemented, and will there be a server-specific config to restrict emoticons?

**Comment by Jiiks** [comment]
Was implemented in 0.1.5 and no since it's all client side.
I can add a user-specific config though.
