### ISSUE TITLE
BetterDiscord crashes discord

### ISSUE THREAD

**Issue by SquidPlayZYT** [Jiiks/BetterDiscordApp#907]
i recently re installed discord and opened it to check my dms and all that before downloading betterdiscord, it was running completely fine before i installed better discord and once i installed better discord it started crashing when discord loaded up. any way to fix this?

**Comment by rauenzi** [comment]
Did you install BandagedBD or the old BetterDiscord?

**Comment by SquidPlayZYT** [comment]
holdon ill send the link that i downloaded it from

**Comment by SquidPlayZYT** [comment]
https://github.com/JsSucks/BetterDiscordApp/releases/tag/2.0.0-beta.6

**Comment by SquidPlayZYT** [comment]
i had installed BetterDiscord_0.3.0_win.zip

**Comment by SquidPlayZYT** [comment]
![image](https://user-images.githubusercontent.com/33473322/62754937-880c8400-ba37-11e9-8906-8953f9f7e6a7.png)

**Comment by SquidPlayZYT** [comment]
i click the logo in the corner and that pops up

**Comment by SquidPlayZYT** [comment]
i havent used BetterDiscord in a while and i dont know if that is a recent type

**Comment by DevilsLynAvenged** [comment]
https://0x71.cc/bd/guide/ Download BetterDiscord from here

**Comment by SquidPlayZYT** [comment]
lmao i got it to work like 3 hours later
