### ISSUE TITLE
Theme not loading fully

### ISSUE THREAD

**Issue by Hearthen** [Jiiks/BetterDiscordApp#912]
So I woke up one day, and my BD theme wasn't loading. I tried basically everything. The theme only loads for chat backgrounds now, instead of every part, while it still says it's loaded. Any fixes? (Or is this just a Discord update?)

**Comment by ToxicMethASS** [comment]
as stated on the betterdiscord server, this is because of the new update discord released. all you can do is wait for the theme/plugin devs to fix their themes for the new classes introduced in the new discord

**Comment by Hearthen** [comment]
aight thanks

**Comment by VasVadum** [comment]
I installed BetterDiscord today, and I can't even use custom CSS, it just doesn't do anything... Is this related to the fact that BetterDiscord hasn't been updated yet?
