### ISSUE TITLE
All plugins are not working

### ISSUE THREAD

**Issue by RapidGamer** [Jiiks/BetterDiscordApp#918]
I have a lot of plugins and they all are not working for me. I've tried unloading and reloading the plugins and they just do not work at all.

**Comment by abyssnetserver** [comment]
It could be to do with an issue a few other people are having where all of DevilBro's plugins have broken somehow, maybe wait it out?

**Comment by RapidGamer** [comment]
Thank you for telling me that, I just found out as well, so I guess there’s nothing in our power
