### ISSUE TITLE
BetterDiscord not loading (11/5/19)

### ISSUE THREAD

**Issue by sarcasticdrank** [Jiiks/BetterDiscordApp#922]
Something happened about a week ago and my BetterDiscord randomly stopped working. Now all I have is a flashing "B" in the bottom right corner of Discord telling me that "BandagedBD is loading". I tried uninstalling, repairing, uninstalling discord, etc. Nothing's worked.

**Comment by DevilsLynAvenged** [comment]
Then it's probably your internet that is preventing BandagedBD from loading or you downloaded a plugin that is not supported

**Comment by LaPingas** [comment]
the same goes for me atm. can't get it to work whatsoever

**Comment by SwiddisZwei** [comment]
Same here. Here's the log after a fresh reinstall of both BandagedBD and Discord.

```
[INF][11/8/2019, 4:58:16 PM] Hooking dom-ready
[INF][11/8/2019, 4:58:18 PM] Hooked dom-ready
[INF][11/8/2019, 4:58:18 PM] Getting updater
[INF][11/8/2019, 4:58:18 PM] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/injector
[INF][11/8/2019, 4:58:18 PM] Getting version from: https://cdn.statically.io/gh/rauenzi/BetterDiscordApp/1434e5391f87759f5455293bcebf7b6aee9fceb1/betterdiscord/config.json
[INF][11/8/2019, 4:58:18 PM] Latest Version: 0.3.2
[INF][11/8/2019, 4:58:18 PM] Getting commit hash
[INF][11/8/2019, 4:58:18 PM] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/master
[INF][11/8/2019, 4:58:19 PM] 0b97303051b717a8307bc31cc5b422cac7784bc9
[INF][11/8/2019, 4:58:19 PM] Using hash: 0b97303051b717a8307bc31cc5b422cac7784bc9
[INF][11/8/2019, 4:58:19 PM] Loading
[INF][11/8/2019, 4:58:19 PM] Loading Resource (//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js)
[INF][11/8/2019, 4:58:19 PM] Loading Resource (//cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/0b97303051b717a8307bc31cc5b422cac7784bc9/css/main.min.css)
[INF][11/8/2019, 4:58:19 PM] Loading Resource (//cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/0b97303051b717a8307bc31cc5b422cac7784bc9/js/main.min.js)
[INF][11/8/2019, 4:58:19 PM] Starting Up
```

**Comment by Nulled2117** [comment]
> Same here. Here's the log after a fresh reinstall of both BandagedBD and Discord.
> 
> ```
> [INF][11/8/2019, 4:58:16 PM] Hooking dom-ready
> [INF][11/8/2019, 4:58:18 PM] Hooked dom-ready
> [INF][11/8/2019, 4:58:18 PM] Getting updater
> [INF][11/8/2019, 4:58:18 PM] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/injector
> [INF][11/8/2019, 4:58:18 PM] Getting version from: https://cdn.statically.io/gh/rauenzi/BetterDiscordApp/1434e5391f87759f5455293bcebf7b6aee9fceb1/betterdiscord/config.json
> [INF][11/8/2019, 4:58:18 PM] Latest Version: 0.3.2
> [INF][11/8/2019, 4:58:18 PM] Getting commit hash
> [INF][11/8/2019, 4:58:18 PM] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/master
> [INF][11/8/2019, 4:58:19 PM] 0b97303051b717a8307bc31cc5b422cac7784bc9
> [INF][11/8/2019, 4:58:19 PM] Using hash: 0b97303051b717a8307bc31cc5b422cac7784bc9
> [INF][11/8/2019, 4:58:19 PM] Loading
> [INF][11/8/2019, 4:58:19 PM] Loading Resource (//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js)
> [INF][11/8/2019, 4:58:19 PM] Loading Resource (//cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/0b97303051b717a8307bc31cc5b422cac7784bc9/css/main.min.css)
> [INF][11/8/2019, 4:58:19 PM] Loading Resource (//cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/0b97303051b717a8307bc31cc5b422cac7784bc9/js/main.min.js)
> [INF][11/8/2019, 4:58:19 PM] Starting Up
> ```
> 
> Edit: I was able to fix it by changing the interface language to German, then back to English.

Damn thanks that fixed it for me man :P
