### ISSUE TITLE
11/12/19 BandagedBD no longer works

### ISSUE THREAD

**Issue by EnderShadowborne** [Jiiks/BetterDiscordApp#923]
I've done multiple repairs and reinstalls, nothing seems to work, fresh reinstalls, everything I could do. Any updates? Or anything?

**Comment by Danfun64** [comment]
I have the same issue. It was working earlier today, then I restarted my computer and suddenly it didn't work.

**Comment by Takka16** [comment]
I can definitely relate, It was working just fine till like 30 minutes ago, discord looks totally normal, in the left bar of the menu. I can't see theme or any tab that BandageBD adds

**Comment by deanB3AN** [comment]
Noticed the same thing happened to mine this morning. Tried uninstalling and reinstalling Discord and BandagedBD but to no success. I start Discord and BetterDiscord just never shows up. 
Wondering if it's an issue with a Discord update?

**Comment by Danfun64** [comment]
I have no affiliation with BandagedBD whatsoever, but I looked in the BetterDiscord2 Discord group and it appears that it's a known issue and DevilsLynnAvenged/ShadowDevilsAvenged has provided a temp fix. Here is their posts.

`For Mac Users Go To:
Applications > Discord > Right Click on Discord and then click on Show Package Contents > Contents > Resources > app > better discord > index.js and change 5000 to 3889 in the “Object.keys(req.c).length < 5000) part `

![image](https://user-images.githubusercontent.com/4473635/68708626-17a75e80-0562-11ea-98e5-25cd94e07a7b.png)

`This is for Linux users 
download bdctl from here https://raw.githubusercontent.com/bb010g/betterdiscordctl/temp-fix/betterdiscordctl and run its update command`

and for Windows users,
`Incase anyone can't wait for BBD to be fixed, or still want to work on their plugins/themes:
go to
%localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
Change 5000 to 3889
Save file
Restart Discord client

Screenshot of where you should change the value: `
![image](https://cdn.discordapp.com/attachments/280806472928198656/643908023265394728/unknown.png)

**Comment by EnderShadowborne** [comment]
> I have no affiliation with BandagedBD whatsoever, but I looked in the BetterDiscord2 Discord group and it appears that it's a known issue and DevilsLynnAvenged/ShadowDevilsAvenged has provided a temp fix. Here is their posts.
> 
> `For Mac Users Go To: Applications > Discord > Right Click on Discord and then click on Show Package Contents > Contents > Resources > app > better discord > index.js and change 5000 to 3889 in the “Object.keys(req.c).length < 5000) part `
> 
> ![image](https://user-images.githubusercontent.com/4473635/68708626-17a75e80-0562-11ea-98e5-25cd94e07a7b.png)
> 
> `This is for Linux users download bdctl from here https://raw.githubusercontent.com/bb010g/betterdiscordctl/temp-fix/betterdiscordctl and run its update command`
> 
> and for Windows users,
> ` Incase anyone can't wait for BBD to be fixed, or still want to work on their plugins/themes:
> go to
> %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> Change 5000 to 3889
> Save file
> Restart Discord client
> 
> Screenshot of where you should change the value: `
> ![image](https://camo.githubusercontent.com/f2f0d5abc0b7a7acddd5c3f03e2728b207391324/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3238303830363437323932383139383635362f3634333930383032333236353339343732382f756e6b6e6f776e2e706e67)

And then I restart Discord, right?

**Comment by master3395** [comment]
> > I have no affiliation with BandagedBD whatsoever, but I looked in the BetterDiscord2 Discord group and it appears that it's a known issue and DevilsLynnAvenged/ShadowDevilsAvenged has provided a temp fix. Here is their posts.
> > `For Mac Users Go To: Applications > Discord > Right Click on Discord and then click on Show Package Contents > Contents > Resources > app > better discord > index.js and change 5000 to 3889 in the “Object.keys(req.c).length < 5000) part `
> > ![image](https://user-images.githubusercontent.com/4473635/68708626-17a75e80-0562-11ea-98e5-25cd94e07a7b.png)
> > `This is for Linux users download bdctl from here https://raw.githubusercontent.com/bb010g/betterdiscordctl/temp-fix/betterdiscordctl and run its update command`
> > and for Windows users,
> > ` Incase anyone can't wait for BBD to be fixed, or still want to work on their plugins/themes:
> > go to
> > %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> > Change 5000 to 3889
> > Save file
> > Restart Discord client
> > Screenshot of where you should change the value: `
> > ![image](https://camo.githubusercontent.com/f2f0d5abc0b7a7acddd5c3f03e2728b207391324/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3238303830363437323932383139383635362f3634333930383032333236353339343732382f756e6b6e6f776e2e706e67)
> 
> And then I restart Discord, right?

It says at the bottom, that you restart.
For me, it only works on the stable discord.
It doesn't work on canary nor PTB

**Comment by Takka16** [comment]
It did work, thanks a lot :D

**Comment by Xolotia** [comment]
> I have no affiliation with BandagedBD whatsoever, but I looked in the BetterDiscord2 Discord group and it appears that it's a known issue and DevilsLynnAvenged/ShadowDevilsAvenged has provided a temp fix. Here is their posts.
> 
> `For Mac Users Go To: Applications > Discord > Right Click on Discord and then click on Show Package Contents > Contents > Resources > app > better discord > index.js and change 5000 to 3889 in the “Object.keys(req.c).length < 5000) part `
> 
> ![image](https://user-images.githubusercontent.com/4473635/68708626-17a75e80-0562-11ea-98e5-25cd94e07a7b.png)
> 
> `This is for Linux users download bdctl from here https://raw.githubusercontent.com/bb010g/betterdiscordctl/temp-fix/betterdiscordctl and run its update command`
> 
> and for Windows users,
> ` Incase anyone can't wait for BBD to be fixed, or still want to work on their plugins/themes:
> go to
> %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> Change 5000 to 3889
> Save file
> Restart Discord client
> 
> Screenshot of where you should change the value: `
> ![image](https://camo.githubusercontent.com/f2f0d5abc0b7a7acddd5c3f03e2728b207391324/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3238303830363437323932383139383635362f3634333930383032333236353339343732382f756e6b6e6f776e2e706e67)

This made it work, thank you.

**Comment by VexioPL** [comment]
> I have no affiliation with BandagedBD whatsoever, but I looked in the BetterDiscord2 Discord group and it appears that it's a known issue and DevilsLynnAvenged/ShadowDevilsAvenged has provided a temp fix. Here is their posts.
> 
> `For Mac Users Go To: Applications > Discord > Right Click on Discord and then click on Show Package Contents > Contents > Resources > app > better discord > index.js and change 5000 to 3889 in the “Object.keys(req.c).length < 5000) part `
> 
> ![image](https://user-images.githubusercontent.com/4473635/68708626-17a75e80-0562-11ea-98e5-25cd94e07a7b.png)
> 
> `This is for Linux users download bdctl from here https://raw.githubusercontent.com/bb010g/betterdiscordctl/temp-fix/betterdiscordctl and run its update command`
> 
> and for Windows users,
> ` Incase anyone can't wait for BBD to be fixed, or still want to work on their plugins/themes:
> go to
> %localappdata%\Discord\app-0.0.305\resources\app\betterdiscord
> Change 5000 to 3889
> Save file
> Restart Discord client
> 
> Screenshot of where you should change the value: `
> ![image](https://camo.githubusercontent.com/f2f0d5abc0b7a7acddd5c3f03e2728b207391324/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3238303830363437323932383139383635362f3634333930383032333236353339343732382f756e6b6e6f776e2e706e67)

work, thanks

**Comment by EnderShadowborne** [comment]
Thanks, it worked

**Comment by Axoonium** [comment]
Quick side comment: Do not use ctrl+R when restarting Discord to apply this fix, it won't work. Instead, completely close out of the program (such as through the task manager or alt+F4) and reopen it.

**Comment by FlashlightET** [comment]
didnt fix

**Comment by EnderShadowborne** [comment]
Please stop commenting as the topic is closed
