### ISSUE TITLE
Discord crash when open "Hmm, this is weird".

### ISSUE THREAD

**Issue by DeadLyBro** [Jiiks/BetterDiscordApp#939]
I have an error; says "Hmm, this is weird."
Platform: Windows 10 (32-Bit)
I guess it doesn't crash when you move it plugins to another place.
Sorry my bad English, I'm from Turkey :)
Thank for help.

**Comment by DeadLyBro** [comment]
I'm using these plugins;
Animated Status,
BD Context Menu,
Better Friend Count,
Better Role Colors,
In App Notifications,
Message Utilities,
Minespoiler(for fun :),
Replyer,
SendEmbeds,
StatusEverywhere,

Libs:
XenoLib,
ZeresPluginLibrary,
0 Plugin Library,
1 lib discord internals,
1 Xeno Lib.

**Comment by Raygius** [comment]
i had to disable Better Role Colors a few days ago, so that's probably the culprit for you

**Comment by DeadLyBro** [comment]
> i had to disable Better Role Colors a few days ago for the same reason, so that's probably the culprit for you

Thank for comment @Raygius . 
Now I will delete that plugin and try again.

**Comment by DeadLyBro** [comment]
Now it's working well thank for help @Raygius :)
