### ISSUE TITLE
BetterDiscord doesnt work with microsoft/PowerToys fancy zones

### ISSUE THREAD

**Issue by kdaniel2410** [Jiiks/BetterDiscordApp#961]
![bHptnLl8mi](https://user-images.githubusercontent.com/18488621/105610116-c4f04600-5da5-11eb-8e76-a370de1df42d.gif)
https://github.com/microsoft/PowerToys

**Comment by Strencher** [comment]
1. This repo is dead, here you can find the [maintained](https://github.com/rauenzi/BetterDiscordApp) repo.
2. That problem has nothing todo with BetterDiscord since it's just a clientmod.
