### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [Jiiks/BetterDiscordApp#964]
doesn't work on Windows - after installation it does not do anything

**Comment by Tropix126** [comment]
Wrong repo.
https://github.com/rauenzi/BBDInstaller/releases/tag/v1.0.5

**Comment by SirEpiclyAmazing** [comment]
i used BandagedBD

**Comment by Tropix126** [comment]
> i used BandagedBD

Then this should probably be directed to the BBD repo instead. This one hasn't been touched since 2019

**Comment by SirEpiclyAmazing** [comment]
> Then this should probably be directed to the BBD repo instead. This one hasn't been touched since 2019
BBD works
