### ISSUE TITLE
Discord crashes unexpectedly when proceding to different actions 

### ISSUE THREAD

**Issue by vsahler** [Jiiks/BetterDiscordApp#966]
Me and my friend came across a very specific bug in the actual version of discord : when proceeding to specific actions such as creating a new line in a message (by using shift + enter), discord crashes.
I started investigating and this bug is comming from better discord.
I first tried to run an older version from discord directly from 

```C:\Users\<user>\AppData\Local\Discord\app-0.0.308\Discord.exe```

And the problem wasn't here anymore. So I desactivated better discord by renaming 
```C:\Users\vince\AppData\Local\Discord\app-0.0.309\resources\app``` info ```app.temp```
And the bug wasn't here anymore. Is there a way to get a stacktrace or crash report ?

**Comment by Ironnix** [comment]
Got the same bug..
When i want to Ping someone or send a link Discord instant crashes.

**Comment by Overimagine1** [comment]
This is the wrong repo, this is for the og betterdiscord by Jiiks which is long dead

All you need to do is run the installer and just reinstall using the install option.

**Comment by Tropix126** [comment]
Dead repo and already fixed.
Reinject BD using the installer to fix.

**Comment by vsahler** [comment]
Worked for me. Thanks !
