### ISSUE TITLE
Help Meeee

### ISSUE THREAD

**Issue by SudgYT** [Jiiks/BetterDiscordApp#974]
Help Me, BetterDiscord Doesn't Work
[Image](https://i.imgur.com/WVg1X6Y.jpg)

**Comment by dav1312** [comment]
This is the wrong repo. The correct repo would be https://github.com/rauenzi/BetterDiscordApp

**Comment by SudgYT** [comment]
> This is the wrong repo. The correct repo would be https://github.com/rauenzi/BetterDiscordApp

ok
