### ISSUE TITLE
"Better Discord Seems to have crashed your Discord client"

### ISSUE THREAD

**Issue by cory4** [Jiiks/BetterDiscordApp#979]
![Screenshot_1](https://user-images.githubusercontent.com/56929051/115911721-18426500-a477-11eb-86c2-5c8103aa382a.png)
Imma use the latest discord and the latest 1.1.0 BD Build and when im wanna try to start discord it shown me "Better Discord Seems to have crashed your Discord client"
Reinstall of Discord and BD didn't helps

**Comment by Tropix126** [comment]
If you have plugins, try uninstalling them.
If you don't have plugins, try deleting the entire ./BetterDiscord directory in %appdata% then reinstalling BD.]

**Comment by cory4** [comment]
![image](https://user-images.githubusercontent.com/56929051/115912496-14631280-a478-11eb-9104-998e1f5f668f.png)
now new problem

**Comment by cory4** [comment]
fixed, done, thx <3

**Comment by Leo59054** [comment]
> che

e come si risolve?
