### ISSUE TITLE
Unique Issue; Installer Wont Open.

### ISSUE THREAD

**Issue by OFWModz** [Jiiks/BetterDiscordApp#984]
The latest version of the betterdiscord installer and even old versions simply do not open for me. Here is a screenshot 
![image](https://user-images.githubusercontent.com/36628963/126049954-6faaf36f-8f9b-4074-9af3-267fb6952910.png)

**Comment by identity7** [comment]
This repo is deprecated. New one is in #info

And go to #support and look in the pins for your solution. It's in there

**Comment by identity7** [comment]
> The latest version of the betterdiscord installer and even old versions simply do not open for me. Here is a screenshot 
> 
> ![image](https://user-images.githubusercontent.com/36628963/126049954-6faaf36f-8f9b-4074-9af3-267fb6952910.png)
> 
> 

This repo is deprecated. New one is in #info

And go to #support and look in the pins for your solution. It's in there
