### ISSUE TITLE
BandageBD stuck at "Extracting BandagedBD package".

### ISSUE THREAD

**Issue by FreyZinn** [Jiiks/BetterDiscordApp#985]
Hello, recently I tried to install Better Discord and on BandageBD, I am stuck at "Extracting BandagedBD package", I tried multiple things like "Run as administrator", in Downloads folder, but I'm still stuck, with the other installer I saw, I'm not stuck but when I launch Discord, It says: "Better Discord Seems to have crashed your Discord client", and I tried fixes, even deleting ./BetterDiscord and re-installing, etc.. I still crash, so with both installers, I can't install Better Discord and I don't know why. I tried a lot of fixes but still nothing. I stayed 30 minutes straight at "Extracting BandagedBD package" waiting until it does it, but when I go check in ./resources it extracted the file but it's stuck in BandageBD for some reason. I'll try to attach an image of it stuck and the zip extracted.
Thanks for reading,
FreyZinn.
![3_6](https://user-images.githubusercontent.com/65310654/127029845-1633babc-4776-42c0-8080-a4a53a5204a2.PNG)

**Comment by doggybootsy** [comment]
It might be that bandaged bd is extremely out of date

**Comment by FreyZinn** [comment]
> It might be that bandaged bd is extremely out of date

no i updated it it said to me to update it to 1.0.5 and it didn't worked still

**Comment by doggybootsy** [comment]
The latest version is 1.2.0

**Comment by FreyZinn** [comment]
> The latest version is 1.2.0

Where can I try to download that installer??

**Comment by doggybootsy** [comment]
https://betterdiscord.app

**Comment by FreyZinn** [comment]
> https://betterdiscord.app

thanks alot!
