### ISSUE TITLE
BetterDiscord has destroyed my discord

### ISSUE THREAD

**Issue by Nxbulah** [Jiiks/BetterDiscordApp#987]
So i went to open my discord and get the error "BetterDiscord has automatically disabled itself temporarily" So i think alright ill just go repair with BD setup. I do it and it doesnt do anything so i delete everything from better discord from my pc. At first it wouldnt let me delete certain files... like ASAR... then it wouldnt let me uninstall discord. Now it wont let me set up discord. I feel like this is due to BD. Please help!

**Comment by identity7** [comment]
1. this is the old repo and afaik is no longer maintained(current repo: https://github.com/BetterDiscord/BetterDiscord/issues)
2. this is likely fixed by manually updating 0PluginLibrary.plugin.js
https://github.com/BetterDiscord/BetterDiscord/issues/995 for instructions
