### ISSUE TITLE
Server switch malfunction on Windows 11

### ISSUE THREAD

**Issue by Suvraneel** [Jiiks/BetterDiscordApp#988]
### Ever since I upgraded to Windows 11, the server switches stop working & clicking on the server icons doesn't do anything...
![Screen Record](https://user-images.githubusercontent.com/63473496/136666017-03daa2f6-c58c-44bf-95b0-35bd7836d9e2.gif)

#### I've tried 
- unloading plugins
- reinstalling multiple times...
`Seems to be a Win11 compatibility issue...`
Consequently, I've had to disable BetterDC... 

### To replicate : 
- Just wait for 2-3 mins after Discord's launch in Win11
- Restarting Dc fixes the issue for like 30 seconds after which it goes back to the inactive state

**Comment by christiankek** [comment]
This is the wrong repo, and even then this isn't a BD issue. This is an issue with DevilBro's plugins.

**Comment by Suvraneel** [comment]
@christiankek My bad!
Thanks for informing ... Lemme see, if not will open in actual repo
