### ISSUE TITLE
Emotes aren't in-line when using compact mode

### ISSUE THREAD

**Issue by sillypears** [Jiiks/BetterDiscordApp#99]
When using Better Discord with the base compact mode enabled, emotes that are converted to the twitch version are placed on top of the username.
![image](https://cloud.githubusercontent.com/assets/13240985/11901166/1925cf2e-a578-11e5-8bca-75432c780926.png)

When using normal mode, these emotes work fine.
![image](https://cloud.githubusercontent.com/assets/13240985/11901191/32fad98a-a578-11e5-8c66-bfa945157bb1.png)

Is this a known bug? If it is, are there plans to correct it?

Thanks!

**Comment by Jiiks** [comment]
It is a known bug and it's on the todo list :+1:

**Comment by Jiiks** [comment]
Well it should be fixed now :P 
Simply restard Discord to fetch the latest css :+1:

**Comment by sillypears** [comment]
Wow thanks! Great service :D
