### ISSUE TITLE
Microsoft JScript compilation error 800A03EA with a plugin 

### ISSUE THREAD

**Issue by FireFoxOff** [Jiiks/BetterDiscordApp#991]
Hello everyone! I have a small problem concerning the animated status plugin.
I installed the plugin a few weeks ago and it worked very well. Until the day this error appears on my Discord:
![Capture d’écran 2021-11-05 210151](https://user-images.githubusercontent.com/93219091/140575068-d2610806-a762-44e3-b965-6e36dc582883.png)
The plugin also disappeared from my list.
So I tried to reinstall the plugin as it disappeared but a new interface appears when I click on it:
![Capture d’écran 2021-11-05 184700](https://user-images.githubusercontent.com/93219091/140575611-a1a87798-408d-4c95-a0a0-6bfd3772846a.png)
I reinstalled everything, Discord, BetterDiscord, the plugin again, nothing does! The syntax error is still there.
Especially since computers aren’t my strong suit.
I hope someone can solve this problem. See you next time!
Thank you in advance!

**Comment by christiankek** [comment]
1. Animated status is not supported and will get your account terminated if you use it.
2. This is the wrong repo.
